const spec = @import("csl_spec.zig");
const W = @import("emit_csl_ir_walk.zig");

pub const EmitError = W.EmitError;

pub fn emitLayout(buf: []u8, pos: *usize) EmitError!void {
    try W.write(buf, pos, "// Layout: dense GEMV with hidden x-shards and vocab y-shards.\n");
    try W.write(buf, pos, "// Each PE row reduces its hidden partials into the row sink.\n\n");
    try W.write(buf, pos, "param width: u16;\n");
    try W.write(buf, pos, "param height: u16;\n");
    try W.write(buf, pos, "param out_dim: i16;\n");
    try W.write(buf, pos, "param out_dim_per_pe: i16;\n");
    try W.write(buf, pos, "param in_dim_per_pe: i16;\n\n");
    try W.write(buf, pos, "const memcpy = @import_module(\"<memcpy/get_params>\", .{\n");
    try W.write(buf, pos, "    .width = width,\n");
    try W.write(buf, pos, "    .height = height,\n");
    try W.write(buf, pos, "});\n\n");
    try W.write(buf, pos, "const reduce_color: color = @get_color(4);\n\n");
    try W.write(buf, pos, "layout {\n");
    try W.write(buf, pos, "    @set_rectangle(width, height);\n\n");
    try W.write(buf, pos, "    for (@range(u16, height)) |pe_y| {\n");
    try W.write(buf, pos, "        for (@range(u16, width)) |pe_x| {\n");
    try W.write(buf, pos, "            @set_tile_code(pe_x, pe_y, \"");
    try W.write(buf, pos, spec.PE_PROGRAM_FILENAME);
    try W.write(buf, pos, "\", .{\n");
    try W.write(buf, pos, "                .memcpy_params = memcpy.get_params(pe_x),\n");
    try W.write(buf, pos, "                .pe_id = @as(i16, pe_x),\n");
    try W.write(buf, pos, "                .num_pes = @as(i16, width),\n");
    try W.write(buf, pos, "                .reduce_color = reduce_color,\n");
    try W.write(buf, pos, "                .out_dim_per_pe = out_dim_per_pe,\n");
    try W.write(buf, pos, "                .in_dim_per_pe = in_dim_per_pe,\n");
    try W.write(buf, pos, "            });\n");
    try W.write(buf, pos, "            if (width > 1) {\n");
    try W.write(buf, pos, "                if (pe_x == 0) {\n");
    try W.write(buf, pos, "                    @set_color_config(pe_x, pe_y, reduce_color, .{\n");
    try W.write(buf, pos, "                        .routes = .{ .rx = .{RAMP}, .tx = .{EAST} },\n");
    try W.write(buf, pos, "                    });\n");
    try W.write(buf, pos, "                } else if (pe_x == width - 1) {\n");
    try W.write(buf, pos, "                    @set_color_config(pe_x, pe_y, reduce_color, .{\n");
    try W.write(buf, pos, "                        .routes = .{ .rx = .{WEST}, .tx = .{RAMP} },\n");
    try W.write(buf, pos, "                    });\n");
    try W.write(buf, pos, "                } else {\n");
    try W.write(buf, pos, "                    @set_color_config(pe_x, pe_y, reduce_color, .{\n");
    try W.write(buf, pos, "                        .routes = .{ .rx = .{WEST}, .tx = .{EAST} },\n");
    try W.write(buf, pos, "                    });\n");
    try W.write(buf, pos, "                }\n");
    try W.write(buf, pos, "            }\n");
    try W.write(buf, pos, "        }\n");
    try W.write(buf, pos, "    }\n\n");
    try W.write(buf, pos, "    @export_name(\"activation\", [*]f16, true);\n");
    try W.write(buf, pos, "    @export_name(\"weight\", [*]f16, true);\n");
    try W.write(buf, pos, "    @export_name(\"output\", [*]f32, true);\n");
    try W.write(buf, pos, "    @export_name(\"compute\", fn()void);\n");
    try W.write(buf, pos, "}\n");
}

pub fn emitPeProgram(buf: []u8, pos: *usize) EmitError!void {
    try W.write(buf, pos, "// PE program: dense GEMV, f16 inputs/weights with f32 logits.\n");
    try W.write(buf, pos, "// weight is staged as [out_dim_per_pe, in_dim_per_pe] per PE.\n\n");
    try W.write(buf, pos, "param memcpy_params;\n");
    try W.write(buf, pos, "param pe_id: i16;\n");
    try W.write(buf, pos, "param num_pes: i16;\n");
    try W.write(buf, pos, "param reduce_color: color;\n");
    try W.write(buf, pos, "param out_dim_per_pe: i16;\n");
    try W.write(buf, pos, "param in_dim_per_pe: i16;\n\n");
    try W.write(buf, pos, "const sys_mod = @import_module(\"<memcpy/memcpy>\", memcpy_params);\n");
    try W.write(buf, pos, "\n");
    try W.write(buf, pos, "var activation: [in_dim_per_pe]f16 = @zeros([in_dim_per_pe]f16);\n");
    try W.write(buf, pos, "var weight: [out_dim_per_pe * in_dim_per_pe]f16 = @zeros([out_dim_per_pe * in_dim_per_pe]f16);\n");
    try W.write(buf, pos, "var partial: [out_dim_per_pe]f32 = @zeros([out_dim_per_pe]f32);\n");
    try W.write(buf, pos, "var output: [out_dim_per_pe]f32 = @zeros([out_dim_per_pe]f32);\n");
    try W.write(buf, pos, "\n");
    try W.write(buf, pos, "var activation_ptr: [*]f16 = &activation;\n");
    try W.write(buf, pos, "var weight_ptr: [*]f16 = &weight;\n");
    try W.write(buf, pos, "var output_ptr: [*]f32 = &output;\n\n");
    try W.write(buf, pos, "var scratch_in: [out_dim_per_pe]f32 = @zeros([out_dim_per_pe]f32);\n");
    try W.write(buf, pos, "var scratch_out: [out_dim_per_pe]f32 = @zeros([out_dim_per_pe]f32);\n");
    try W.write(buf, pos, "const scratch_in_dsd = @get_dsd(mem1d_dsd, .{ .tensor_access = |i|{out_dim_per_pe} -> scratch_in[i] });\n");
    try W.write(buf, pos, "const scratch_out_dsd = @get_dsd(mem1d_dsd, .{ .tensor_access = |i|{out_dim_per_pe} -> scratch_out[i] });\n\n");
    try W.write(buf, pos, "const reduce_out_q = @get_output_queue(2);\n");
    try W.write(buf, pos, "const reduce_in_q = @get_input_queue(2);\n");
    try W.write(buf, pos, "const reduce_out = @get_dsd(fabout_dsd, .{ .extent = out_dim_per_pe, .output_queue = reduce_out_q });\n");
    try W.write(buf, pos, "const reduce_in = @get_dsd(fabin_dsd, .{ .extent = out_dim_per_pe, .input_queue = reduce_in_q });\n\n");
    try W.write(buf, pos, "const reduce_task_id: local_task_id = @get_local_task_id(10);\n");
    try W.write(buf, pos, "const send_done_id: local_task_id = @get_local_task_id(11);\n\n");
    try W.write(buf, pos, "fn compute() void {\n");
    try W.write(buf, pos, "    for (@range(i16, out_dim_per_pe)) |row| {\n");
    try W.write(buf, pos, "        var sum: f32 = 0.0;\n");
    try W.write(buf, pos, "        const row_base = @as(u32, row) * @as(u32, in_dim_per_pe);\n");
    try W.write(buf, pos, "        for (@range(i16, in_dim_per_pe)) |col| {\n");
    try W.write(buf, pos, "            const idx = row_base + @as(u32, col);\n");
    try W.write(buf, pos, "            sum += @as(f32, activation[@as(u32, col)]) * @as(f32, weight[idx]);\n");
    try W.write(buf, pos, "        }\n");
    try W.write(buf, pos, "        partial[@as(u32, row)] = sum;\n");
    try W.write(buf, pos, "    }\n");
    try W.write(buf, pos, "    if (num_pes == 1) {\n");
    try W.write(buf, pos, "        for (@range(i16, out_dim_per_pe)) |i| {\n");
    try W.write(buf, pos, "            output[@as(u32, i)] = partial[@as(u32, i)];\n");
    try W.write(buf, pos, "        }\n");
    try W.write(buf, pos, "        sys_mod.unblock_cmd_stream();\n");
    try W.write(buf, pos, "    } else if (pe_id == 0) {\n");
    try W.write(buf, pos, "        for (@range(i16, out_dim_per_pe)) |i| {\n");
    try W.write(buf, pos, "            scratch_out[@as(u32, i)] = partial[@as(u32, i)];\n");
    try W.write(buf, pos, "        }\n");
    try W.write(buf, pos, "        @mov32(reduce_out, scratch_out_dsd, .{ .async = true, .unblock = send_done_id });\n");
    try W.write(buf, pos, "    } else {\n");
    try W.write(buf, pos, "        @mov32(scratch_in_dsd, reduce_in, .{ .async = true, .activate = reduce_task_id });\n");
    try W.write(buf, pos, "    }\n");
    try W.write(buf, pos, "}\n\n");
    try W.write(buf, pos, "task reduce_recv() void {\n");
    try W.write(buf, pos, "    for (@range(i16, out_dim_per_pe)) |i| {\n");
    try W.write(buf, pos, "        output[@as(u32, i)] = partial[@as(u32, i)] + scratch_in[@as(u32, i)];\n");
    try W.write(buf, pos, "    }\n");
    try W.write(buf, pos, "    if (pe_id != num_pes - 1) {\n");
    try W.write(buf, pos, "        for (@range(i16, out_dim_per_pe)) |i| {\n");
    try W.write(buf, pos, "            scratch_out[@as(u32, i)] = output[@as(u32, i)];\n");
    try W.write(buf, pos, "        }\n");
    try W.write(buf, pos, "        @mov32(reduce_out, scratch_out_dsd, .{ .async = true, .unblock = send_done_id });\n");
    try W.write(buf, pos, "    } else {\n");
    try W.write(buf, pos, "        sys_mod.unblock_cmd_stream();\n");
    try W.write(buf, pos, "    }\n");
    try W.write(buf, pos, "}\n\n");
    try W.write(buf, pos, "task send_done_task() void {\n");
    try W.write(buf, pos, "    sys_mod.unblock_cmd_stream();\n");
    try W.write(buf, pos, "}\n\n");
    try W.write(buf, pos, "comptime {\n");
    try W.write(buf, pos, "    @bind_local_task(reduce_recv, reduce_task_id);\n");
    try W.write(buf, pos, "    @bind_local_task(send_done_task, send_done_id);\n");
    try W.write(buf, pos, "    @block(send_done_id);\n");
    try W.write(buf, pos, "    if (@is_arch(\"wse3\")) {\n");
    try W.write(buf, pos, "        @initialize_queue(reduce_out_q, .{ .color = reduce_color });\n");
    try W.write(buf, pos, "        @initialize_queue(reduce_in_q, .{ .color = reduce_color });\n");
    try W.write(buf, pos, "    }\n");
    try W.write(buf, pos, "    @export_symbol(activation_ptr, \"activation\");\n");
    try W.write(buf, pos, "    @export_symbol(weight_ptr, \"weight\");\n");
    try W.write(buf, pos, "    @export_symbol(output_ptr, \"output\");\n");
    try W.write(buf, pos, "    @export_symbol(compute);\n");
    try W.write(buf, pos, "}\n");
}
