const std = @import("std");
const ir = @import("ir.zig");
const maps = @import("emit_hlsl_maps.zig");
const stage_render = @import("emit_hlsl_stage.zig");
const texture = @import("emit_hlsl_texture.zig");
const layout = @import("layout_utils.zig");

pub const EmitError = error{
    OutputTooLarge,
    InvalidIr,
};

pub const MAX_OUTPUT: usize = 256 * 1024;

pub fn emit(module: *const ir.Module, out: []u8) EmitError!usize {
    var emitter = Emitter{ .module = module, .buf = out };
    try emitter.emit_root();
    return emitter.pos;
}

const Emitter = struct {
    module: *const ir.Module,
    buf: []u8,
    pos: usize = 0,
    indent: usize = 0,

    fn emit_root(self: *Emitter) EmitError!void {
        try self.write("// Generated by doe_wgsl/emit_hlsl.zig\n");
        try self.write("uint doe_atomicLoad(inout uint value) { uint result; InterlockedOr(value, 0u, result); return result; }\n");
        try self.write("void doe_atomicStore(inout uint value, uint next) { uint ignored; InterlockedExchange(value, next, ignored); }\n");
        try self.write("uint doe_atomicAdd(inout uint v, uint a) { uint r; InterlockedAdd(v, a, r); return r; }\n");
        try self.write("uint doe_atomicSub(inout uint v, uint a) { uint r; InterlockedAdd(v, 0u - a, r); return r; }\n");
        try self.write("uint doe_atomicMin(inout uint v, uint a) { uint r; InterlockedMin(v, a, r); return r; }\n");
        try self.write("uint doe_atomicMax(inout uint v, uint a) { uint r; InterlockedMax(v, a, r); return r; }\n");
        try self.write("uint doe_atomicAnd(inout uint v, uint a) { uint r; InterlockedAnd(v, a, r); return r; }\n");
        try self.write("uint doe_atomicOr(inout uint v, uint a) { uint r; InterlockedOr(v, a, r); return r; }\n");
        try self.write("uint doe_atomicXor(inout uint v, uint a) { uint r; InterlockedXor(v, a, r); return r; }\n");
        try self.write("uint doe_atomicExchange(inout uint v, uint a) { uint r; InterlockedExchange(v, a, r); return r; }\n");
        try self.write("int doe_atomicLoad(inout int value) { int result; InterlockedOr(value, 0, result); return result; }\n");
        try self.write("void doe_atomicStore(inout int value, int next) { int ignored; InterlockedExchange(value, next, ignored); }\n");
        try self.write("int doe_atomicAdd(inout int v, int a) { int r; InterlockedAdd(v, a, r); return r; }\n");
        try self.write("int doe_atomicSub(inout int v, int a) { int r; InterlockedAdd(v, -a, r); return r; }\n");
        try self.write("int doe_atomicMin(inout int v, int a) { int r; InterlockedMin(v, a, r); return r; }\n");
        try self.write("int doe_atomicMax(inout int v, int a) { int r; InterlockedMax(v, a, r); return r; }\n");
        try self.write("int doe_atomicAnd(inout int v, int a) { int r; InterlockedAnd(v, a, r); return r; }\n");
        try self.write("int doe_atomicOr(inout int v, int a) { int r; InterlockedOr(v, a, r); return r; }\n");
        try self.write("int doe_atomicXor(inout int v, int a) { int r; InterlockedXor(v, a, r); return r; }\n");
        try self.write("int doe_atomicExchange(inout int v, int a) { int r; InterlockedExchange(v, a, r); return r; }\n");
        try self.write("float2 doe_unpack2x16float(uint v) { return float2(f16tof32(v & 0xFFFFu), f16tof32(v >> 16u)); }\n");
        try self.write("uint doe_pack2x16float(float2 v) { return f32tof16(v.x) | (f32tof16(v.y) << 16u); }\n");
        try self.write("float4 doe_unpack4x8unorm(uint v) { return float4(v & 0xFFu, (v >> 8u) & 0xFFu, (v >> 16u) & 0xFFu, v >> 24u) / 255.0; }\n");
        try self.write("float4 doe_unpack4x8snorm(uint v) { int4 s = int4(int(v << 24u) >> 24, int(v << 16u) >> 24, int(v << 8u) >> 24, int(v) >> 24); return clamp(float4(s) / 127.0, -1.0, 1.0); }\n");
        try self.write("uint doe_pack4x8unorm(float4 v) { uint4 c = uint4(round(saturate(v) * 255.0)); return c.x | (c.y << 8u) | (c.z << 16u) | (c.w << 24u); }\n");
        try self.write("uint doe_pack4x8snorm(float4 v) { int4 c = int4(round(clamp(v, -1.0, 1.0) * 127.0)); uint4 b = uint4(c) & 0xFFu; return b.x | (b.y << 8u) | (b.z << 16u) | (b.w << 24u); }\n");
        try self.emit_structs();
        try self.emit_globals();
        try self.emit_global_helpers();
        try self.emit_functions();
    }

    fn emit_structs(self: *Emitter) EmitError!void {
        for (self.module.structs.items) |struct_def| {
            try self.write("\nstruct ");
            try self.write(struct_def.name);
            try self.write(" {\n");
            self.indent += 4;
            for (struct_def.fields.items) |field| {
                try self.write_indent();
                try self.emit_typed_name(field.ty, field.name);
                try self.write(";\n");
            }
            self.indent -= 4;
            try self.write("};\n");
        }
    }

    fn emit_globals(self: *Emitter) EmitError!void {
        for (self.module.globals.items) |global| {
            if (global.binding != null) {
                try self.emit_bound_global(global);
                continue;
            }
            switch (global.class) {
                .var_ => {
                    const addr_space = global.addr_space orelse continue;
                    switch (addr_space) {
                        .workgroup => try self.write("\ngroupshared "),
                        .private => try self.write("\nstatic "),
                        else => continue,
                    }
                    try self.emit_typed_name(global.ty, global.name);
                    if (global.initializer) |constant| {
                        try self.write(" = ");
                        try self.emit_constant(constant, global.ty);
                    }
                    try self.write(";\n");
                },
                .const_, .override_ => {
                    try self.write("\nstatic const ");
                    try self.emit_typed_name(global.ty, global.name);
                    if (global.initializer) |constant| {
                        try self.write(" = ");
                        try self.emit_constant(constant, global.ty);
                    }
                    try self.write(";\n");
                },
                else => {},
            }
        }
    }

    fn emit_global_helpers(self: *Emitter) EmitError!void {
        for (self.module.globals.items) |global| {
            if ((global.addr_space orelse continue) != .storage) continue;
            if (global.binding == null) continue;
            switch (self.module.types.get(global.ty)) {
                .array => |arr| {
                    if (arr.len != null) continue;
                    try self.write("\nuint doe_arrayLength_");
                    try self.write(global.name);
                    try self.write("() {\n");
                    self.indent += 4;
                    try self.write_indent();
                    try self.write("uint count = 0u;\n");
                    try self.write_indent();
                    try self.write("uint stride = 0u;\n");
                    try self.write_indent();
                    try self.write(global.name);
                    try self.write(".GetDimensions(count, stride);\n");
                    try self.write_indent();
                    try self.write("return count;\n");
                    self.indent -= 4;
                    try self.write("}\n");
                },
                .struct_ => |struct_id| {
                    // Generate helpers for struct fields that are runtime-sized arrays.
                    try self.emit_struct_array_length_helpers(global, struct_id);
                },
                else => {},
            }
        }
        for (self.module.globals.items) |global| {
            if (global.binding == null) continue;
            switch (self.module.types.get(global.ty)) {
                .texture_2d, .texture_cube, .texture_depth_cube => {
                    try self.write("\nuint2 doe_textureDimensions_");
                    try self.write(global.name);
                    try self.write("(uint level) {\n");
                    self.indent += 4;
                    try self.write_indent();
                    try self.write("uint width = 0u;\n");
                    try self.write_indent();
                    try self.write("uint height = 0u;\n");
                    try self.write_indent();
                    try self.write("uint levels = 0u;\n");
                    try self.write_indent();
                    try self.write(global.name);
                    try self.write(".GetDimensions(level, width, height, levels);\n");
                    try self.write_indent();
                    try self.write("return uint2(width, height);\n");
                    self.indent -= 4;
                    try self.write("}\n");
                },
                .texture_2d_array => {
                    try self.write("\nuint2 doe_textureDimensions_");
                    try self.write(global.name);
                    try self.write("(uint level) {\n");
                    self.indent += 4;
                    try self.write_indent();
                    try self.write("uint width = 0u;\n");
                    try self.write_indent();
                    try self.write("uint height = 0u;\n");
                    try self.write_indent();
                    try self.write("uint elements = 0u;\n");
                    try self.write_indent();
                    try self.write("uint levels = 0u;\n");
                    try self.write_indent();
                    try self.write(global.name);
                    try self.write(".GetDimensions(level, width, height, elements, levels);\n");
                    try self.write_indent();
                    try self.write("return uint2(width, height);\n");
                    self.indent -= 4;
                    try self.write("}\n");
                },
                .storage_texture_2d => {
                    try self.write("\nuint2 doe_textureDimensions_");
                    try self.write(global.name);
                    try self.write("() {\n");
                    self.indent += 4;
                    try self.write_indent();
                    try self.write("uint width = 0u;\n");
                    try self.write_indent();
                    try self.write("uint height = 0u;\n");
                    try self.write_indent();
                    try self.write(global.name);
                    try self.write(".GetDimensions(width, height);\n");
                    try self.write_indent();
                    try self.write("return uint2(width, height);\n");
                    self.indent -= 4;
                    try self.write("}\n");
                },
                else => {},
            }
        }
    }

    /// Generate arrayLength helpers for runtime-sized array fields inside
    /// struct-typed storage globals.  Uses GetDimensions on the parent buffer:
    /// count=1, stride=total_buffer_size.  The array element count is then
    /// (stride - field_byte_offset) / sizeof(elem).
    fn emit_struct_array_length_helpers(self: *Emitter, global: ir.Global, struct_id: ir.StructId) EmitError!void {
        const struct_def = self.module.structs.items[struct_id];
        for (struct_def.fields.items, 0..) |field, field_idx| {
            const arr = switch (self.module.types.get(field.ty)) {
                .array => |a| a,
                else => continue,
            };
            if (arr.len != null) continue;
            const field_offset = hlsl_struct_field_offset(self.module, struct_def, @intCast(field_idx));
            const elem_size = hlsl_type_size(self.module, arr.elem);
            try self.write("\nuint doe_arrayLength_");
            try self.write(global.name);
            try self.write("_");
            try self.write(field.name);
            try self.write("() {\n");
            self.indent += 4;
            try self.write_indent();
            try self.write("uint count = 0u;\n");
            try self.write_indent();
            try self.write("uint stride = 0u;\n");
            try self.write_indent();
            try self.write(global.name);
            try self.write(".GetDimensions(count, stride);\n");
            try self.write_indent();
            try self.write("return (stride - ");
            try self.write_u32(field_offset);
            try self.write(") / ");
            try self.write_u32(elem_size);
            try self.write(";\n");
            self.indent -= 4;
            try self.write("}\n");
        }
    }

    fn emit_bound_global(self: *Emitter, global: ir.Global) EmitError!void {
        const binding = global.binding orelse return error.InvalidIr;
        if (global.addr_space) |addr_space| switch (addr_space) {
            .uniform => {
                try self.write("\ncbuffer doe_uniform_");
                try self.write(global.name);
                try self.write(" : register(b");
                try self.write_u32(binding.binding);
                try self.write(", space");
                try self.write_u32(binding.group);
                try self.write(") {\n");
                self.indent += 4;
                try self.write_indent();
                try self.emit_typed_name(global.ty, global.name);
                try self.write(";\n");
                self.indent -= 4;
                try self.write("};\n");
                return;
            },
            .storage => {
                try self.write("\n");
                if ((global.access orelse .read_write) == .read) {
                    try self.write("StructuredBuffer<");
                } else {
                    try self.write("RWStructuredBuffer<");
                }
                switch (self.module.types.get(global.ty)) {
                    .array => |arr| try self.emit_type_only(arr.elem),
                    else => try self.emit_type_only(global.ty),
                }
                try self.write("> ");
                try self.write(global.name);
                try self.write(" : register(");
                try self.write(if ((global.access orelse .read_write) == .read) "t" else "u");
                try self.write_u32(binding.binding);
                try self.write(", space");
                try self.write_u32(binding.group);
                try self.write(");\n");
                return;
            },
            else => {},
        };

        switch (self.module.types.get(global.ty)) {
            .sampler, .sampler_comparison => {
                try self.write("\nSamplerState ");
                try self.write(global.name);
                try self.write(" : register(s");
                try self.write_u32(binding.binding);
                try self.write(", space");
                try self.write_u32(binding.group);
                try self.write(");\n");
            },
            .texture_2d, .texture_2d_array, .texture_cube, .texture_multisampled_2d, .texture_depth_2d, .texture_depth_cube, .texture_3d => {
                try self.write("\n");
                try self.emit_type_only(global.ty);
                try self.write(" ");
                try self.write(global.name);
                try self.write(" : register(t");
                try self.write_u32(binding.binding);
                try self.write(", space");
                try self.write_u32(binding.group);
                try self.write(");\n");
            },
            .storage_texture_2d => |storage_tex| {
                try self.write("\n");
                if (storage_tex.access == .read) {
                    try self.write("Texture2D<float4> ");
                } else {
                    try self.write("RWTexture2D<float4> ");
                }
                try self.write(global.name);
                try self.write(" : register(");
                try self.write(if (storage_tex.access == .read) "t" else "u");
                try self.write_u32(binding.binding);
                try self.write(", space");
                try self.write_u32(binding.group);
                try self.write(");\n");
            },
            else => return error.InvalidIr,
        }
    }

    fn emit_functions(self: *Emitter) EmitError!void {
        for (self.module.functions.items, 0..) |_, index| {
            try self.emit_function(@intCast(index));
        }
    }

    fn emit_function(self: *Emitter, function_index: ir.FunctionId) EmitError!void {
        const function = self.module.functions.items[function_index];
        try self.write("\n");
        if (function.stage) |stage| {
            if (stage != .compute) return stage_render.emit_stage_function(self, function_index);
            try self.write("[numthreads(");
            try self.write_u32(function.workgroup_size[0]);
            try self.write(", ");
            try self.write_u32(function.workgroup_size[1]);
            try self.write(", ");
            try self.write_u32(function.workgroup_size[2]);
            try self.write(")]\n");
        }
        try self.emit_type_only(function.return_type);
        try self.write(" ");
        try self.write(function.name);
        try self.write("(");
        var first_param = true;
        for (function.params.items) |param| {
            // Builtins that map to HLSL intrinsic calls are not entry-point parameters
            if (param.io) |io_attr| {
                if (maps.hlsl_intrinsic_builtin(io_attr.builtin) != null) continue;
            }
            if (!first_param) try self.write(", ");
            try self.emit_param(param);
            first_param = false;
        }
        try self.write(") {\n");
        self.indent += 4;
        try self.emit_stmt(function, function.root_stmt);
        self.indent -= 4;
        try self.write("}\n");
    }

    fn emit_param(self: *Emitter, param: ir.Param) EmitError!void {
        switch (self.module.types.get(param.ty)) {
            .ref => |ref_ty| {
                if (ref_ty.access == .read) {
                    try self.write("in ");
                } else {
                    try self.write("inout ");
                }
                try self.emit_typed_name(ref_ty.elem, param.name);
            },
            else => try self.emit_typed_name(param.ty, param.name),
        }
        if (param.io) |io_attr| {
            if (io_attr.builtin != .none) {
                try self.write(" : ");
                try self.write(maps.hlsl_builtin_name(io_attr.builtin));
            } else if (io_attr.location != null) {
                return error.InvalidIr;
            }
        }
    }

    pub fn emit_stmt(self: *Emitter, function: ir.Function, stmt_id: ir.StmtId) EmitError!void {
        const stmt = function.stmts.items[stmt_id];
        switch (stmt) {
            .block => |range| {
                var i: u32 = 0;
                while (i < range.len) : (i += 1) {
                    try self.emit_stmt(function, function.stmt_children.items[range.start + i]);
                }
            },
            .local_decl => |decl| {
                const local = function.locals.items[decl.local];
                try self.write_indent();
                if (decl.is_const) try self.write("const ");
                try self.emit_typed_name(local.ty, local.name);
                if (decl.initializer) |expr_id| {
                    try self.write(" = ");
                    try self.emit_expr(function, expr_id);
                }
                try self.write(";\n");
            },
            .expr => |expr_id| {
                try self.write_indent();
                try self.emit_expr(function, expr_id);
                try self.write(";\n");
            },
            .assign => |assign| {
                try self.write_indent();
                try self.emit_expr(function, assign.lhs);
                try self.write(" ");
                try self.write(maps.assign_op_text(assign.op));
                try self.write(" ");
                try self.emit_expr(function, assign.rhs);
                try self.write(";\n");
            },
            .return_ => |value| {
                try self.write_indent();
                try self.write("return");
                if (value) |expr_id| {
                    try self.write(" ");
                    try self.emit_expr(function, expr_id);
                }
                try self.write(";\n");
            },
            .if_ => |if_stmt| {
                try self.write_indent();
                try self.write("if (");
                try self.emit_expr(function, if_stmt.cond);
                try self.write(") {\n");
                self.indent += 4;
                try self.emit_stmt(function, if_stmt.then_block);
                self.indent -= 4;
                try self.write_indent();
                try self.write("}");
                if (if_stmt.else_block) |else_block| {
                    try self.write(" else {\n");
                    self.indent += 4;
                    try self.emit_stmt(function, else_block);
                    self.indent -= 4;
                    try self.write_indent();
                    try self.write("}\n");
                } else {
                    try self.write("\n");
                }
            },
            .loop_ => |loop_stmt| {
                if (loop_stmt.init) |init_stmt| try self.emit_stmt(function, init_stmt);
                try self.write_indent();
                try self.write("while (");
                if (loop_stmt.cond) |cond| {
                    try self.emit_expr(function, cond);
                } else {
                    try self.write("true");
                }
                try self.write(") {\n");
                self.indent += 4;
                try self.emit_stmt(function, loop_stmt.body);
                if (loop_stmt.continuing) |continuing| try self.emit_stmt(function, continuing);
                self.indent -= 4;
                try self.write_indent();
                try self.write("}\n");
            },
            .switch_ => |switch_stmt| {
                try self.write_indent();
                try self.write("switch (");
                try self.emit_expr(function, switch_stmt.expr);
                try self.write(") {\n");
                self.indent += 4;
                var case_index: u32 = 0;
                while (case_index < switch_stmt.cases.len) : (case_index += 1) {
                    const case_node = function.switch_cases.items[switch_stmt.cases.start + case_index];
                    if (case_node.is_default) {
                        try self.write_indent();
                        try self.write("default:\n");
                    } else {
                        var selector_index: usize = 0;
                        while (selector_index < case_node.selectors.items.len) : (selector_index += 1) {
                            try self.write_indent();
                            try self.write("case ");
                            try self.emit_expr(function, case_node.selectors.items[selector_index]);
                            try self.write(":\n");
                        }
                    }
                    self.indent += 4;
                    try self.emit_stmt(function, case_node.body);
                    try self.write_indent();
                    try self.write("break;\n");
                    self.indent -= 4;
                }
                self.indent -= 4;
                try self.write_indent();
                try self.write("}\n");
            },
            .break_ => {
                try self.write_indent();
                try self.write("break;\n");
            },
            .continue_ => {
                try self.write_indent();
                try self.write("continue;\n");
            },
            .discard_ => {
                try self.write_indent();
                try self.write("discard;\n");
            },
        }
    }

    pub fn emit_expr(self: *Emitter, function: ir.Function, expr_id: ir.ExprId) EmitError!void {
        const expr = function.exprs.items[expr_id];
        switch (expr.data) {
            .bool_lit => |value| try self.write(if (value) "true" else "false"),
            .int_lit => |value| try self.write_u64(value),
            .float_lit => |value| try self.write_float(value),
            .param_ref => |index| {
                const param = function.params.items[index];
                if (param.io) |io_attr| {
                    if (maps.hlsl_intrinsic_builtin(io_attr.builtin)) |intrinsic| {
                        try self.write(intrinsic);
                        return;
                    }
                }
                try self.write(param.name);
            },
            .local_ref => |index| try self.write(function.locals.items[index].name),
            .global_ref => |index| try self.write(self.module.globals.items[index].name),
            .load => |inner| try self.emit_expr(function, inner),
            .unary => |unary| {
                try self.write("(");
                try self.write(maps.unary_op_text(unary.op));
                try self.emit_expr(function, unary.operand);
                try self.write(")");
            },
            .binary => |binary| {
                try self.write("(");
                try self.emit_expr(function, binary.lhs);
                try self.write(" ");
                try self.write(maps.binary_op_text(binary.op));
                try self.write(" ");
                try self.emit_expr(function, binary.rhs);
                try self.write(")");
            },
            .call => |call| try self.emit_call(function, expr.ty, call),
            .construct => |construct| {
                try self.emit_type_only(construct.ty);
                try self.write("(");
                try self.emit_expr_list(function, construct.args);
                try self.write(")");
            },
            .member => |member| {
                try self.emit_expr(function, member.base);
                try self.write(".");
                try self.write(member.field_name);
            },
            .index => |index| {
                try self.emit_expr(function, index.base);
                try self.write("[");
                try self.emit_expr(function, index.index);
                try self.write("]");
            },
        }
    }

    fn emit_call(self: *Emitter, function: ir.Function, result_ty: ir.TypeId, call: anytype) EmitError!void {
        if (call.kind == .builtin) {
            if (std.mem.eql(u8, call.name, "workgroupBarrier")) {
                try self.write("GroupMemoryBarrierWithGroupSync()");
                return;
            }
            if (std.mem.eql(u8, call.name, "storageBarrier")) {
                try self.write("AllMemoryBarrierWithGroupSync()");
                return;
            }
            if (std.mem.eql(u8, call.name, "bitcast")) {
                if (call.args.len != 1) return error.InvalidIr;
                try self.write(maps.hlsl_bitcast_fn(self.module, result_ty));
                try self.write("(");
                try self.emit_expr(function, function.expr_args.items[call.args.start]);
                try self.write(")");
                return;
            }
            if (std.mem.eql(u8, call.name, "arrayLength")) {
                if (call.args.len != 1) return error.InvalidIr;
                const target_expr = function.expr_args.items[call.args.start];
                switch (function.exprs.items[target_expr].data) {
                    .global_ref => |index| {
                        const global = self.module.globals.items[index];
                        switch (self.module.types.get(global.ty)) {
                            .array => |arr| {
                                if (arr.len != null) return error.InvalidIr;
                                try self.write("doe_arrayLength_");
                                try self.write(global.name);
                                try self.write("()");
                                return;
                            },
                            else => return error.InvalidIr,
                        }
                    },
                    .member => |member| {
                        // arrayLength(&buf.data) — struct field runtime-sized array.
                        const global_index = hlsl_resolve_member_global(function, member.base) orelse return error.InvalidIr;
                        const global = self.module.globals.items[global_index];
                        const struct_id = switch (self.module.types.get(global.ty)) {
                            .struct_ => |sid| sid,
                            else => return error.InvalidIr,
                        };
                        const struct_def = self.module.structs.items[struct_id];
                        if (member.field_index >= struct_def.fields.items.len) return error.InvalidIr;
                        const field = struct_def.fields.items[member.field_index];
                        try self.write("doe_arrayLength_");
                        try self.write(global.name);
                        try self.write("_");
                        try self.write(field.name);
                        try self.write("()");
                        return;
                    },
                    else => return error.InvalidIr,
                }
            }
            if (std.mem.eql(u8, call.name, "select")) {
                if (call.args.len != 3) return error.InvalidIr;
                try self.write("((");
                try self.emit_expr(function, function.expr_args.items[call.args.start + 2]);
                try self.write(") ? (");
                try self.emit_expr(function, function.expr_args.items[call.args.start + 1]);
                try self.write(") : (");
                try self.emit_expr(function, function.expr_args.items[call.args.start]);
                try self.write("))");
                return;
            }
            if (std.mem.eql(u8, call.name, "subgroupShuffleXor")) {
                if (call.args.len != 2) return error.InvalidIr;
                try self.write("WaveReadLaneAt(");
                try self.emit_expr(function, function.expr_args.items[call.args.start]);
                try self.write(", WaveGetLaneIndex() ^ ");
                try self.emit_expr(function, function.expr_args.items[call.args.start + 1]);
                try self.write(")");
                return;
            }
            if (try texture.emit_texture_builtin(self.module, self.buf, &self.pos, function, call.name, call.args)) return;
            if (std.mem.eql(u8, call.name, "degrees")) {
                if (call.args.len != 1) return error.InvalidIr;
                try self.write("(");
                try self.emit_expr(function, function.expr_args.items[call.args.start]);
                try self.write(" * 57.29577951308232)");
                return;
            }
            if (std.mem.eql(u8, call.name, "radians")) {
                if (call.args.len != 1) return error.InvalidIr;
                try self.write("(");
                try self.emit_expr(function, function.expr_args.items[call.args.start]);
                try self.write(" * 0.017453292519943295)");
                return;
            }
            if (maps.hlsl_renamed_builtin(call.name)) |mapped| {
                try self.write(mapped);
                try self.write("(");
                try self.emit_expr_list(function, call.args);
                try self.write(")");
                return;
            }
            if (maps.hlsl_builtin_passthrough(call.name)) {
                try self.write(call.name);
                try self.write("(");
                try self.emit_expr_list(function, call.args);
                try self.write(")");
                return;
            }
            return error.InvalidIr;
        }
        try self.write(call.name);
        try self.write("(");
        try self.emit_expr_list(function, call.args);
        try self.write(")");
    }

    fn emit_expr_list(self: *Emitter, function: ir.Function, range: ir.Range) EmitError!void {
        var i: u32 = 0;
        while (i < range.len) : (i += 1) {
            if (i > 0) try self.write(", ");
            try self.emit_expr(function, function.expr_args.items[range.start + i]);
        }
    }

    fn emit_constant(self: *Emitter, constant: ir.ConstantValue, ty: ir.TypeId) EmitError!void {
        _ = ty;
        switch (constant) {
            .bool => |value| try self.write(if (value) "true" else "false"),
            .int => |value| try self.write_u64(value),
            .float => |value| try self.write_float(value),
        }
    }

    pub fn emit_typed_name(self: *Emitter, ty: ir.TypeId, name: []const u8) EmitError!void {
        switch (self.module.types.get(ty)) {
            .array => |arr| {
                try self.emit_type_only(arr.elem);
                try self.write(" ");
                try self.write(name);
                if (arr.len) |len| {
                    try self.write("[");
                    try self.write_u32(len);
                    try self.write("]");
                } else {
                    return error.InvalidIr;
                }
            },
            else => {
                try self.emit_type_only(ty);
                try self.write(" ");
                try self.write(name);
            },
        }
    }

    pub fn emit_type_only(self: *Emitter, ty: ir.TypeId) EmitError!void {
        switch (self.module.types.get(ty)) {
            .scalar => |scalar| try self.write(switch (scalar) {
                .void => "void",
                .bool => "bool",
                .i32, .abstract_int => "int",
                .u32 => "uint",
                .f32, .abstract_float => "float",
                .f16 => "half",
            }),
            .vector => |vec| {
                const prefix = switch (self.module.types.get(vec.elem)) {
                    .scalar => |scalar| switch (scalar) {
                        .bool => "bool",
                        .i32, .abstract_int => "int",
                        .u32 => "uint",
                        .f32, .abstract_float => "float",
                        .f16 => "half",
                        else => return error.InvalidIr,
                    },
                    else => return error.InvalidIr,
                };
                try self.write(prefix);
                try self.write_u32(vec.len);
            },
            .matrix => |mat| {
                const prefix = switch (self.module.types.get(mat.elem)) {
                    .scalar => |scalar| switch (scalar) {
                        .f32, .abstract_float => "float",
                        .f16 => "half",
                        else => return error.InvalidIr,
                    },
                    else => return error.InvalidIr,
                };
                try self.write(prefix);
                try self.write_u32(mat.columns);
                try self.write("x");
                try self.write_u32(mat.rows);
            },
            .array => return error.InvalidIr,
            .atomic => |inner| switch (self.module.types.get(inner)) {
                .scalar => |scalar| switch (scalar) {
                    .u32 => try self.write("uint"),
                    .i32, .abstract_int => try self.write("int"),
                    else => return error.InvalidIr,
                },
                else => return error.InvalidIr,
            },
            .struct_ => |struct_id| try self.write(self.module.structs.items[struct_id].name),
            .sampler, .sampler_comparison => try self.write("SamplerState"),
            .texture_2d => |sample_ty| {
                try self.write("Texture2D<");
                try self.write(maps.texture_component(sample_ty));
                try self.write("4>");
            },
            .texture_2d_array => |sample_ty| {
                try self.write("Texture2DArray<");
                try self.write(maps.texture_component(sample_ty));
                try self.write("4>");
            },
            .texture_cube => |sample_ty| {
                try self.write("TextureCube<");
                try self.write(maps.texture_component(sample_ty));
                try self.write("4>");
            },
            .texture_multisampled_2d => |sample_ty| {
                try self.write("Texture2DMS<");
                try self.write(maps.texture_component(sample_ty));
                try self.write("4>");
            },
            .texture_depth_2d => try self.write("Texture2D<float>"),
            .texture_depth_cube => try self.write("TextureCube<float>"),
            .texture_3d => |sample_ty| {
                try self.write("Texture3D<");
                try self.write(maps.texture_component(sample_ty));
                try self.write("4>");
            },
            .storage_texture_2d => |storage_tex| {
                if (storage_tex.access == .read) {
                    try self.write("Texture2D<float4>");
                } else {
                    try self.write("RWTexture2D<float4>");
                }
            },
            .ref => |ref_ty| try self.emit_type_only(ref_ty.elem),
        }
    }
    pub fn write(self: *Emitter, text: []const u8) EmitError!void {
        if (self.pos + text.len > self.buf.len) return error.OutputTooLarge;
        @memcpy(self.buf[self.pos .. self.pos + text.len], text);
        self.pos += text.len;
    }

    pub fn write_indent(self: *Emitter) EmitError!void {
        var i: usize = 0;
        while (i < self.indent) : (i += 1) try self.write(" ");
    }

    pub fn write_u32(self: *Emitter, value: u32) EmitError!void {
        var buf: [32]u8 = undefined;
        const text = std.fmt.bufPrint(&buf, "{}", .{value}) catch return error.OutputTooLarge;
        try self.write(text);
    }

    fn write_u64(self: *Emitter, value: u64) EmitError!void {
        var buf: [32]u8 = undefined;
        const text = std.fmt.bufPrint(&buf, "{}", .{value}) catch return error.OutputTooLarge;
        try self.write(text);
    }

    fn write_float(self: *Emitter, value: f64) EmitError!void {
        var buf: [64]u8 = undefined;
        const text = std.fmt.bufPrint(&buf, "{d}", .{value}) catch return error.OutputTooLarge;
        try self.write(text);
        if (std.mem.indexOfScalar(u8, text, '.') == null and std.mem.indexOfAny(u8, text, "eE") == null) {
            try self.write(".0");
        }
    }
};

/// Walk a chain of member/load expressions to find the root global_ref index.
fn hlsl_resolve_member_global(function: ir.Function, expr_id: ir.ExprId) ?ir.GlobalId {
    var current = expr_id;
    while (true) {
        switch (function.exprs.items[current].data) {
            .global_ref => |index| return index,
            .member => |m| current = m.base,
            .load => |inner| current = inner,
            else => return null,
        }
    }
}

/// Compute the byte offset of a field in a struct for storage layout (std430).
fn hlsl_struct_field_offset(module: *const ir.Module, struct_def: ir.StructDef, target_field: u32) u32 {
    var offset: u32 = 0;
    for (struct_def.fields.items[0..target_field]) |field| {
        const field_align = hlsl_type_alignment(module, field.ty);
        offset = hlsl_round_up(offset, field_align);
        offset += hlsl_type_size(module, field.ty);
    }
    const target_align = hlsl_type_alignment(module, struct_def.fields.items[target_field].ty);
    return hlsl_round_up(offset, target_align);
}

fn hlsl_round_up(value: u32, alignment: u32) u32 {
    if (alignment <= 1) return value;
    const remainder = value % alignment;
    if (remainder == 0) return value;
    return value + alignment - remainder;
}

fn hlsl_type_alignment(module: *const ir.Module, ty: ir.TypeId) u32 {
    return switch (module.types.get(ty)) {
        .scalar => |s| switch (s) {
            .f16 => 2,
            .bool, .i32, .u32, .f32, .abstract_int, .abstract_float => 4,
            else => 4,
        },
        .vector => |v| hlsl_type_alignment(module, v.elem) * switch (v.len) {
            2 => @as(u32, 2),
            3, 4 => @as(u32, 4),
            else => 1,
        },
        .matrix => |m| hlsl_type_alignment(module, m.elem) * switch (m.rows) {
            2 => @as(u32, 2),
            3, 4 => @as(u32, 4),
            else => 1,
        },
        .array => |a| hlsl_type_alignment(module, a.elem),
        .atomic => |inner| hlsl_type_alignment(module, inner),
        .struct_ => |sid| blk: {
            var max_align: u32 = 1;
            for (module.structs.items[sid].fields.items) |field| {
                max_align = @max(max_align, hlsl_type_alignment(module, field.ty));
            }
            break :blk max_align;
        },
        else => 4,
    };
}

fn hlsl_type_size(module: *const ir.Module, ty: ir.TypeId) u32 {
    return switch (module.types.get(ty)) {
        .scalar => |s| switch (s) {
            .f16 => 2,
            .bool, .i32, .u32, .f32, .abstract_int, .abstract_float => 4,
            else => 4,
        },
        .vector => |v| hlsl_type_size(module, v.elem) * v.len,
        .matrix => |m| blk: {
            const col_size = hlsl_type_size(module, m.elem) * m.rows;
            const col_align = hlsl_type_alignment(module, m.elem) * switch (m.rows) {
                2 => @as(u32, 2),
                3, 4 => @as(u32, 4),
                else => 1,
            };
            const stride = hlsl_round_up(col_size, col_align);
            break :blk stride * m.columns;
        },
        .array => |a| blk: {
            if (a.len) |len| {
                const elem_size = hlsl_type_size(module, a.elem);
                const elem_align = hlsl_type_alignment(module, a.elem);
                const stride = hlsl_round_up(elem_size, elem_align);
                break :blk stride * len;
            }
            break :blk 0;
        },
        .atomic => |inner| hlsl_type_size(module, inner),
        .struct_ => |sid| blk: {
            var offset: u32 = 0;
            var max_align: u32 = 1;
            for (module.structs.items[sid].fields.items) |field| {
                const field_align = hlsl_type_alignment(module, field.ty);
                offset = hlsl_round_up(offset, field_align);
                offset += hlsl_type_size(module, field.ty);
                max_align = @max(max_align, field_align);
            }
            break :blk hlsl_round_up(offset, max_align);
        },
        else => 4,
    };
}
