const spec = @import("csl_spec.zig");
const W = @import("emit_csl_ir_walk.zig");

pub const EmitError = W.EmitError;

pub fn emitLayout(buf: []u8, pos: *usize) EmitError!void {
    try W.write(buf, pos, "// Layout: dense GEMV with hidden x-shards and vocab y-shards.\n");
    try W.write(buf, pos, "// Each PE row reduces its hidden partials into the row sink.\n\n");
    try W.write(buf, pos, "param width: u16;\n");
    try W.write(buf, pos, "param height: u16;\n");
    try W.write(buf, pos, "param out_dim: i16;\n");
    try W.write(buf, pos, "param out_dim_per_pe: i16;\n");
    try W.write(buf, pos, "param in_dim_per_pe: i16;\n\n");
    try W.write(buf, pos, "const memcpy = @import_module(\"<memcpy/get_params>\", .{\n");
    try W.write(buf, pos, "    .width = width,\n");
    try W.write(buf, pos, "    .height = height,\n");
    try W.write(buf, pos, "});\n\n");
    try W.write(buf, pos, "const c2d = @import_module(\"<collectives_2d/params>\");\n\n");
    try W.write(buf, pos, "layout {\n");
    try W.write(buf, pos, "    @set_rectangle(width, height);\n\n");
    try W.write(buf, pos, "    for (@range(u16, height)) |pe_y| {\n");
    try W.write(buf, pos, "        for (@range(u16, width)) |pe_x| {\n");
    try W.write(buf, pos, "            const c2d_tile_params = c2d.get_params(pe_x, pe_y, .{\n");
    try W.write(buf, pos, "                .x_colors      = .{ @get_color(4),         @get_color(5)         },\n");
    try W.write(buf, pos, "                .x_entrypoints = .{ @get_local_task_id(8), @get_local_task_id(9) },\n");
    try W.write(buf, pos, "                .y_colors      = .{ @get_color(6),         @get_color(7)         },\n");
    try W.write(buf, pos, "                .y_entrypoints = .{ @get_local_task_id(10), @get_local_task_id(11) },\n");
    try W.write(buf, pos, "            });\n");
    try W.write(buf, pos, "            @set_tile_code(pe_x, pe_y, \"");
    try W.write(buf, pos, spec.PE_PROGRAM_FILENAME);
    try W.write(buf, pos, "\", .{\n");
    try W.write(buf, pos, "                .memcpy_params = memcpy.get_params(pe_x),\n");
    try W.write(buf, pos, "                .c2d_params = c2d_tile_params,\n");
    try W.write(buf, pos, "                .pe_id = @as(i16, pe_x),\n");
    try W.write(buf, pos, "                .num_pes = @as(i16, width),\n");
    try W.write(buf, pos, "                .out_dim_per_pe = out_dim_per_pe,\n");
    try W.write(buf, pos, "                .in_dim_per_pe = in_dim_per_pe,\n");
    try W.write(buf, pos, "            });\n");
    try W.write(buf, pos, "        }\n");
    try W.write(buf, pos, "    }\n\n");
    try W.write(buf, pos, "    @export_name(\"activation\", [*]f16, true);\n");
    try W.write(buf, pos, "    @export_name(\"weight\", [*]f16, true);\n");
    try W.write(buf, pos, "    @export_name(\"output\", [*]f32, true);\n");
    try W.write(buf, pos, "    @export_name(\"compute\", fn()void);\n");
    try W.write(buf, pos, "}\n");
}

pub fn emitPeProgram(buf: []u8, pos: *usize) EmitError!void {
    try W.write(buf, pos, "// PE program: dense GEMV, f16 inputs/weights with f32 logits.\n");
    try W.write(buf, pos, "// weight is staged as [out_dim_per_pe, in_dim_per_pe] per PE.\n\n");
    try W.write(buf, pos, "param c2d_params;\n");
    try W.write(buf, pos, "param memcpy_params;\n");
    try W.write(buf, pos, "param pe_id: i16;\n");
    try W.write(buf, pos, "param num_pes: i16;\n");
    try W.write(buf, pos, "param out_dim_per_pe: i16;\n");
    try W.write(buf, pos, "param in_dim_per_pe: i16;\n\n");
    try W.write(buf, pos, "const sys_mod = @import_module(\"<memcpy/memcpy>\", memcpy_params);\n");
    try W.write(buf, pos, "const mpi_x = @import_module(\"<collectives_2d/pe>\", .{\n");
    try W.write(buf, pos, "    .dim_params = c2d_params.x,\n");
    try W.write(buf, pos, "    .queues = [2]u16{2, 4},\n");
    try W.write(buf, pos, "    .dest_dsr_ids = [1]u16{1},\n");
    try W.write(buf, pos, "    .src0_dsr_ids = [1]u16{1},\n");
    try W.write(buf, pos, "    .src1_dsr_ids = [1]u16{1},\n");
    try W.write(buf, pos, "});\n\n");
    try W.write(buf, pos, "var activation: [in_dim_per_pe]f16 = @zeros([in_dim_per_pe]f16);\n");
    try W.write(buf, pos, "var weight: [out_dim_per_pe * in_dim_per_pe]f16 = @zeros([out_dim_per_pe * in_dim_per_pe]f16);\n");
    try W.write(buf, pos, "var output: [out_dim_per_pe]f32 = @zeros([out_dim_per_pe]f32);\n");
    try W.write(buf, pos, "\n");
    try W.write(buf, pos, "var activation_ptr: [*]f16 = &activation;\n");
    try W.write(buf, pos, "var weight_ptr: [*]f16 = &weight;\n");
    try W.write(buf, pos, "var output_ptr: [*]f32 = &output;\n\n");
    try W.write(buf, pos, "const reduce_done_id: local_task_id = @get_local_task_id(12);\n\n");
    try W.write(buf, pos, "fn compute() void {\n");
    try W.write(buf, pos, "    for (@range(i16, out_dim_per_pe)) |row| {\n");
    try W.write(buf, pos, "        var sum: f32 = 0.0;\n");
    try W.write(buf, pos, "        const row_base = @as(u32, row) * @as(u32, in_dim_per_pe);\n");
    try W.write(buf, pos, "        for (@range(i16, in_dim_per_pe)) |col| {\n");
    try W.write(buf, pos, "            const idx = row_base + @as(u32, col);\n");
    try W.write(buf, pos, "            sum += @as(f32, activation[@as(u32, col)]) * @as(f32, weight[idx]);\n");
    try W.write(buf, pos, "        }\n");
    try W.write(buf, pos, "        output[@as(u32, row)] = sum;\n");
    try W.write(buf, pos, "    }\n");
    try W.write(buf, pos, "    mpi_x.init();\n");
    try W.write(buf, pos, "    mpi_x.reduce_fadds(@as(u16, num_pes - 1), @ptrcast([*]f32, &output), @ptrcast([*]f32, &output), @as(u16, out_dim_per_pe), reduce_done_id);\n");
    try W.write(buf, pos, "}\n\n");
    try W.write(buf, pos, "task reduce_done_task() void {\n");
    try W.write(buf, pos, "    sys_mod.unblock_cmd_stream();\n");
    try W.write(buf, pos, "}\n\n");
    try W.write(buf, pos, "comptime {\n");
    try W.write(buf, pos, "    @bind_local_task(reduce_done_task, reduce_done_id);\n");
    try W.write(buf, pos, "    @export_symbol(activation_ptr, \"activation\");\n");
    try W.write(buf, pos, "    @export_symbol(weight_ptr, \"weight\");\n");
    try W.write(buf, pos, "    @export_symbol(output_ptr, \"output\");\n");
    try W.write(buf, pos, "    @export_symbol(compute);\n");
    try W.write(buf, pos, "}\n");
}
