const _impl = @import("full/render/wgpu_render_assets.zig");
pub const RENDER_DRAW_SHADER_SOURCE = _impl.RENDER_DRAW_SHADER_SOURCE;
pub const RENDER_DRAW_VERTEX_DATA = _impl.RENDER_DRAW_VERTEX_DATA;
pub const RENDER_DRAW_UNIFORM_COLOR = _impl.RENDER_DRAW_UNIFORM_COLOR;
pub const RENDER_DRAW_TEXTURE_WIDTH = _impl.RENDER_DRAW_TEXTURE_WIDTH;
pub const RENDER_DRAW_TEXTURE_HEIGHT = _impl.RENDER_DRAW_TEXTURE_HEIGHT;
pub const RENDER_DRAW_TEXTURE_BYTES_PER_ROW = _impl.RENDER_DRAW_TEXTURE_BYTES_PER_ROW;
pub const RENDER_DRAW_TEXTURE_DATA = _impl.RENDER_DRAW_TEXTURE_DATA;
