const std = @import("std");
const ir = @import("ir.zig");

pub const EmitError = error{
    OutputTooLarge,
    InvalidIr,
};

pub const MAX_OUTPUT: usize = 256 * 1024;

pub fn emit(module: *const ir.Module, out: []u8) EmitError!usize {
    var emitter = Emitter{ .module = module, .buf = out };
    try emitter.emit_root();
    return emitter.pos;
}

const Emitter = struct {
    module: *const ir.Module,
    buf: []u8,
    pos: usize = 0,
    indent: usize = 0,

    fn emit_root(self: *Emitter) EmitError!void {
        try self.write("// Generated by doe_wgsl/emit_hlsl.zig\n");
        try self.write("uint doe_atomicLoad(inout uint value) { uint result; InterlockedOr(value, 0u, result); return result; }\n");
        try self.write("void doe_atomicStore(inout uint value, uint next) { uint ignored; InterlockedExchange(value, next, ignored); }\n");
        try self.emit_structs();
        try self.emit_globals();
        try self.emit_functions();
    }

    fn emit_structs(self: *Emitter) EmitError!void {
        for (self.module.structs.items) |struct_def| {
            try self.write("\nstruct ");
            try self.write(struct_def.name);
            try self.write(" {\n");
            self.indent += 4;
            for (struct_def.fields.items) |field| {
                try self.write_indent();
                try self.emit_typed_name(field.ty, field.name);
                try self.write(";\n");
            }
            self.indent -= 4;
            try self.write("};\n");
        }
    }

    fn emit_globals(self: *Emitter) EmitError!void {
        for (self.module.globals.items) |global| {
            if (global.binding != null) {
                try self.emit_bound_global(global);
                continue;
            }
            switch (global.class) {
                .var_ => {
                    const addr_space = global.addr_space orelse continue;
                    switch (addr_space) {
                        .workgroup => try self.write("\ngroupshared "),
                        .private => try self.write("\nstatic "),
                        else => continue,
                    }
                    try self.emit_typed_name(global.ty, global.name);
                    if (global.initializer) |constant| {
                        try self.write(" = ");
                        try self.emit_constant(constant, global.ty);
                    }
                    try self.write(";\n");
                },
                .const_, .override_ => {
                    try self.write("\nstatic const ");
                    try self.emit_typed_name(global.ty, global.name);
                    if (global.initializer) |constant| {
                        try self.write(" = ");
                        try self.emit_constant(constant, global.ty);
                    }
                    try self.write(";\n");
                },
                else => {},
            }
        }
    }

    fn emit_bound_global(self: *Emitter, global: ir.Global) EmitError!void {
        const binding = global.binding orelse return error.InvalidIr;
        if (global.addr_space) |addr_space| switch (addr_space) {
            .uniform => {
                try self.write("\ncbuffer doe_uniform_");
                try self.write(global.name);
                try self.write(" : register(b");
                try self.write_u32(binding.binding);
                try self.write(", space");
                try self.write_u32(binding.group);
                try self.write(") {\n");
                self.indent += 4;
                try self.write_indent();
                try self.emit_typed_name(global.ty, global.name);
                try self.write(";\n");
                self.indent -= 4;
                try self.write("};\n");
                return;
            },
            .storage => {
                try self.write("\n");
                if ((global.access orelse .read_write) == .read) {
                    try self.write("StructuredBuffer<");
                } else {
                    try self.write("RWStructuredBuffer<");
                }
                switch (self.module.types.get(global.ty)) {
                    .array => |arr| try self.emit_type_only(arr.elem),
                    else => try self.emit_type_only(global.ty),
                }
                try self.write("> ");
                try self.write(global.name);
                try self.write(" : register(");
                try self.write(if ((global.access orelse .read_write) == .read) "t" else "u");
                try self.write_u32(binding.binding);
                try self.write(", space");
                try self.write_u32(binding.group);
                try self.write(");\n");
                return;
            },
            else => {},
        };

        switch (self.module.types.get(global.ty)) {
            .sampler => {
                try self.write("\nSamplerState ");
                try self.write(global.name);
                try self.write(" : register(s");
                try self.write_u32(binding.binding);
                try self.write(", space");
                try self.write_u32(binding.group);
                try self.write(");\n");
            },
            .texture_2d => |sample_ty| {
                try self.write("\nTexture2D<");
                try self.write(texture_component(sample_ty));
                try self.write("4> ");
                try self.write(global.name);
                try self.write(" : register(t");
                try self.write_u32(binding.binding);
                try self.write(", space");
                try self.write_u32(binding.group);
                try self.write(");\n");
            },
            else => return error.InvalidIr,
        }
    }

    fn emit_functions(self: *Emitter) EmitError!void {
        for (self.module.functions.items, 0..) |_, index| {
            try self.emit_function(@intCast(index));
        }
    }

    fn emit_function(self: *Emitter, function_index: ir.FunctionId) EmitError!void {
        const function = self.module.functions.items[function_index];
        try self.write("\n");
        if (function.stage) |stage| {
            if (stage != .compute) return error.InvalidIr;
            try self.write("[numthreads(");
            try self.write_u32(function.workgroup_size[0]);
            try self.write(", ");
            try self.write_u32(function.workgroup_size[1]);
            try self.write(", ");
            try self.write_u32(function.workgroup_size[2]);
            try self.write(")]\n");
        }
        try self.emit_type_only(function.return_type);
        try self.write(" ");
        try self.write(function.name);
        try self.write("(");
        for (function.params.items, 0..) |param, index| {
            if (index > 0) try self.write(", ");
            try self.emit_param(param);
        }
        try self.write(") {\n");
        self.indent += 4;
        try self.emit_stmt(function, function.root_stmt);
        self.indent -= 4;
        try self.write("}\n");
    }

    fn emit_param(self: *Emitter, param: ir.Param) EmitError!void {
        try self.emit_typed_name(param.ty, param.name);
        if (param.io) |io_attr| {
            if (io_attr.builtin != .none) {
                try self.write(" : ");
                try self.write(hlsl_builtin_name(io_attr.builtin));
            } else if (io_attr.location != null) {
                return error.InvalidIr;
            }
        }
    }

    fn emit_stmt(self: *Emitter, function: ir.Function, stmt_id: ir.StmtId) EmitError!void {
        const stmt = function.stmts.items[stmt_id];
        switch (stmt) {
            .block => |range| {
                var i: u32 = 0;
                while (i < range.len) : (i += 1) {
                    try self.emit_stmt(function, function.stmt_children.items[range.start + i]);
                }
            },
            .local_decl => |decl| {
                const local = function.locals.items[decl.local];
                try self.write_indent();
                if (decl.is_const) try self.write("const ");
                try self.emit_typed_name(local.ty, local.name);
                if (decl.initializer) |expr_id| {
                    try self.write(" = ");
                    try self.emit_expr(function, expr_id);
                }
                try self.write(";\n");
            },
            .expr => |expr_id| {
                try self.write_indent();
                try self.emit_expr(function, expr_id);
                try self.write(";\n");
            },
            .assign => |assign| {
                try self.write_indent();
                try self.emit_expr(function, assign.lhs);
                try self.write(" ");
                try self.write(assign_op_text(assign.op));
                try self.write(" ");
                try self.emit_expr(function, assign.rhs);
                try self.write(";\n");
            },
            .return_ => |value| {
                try self.write_indent();
                try self.write("return");
                if (value) |expr_id| {
                    try self.write(" ");
                    try self.emit_expr(function, expr_id);
                }
                try self.write(";\n");
            },
            .if_ => |if_stmt| {
                try self.write_indent();
                try self.write("if (");
                try self.emit_expr(function, if_stmt.cond);
                try self.write(") {\n");
                self.indent += 4;
                try self.emit_stmt(function, if_stmt.then_block);
                self.indent -= 4;
                try self.write_indent();
                try self.write("}");
                if (if_stmt.else_block) |else_block| {
                    try self.write(" else {\n");
                    self.indent += 4;
                    try self.emit_stmt(function, else_block);
                    self.indent -= 4;
                    try self.write_indent();
                    try self.write("}\n");
                } else {
                    try self.write("\n");
                }
            },
            .loop_ => |loop_stmt| {
                if (loop_stmt.init) |init_stmt| try self.emit_stmt(function, init_stmt);
                try self.write_indent();
                try self.write("while (");
                if (loop_stmt.cond) |cond| {
                    try self.emit_expr(function, cond);
                } else {
                    try self.write("true");
                }
                try self.write(") {\n");
                self.indent += 4;
                try self.emit_stmt(function, loop_stmt.body);
                if (loop_stmt.continuing) |continuing| try self.emit_stmt(function, continuing);
                self.indent -= 4;
                try self.write_indent();
                try self.write("}\n");
            },
            .switch_ => |switch_stmt| {
                try self.write_indent();
                try self.write("switch (");
                try self.emit_expr(function, switch_stmt.expr);
                try self.write(") {\n");
                self.indent += 4;
                var case_index: u32 = 0;
                while (case_index < switch_stmt.cases.len) : (case_index += 1) {
                    const case_node = function.switch_cases.items[switch_stmt.cases.start + case_index];
                    if (case_node.is_default) {
                        try self.write_indent();
                        try self.write("default:\n");
                    } else {
                        var selector_index: usize = 0;
                        while (selector_index < case_node.selectors.items.len) : (selector_index += 1) {
                            try self.write_indent();
                            try self.write("case ");
                            try self.emit_expr(function, case_node.selectors.items[selector_index]);
                            try self.write(":\n");
                        }
                    }
                    self.indent += 4;
                    try self.emit_stmt(function, case_node.body);
                    try self.write_indent();
                    try self.write("break;\n");
                    self.indent -= 4;
                }
                self.indent -= 4;
                try self.write_indent();
                try self.write("}\n");
            },
            .break_ => {
                try self.write_indent();
                try self.write("break;\n");
            },
            .continue_ => {
                try self.write_indent();
                try self.write("continue;\n");
            },
            .discard_ => {
                try self.write_indent();
                try self.write("discard;\n");
            },
        }
    }

    fn emit_expr(self: *Emitter, function: ir.Function, expr_id: ir.ExprId) EmitError!void {
        const expr = function.exprs.items[expr_id];
        switch (expr.data) {
            .bool_lit => |value| try self.write(if (value) "true" else "false"),
            .int_lit => |value| try self.write_u64(value),
            .float_lit => |value| try self.write_float(value),
            .param_ref => |index| try self.write(function.params.items[index].name),
            .local_ref => |index| try self.write(function.locals.items[index].name),
            .global_ref => |index| try self.write(self.module.globals.items[index].name),
            .load => |inner| try self.emit_expr(function, inner),
            .unary => |unary| {
                try self.write("(");
                try self.write(unary_op_text(unary.op));
                try self.emit_expr(function, unary.operand);
                try self.write(")");
            },
            .binary => |binary| {
                try self.write("(");
                try self.emit_expr(function, binary.lhs);
                try self.write(" ");
                try self.write(binary_op_text(binary.op));
                try self.write(" ");
                try self.emit_expr(function, binary.rhs);
                try self.write(")");
            },
            .call => |call| try self.emit_call(function, call),
            .construct => |construct| {
                try self.emit_type_only(construct.ty);
                try self.write("(");
                try self.emit_expr_list(function, construct.args);
                try self.write(")");
            },
            .member => |member| {
                try self.emit_expr(function, member.base);
                try self.write(".");
                try self.write(member.field_name);
            },
            .index => |index| {
                try self.emit_expr(function, index.base);
                try self.write("[");
                try self.emit_expr(function, index.index);
                try self.write("]");
            },
        }
    }

    fn emit_call(self: *Emitter, function: ir.Function, call: anytype) EmitError!void {
        if (call.kind == .builtin) {
            if (std.mem.eql(u8, call.name, "workgroupBarrier")) {
                try self.write("GroupMemoryBarrierWithGroupSync()");
                return;
            }
            if (std.mem.eql(u8, call.name, "storageBarrier")) {
                try self.write("AllMemoryBarrierWithGroupSync()");
                return;
            }
        }
        try self.write(call.name);
        try self.write("(");
        try self.emit_expr_list(function, call.args);
        try self.write(")");
    }

    fn emit_expr_list(self: *Emitter, function: ir.Function, range: ir.Range) EmitError!void {
        var i: u32 = 0;
        while (i < range.len) : (i += 1) {
            if (i > 0) try self.write(", ");
            try self.emit_expr(function, function.expr_args.items[range.start + i]);
        }
    }

    fn emit_constant(self: *Emitter, constant: ir.ConstantValue, ty: ir.TypeId) EmitError!void {
        _ = ty;
        switch (constant) {
            .bool => |value| try self.write(if (value) "true" else "false"),
            .int => |value| try self.write_u64(value),
            .float => |value| try self.write_float(value),
        }
    }

    fn emit_typed_name(self: *Emitter, ty: ir.TypeId, name: []const u8) EmitError!void {
        switch (self.module.types.get(ty)) {
            .array => |arr| {
                try self.emit_type_only(arr.elem);
                try self.write(" ");
                try self.write(name);
                if (arr.len) |len| {
                    try self.write("[");
                    try self.write_u32(len);
                    try self.write("]");
                } else {
                    return error.InvalidIr;
                }
            },
            else => {
                try self.emit_type_only(ty);
                try self.write(" ");
                try self.write(name);
            },
        }
    }

    fn emit_type_only(self: *Emitter, ty: ir.TypeId) EmitError!void {
        switch (self.module.types.get(ty)) {
            .scalar => |scalar| try self.write(switch (scalar) {
                .void => "void",
                .bool => "bool",
                .i32, .abstract_int => "int",
                .u32 => "uint",
                .f32, .abstract_float => "float",
                .f16 => "half",
            }),
            .vector => |vec| {
                const prefix = switch (self.module.types.get(vec.elem)) {
                    .scalar => |scalar| switch (scalar) {
                        .bool => "bool",
                        .i32, .abstract_int => "int",
                        .u32 => "uint",
                        .f32, .abstract_float => "float",
                        .f16 => "half",
                        else => return error.InvalidIr,
                    },
                    else => return error.InvalidIr,
                };
                try self.write(prefix);
                try self.write_u32(vec.len);
            },
            .matrix => |mat| {
                const prefix = switch (self.module.types.get(mat.elem)) {
                    .scalar => |scalar| switch (scalar) {
                        .f32, .abstract_float => "float",
                        .f16 => "half",
                        else => return error.InvalidIr,
                    },
                    else => return error.InvalidIr,
                };
                try self.write(prefix);
                try self.write_u32(mat.columns);
                try self.write("x");
                try self.write_u32(mat.rows);
            },
            .array => return error.InvalidIr,
            .atomic => |inner| switch (self.module.types.get(inner)) {
                .scalar => |scalar| switch (scalar) {
                    .u32 => try self.write("uint"),
                    .i32, .abstract_int => try self.write("int"),
                    else => return error.InvalidIr,
                },
                else => return error.InvalidIr,
            },
            .struct_ => |struct_id| try self.write(self.module.structs.items[struct_id].name),
            .sampler => try self.write("SamplerState"),
            .texture_2d => |sample_ty| {
                try self.write("Texture2D<");
                try self.write(texture_component(sample_ty));
                try self.write("4>");
            },
            .ref => |ref_ty| try self.emit_type_only(ref_ty.elem),
        }
    }

    fn write(self: *Emitter, text: []const u8) EmitError!void {
        if (self.pos + text.len > self.buf.len) return error.OutputTooLarge;
        @memcpy(self.buf[self.pos .. self.pos + text.len], text);
        self.pos += text.len;
    }

    fn write_indent(self: *Emitter) EmitError!void {
        var i: usize = 0;
        while (i < self.indent) : (i += 1) try self.write(" ");
    }

    fn write_u32(self: *Emitter, value: u32) EmitError!void {
        var buf: [32]u8 = undefined;
        const text = std.fmt.bufPrint(&buf, "{}", .{value}) catch return error.OutputTooLarge;
        try self.write(text);
    }

    fn write_u64(self: *Emitter, value: u64) EmitError!void {
        var buf: [32]u8 = undefined;
        const text = std.fmt.bufPrint(&buf, "{}", .{value}) catch return error.OutputTooLarge;
        try self.write(text);
    }

    fn write_float(self: *Emitter, value: f64) EmitError!void {
        var buf: [64]u8 = undefined;
        const text = std.fmt.bufPrint(&buf, "{d}", .{value}) catch return error.OutputTooLarge;
        try self.write(text);
    }
};

fn unary_op_text(op: ir.UnaryOp) []const u8 {
    return switch (op) {
        .neg => "-",
        .not => "!",
        .bit_not => "~",
    };
}

fn binary_op_text(op: ir.BinaryOp) []const u8 {
    return switch (op) {
        .add => "+",
        .sub => "-",
        .mul => "*",
        .div => "/",
        .rem => "%",
        .bit_and => "&",
        .bit_or => "|",
        .bit_xor => "^",
        .shift_left => "<<",
        .shift_right => ">>",
        .equal => "==",
        .not_equal => "!=",
        .less => "<",
        .less_equal => "<=",
        .greater => ">",
        .greater_equal => ">=",
        .logical_and => "&&",
        .logical_or => "||",
    };
}

fn assign_op_text(op: ir.AssignOp) []const u8 {
    return switch (op) {
        .assign => "=",
        .add => "+=",
        .sub => "-=",
        .mul => "*=",
        .div => "/=",
        .rem => "%=",
        .bit_and => "&=",
        .bit_or => "|=",
        .bit_xor => "^=",
    };
}

fn hlsl_builtin_name(builtin: ir.Builtin) []const u8 {
    return switch (builtin) {
        .global_invocation_id => "SV_DispatchThreadID",
        .local_invocation_id => "SV_GroupThreadID",
        .local_invocation_index => "SV_GroupIndex",
        .workgroup_id => "SV_GroupID",
        .num_workgroups => "SV_GroupID",
        else => "UNSUPPORTED_BUILTIN",
    };
}

fn texture_component(sample_ty: ir.TypeId) []const u8 {
    _ = sample_ty;
    return "float";
}
