const std = @import("std");
const ast_mod = @import("ast.zig");
const Ast = ast_mod.Ast;
const Node = ast_mod.Node;
const NodeTag = ast_mod.NodeTag;
const NULL_NODE = ast_mod.NULL_NODE;

pub const EmitError = error{
    OutputTooLarge,
    InvalidAst,
};

pub const MAX_OUTPUT: usize = 256 * 1024;

pub fn emit(tree: *const Ast, out: []u8) EmitError!usize {
    var emitter = Emitter{
        .tree = tree,
        .buf = out,
        .pos = 0,
    };
    try emitter.emit_root();
    return emitter.pos;
}

const Stage = enum {
    none,
    compute,
};

const Builtin = enum {
    none,
    global_invocation_id,
    local_invocation_id,
    local_invocation_index,
    workgroup_id,
    num_workgroups,
};

const PackedSpan = struct {
    start: u32,
    len: u32,
};

const Emitter = struct {
    tree: *const Ast,
    buf: []u8,
    pos: usize,
    saw_compute_entry: bool = false,

    fn emit_root(self: *Emitter) EmitError!void {
        try self.write("// Generated by doe_wgsl/emit_hlsl.zig\n");
        try self.write("uint doe_atomicLoad(inout uint value) { uint result; InterlockedOr(value, 0u, result); return result; }\n");
        try self.write("void doe_atomicStore(inout uint value, uint next) { uint ignored; InterlockedExchange(value, next, ignored); }\n");

        const root = self.tree.nodes.items[0];
        const decl_start = root.data.lhs;
        const decl_count = root.data.rhs;

        var i: u32 = 0;
        while (i < decl_count) : (i += 1) {
            const decl_idx = self.tree.extra_data.items[decl_start + i];
            const node = self.tree.nodes.items[decl_idx];
            switch (node.tag) {
                .enable_directive, .diagnostic_directive => {},
                .alias_decl => try self.emit_alias_decl(node),
                .struct_decl => try self.emit_struct_decl(node),
                .global_var => try self.emit_global_var(node),
                .override_decl => try self.emit_override_decl(node),
                .const_decl => try self.emit_const_decl(node),
                else => {},
            }
        }

        i = 0;
        while (i < decl_count) : (i += 1) {
            const decl_idx = self.tree.extra_data.items[decl_start + i];
            const node = self.tree.nodes.items[decl_idx];
            if (node.tag == .fn_decl) try self.emit_fn_decl(node);
        }

        if (!self.saw_compute_entry) return error.InvalidAst;
    }

    fn emit_alias_decl(self: *Emitter, node: Node) EmitError!void {
        const name = self.token_str(node.main_token + 1);
        try self.write("\ntypedef ");
        try self.emit_type_expr(node.data.lhs);
        try self.write(" ");
        try self.write(name);
        try self.write(";\n");
    }

    fn emit_struct_decl(self: *Emitter, node: Node) EmitError!void {
        const raw_rhs = node.data.rhs;
        const member_start = raw_rhs & 0xFFFF;
        const member_count = raw_rhs >> 16;

        try self.write("\nstruct ");
        try self.write(self.token_str(node.data.lhs));
        try self.write(" {\n");

        var i: u32 = 0;
        while (i < member_count) : (i += 1) {
            const member_idx = self.tree.extra_data.items[member_start + i];
            const member = self.tree.nodes.items[member_idx];
            try self.emit_indent(1);
            try self.emit_decl(member.data.lhs, self.token_str(member.main_token));
            try self.write(";\n");
        }

        try self.write("};\n");
    }

    fn emit_global_var(self: *Emitter, node: Node) EmitError!void {
        const extra = self.tree.extra_data.items;
        const extra_start = node.data.rhs;
        const name = self.token_str(extra[extra_start + 0]);
        const addr_space = if (extra[extra_start + 1] != 0) self.token_str(extra[extra_start + 1]) else "";
        const access_mode = if (extra[extra_start + 2] != 0) self.token_str(extra[extra_start + 2]) else "";
        const initializer = extra[extra_start + 3];
        const attrs_start = extra[extra_start + 4];
        const attrs_len = extra[extra_start + 5];
        const binding = try self.find_group_binding(attrs_start, attrs_len);

        if (std.mem.eql(u8, addr_space, "workgroup")) {
            try self.write("\ngroupshared ");
            try self.emit_decl(node.data.lhs, name);
            try self.write(";\n");
            return;
        }

        if (std.mem.eql(u8, addr_space, "private")) {
            try self.write("\nstatic ");
            try self.emit_decl(node.data.lhs, name);
            if (initializer != NULL_NODE) {
                try self.write(" = ");
                try self.emit_expr(initializer);
            }
            try self.write(";\n");
            return;
        }

        if (std.mem.eql(u8, addr_space, "storage")) {
            if (binding == null) return error.InvalidAst;
            const elem_type = self.array_element_type(node.data.lhs) orelse return error.InvalidAst;
            try self.write("\n");
            if (std.mem.eql(u8, access_mode, "read_write")) {
                try self.write("RWStructuredBuffer<");
                try self.emit_type_expr(elem_type);
                try self.write("> ");
                try self.write(name);
                try self.emit_register("u", binding.?.binding, binding.?.group);
                try self.write(";\n");
            } else {
                try self.write("StructuredBuffer<");
                try self.emit_type_expr(elem_type);
                try self.write("> ");
                try self.write(name);
                try self.emit_register("t", binding.?.binding, binding.?.group);
                try self.write(";\n");
            }
            return;
        }

        if (std.mem.eql(u8, addr_space, "uniform")) {
            if (binding == null) return error.InvalidAst;
            try self.write("\ncbuffer doe_uniform_");
            try self.write(self.token_str(extra[extra_start + 0]));
            try self.emit_register("b", binding.?.binding, binding.?.group);
            try self.write(" {\n");
            try self.emit_indent(1);
            try self.emit_decl(node.data.lhs, name);
            try self.write(";\n};\n");
            return;
        }

        if (self.is_texture_type(node.data.lhs)) {
            if (binding == null) return error.InvalidAst;
            try self.write("\nTexture2D<float4> ");
            try self.write(name);
            try self.emit_register("t", binding.?.binding, binding.?.group);
            try self.write(";\n");
            return;
        }

        if (self.is_sampler_type(node.data.lhs)) {
            if (binding == null) return error.InvalidAst;
            try self.write("\nSamplerState ");
            try self.write(name);
            try self.emit_register("s", binding.?.binding, binding.?.group);
            try self.write(";\n");
            return;
        }

        return error.InvalidAst;
    }

    fn emit_override_decl(self: *Emitter, node: Node) EmitError!void {
        const name = self.token_str(node.main_token + 1);
        if (node.data.lhs == NULL_NODE) return error.InvalidAst;
        try self.write("\nstatic const ");
        try self.emit_decl(node.data.lhs, name);
        if (node.data.rhs != NULL_NODE) {
            try self.write(" = ");
            try self.emit_expr(node.data.rhs);
        }
        try self.write(";\n");
    }

    fn emit_const_decl(self: *Emitter, node: Node) EmitError!void {
        const name = self.token_str(node.main_token + 1);
        if (node.data.lhs == NULL_NODE) return error.InvalidAst;
        try self.write("\nstatic const ");
        try self.emit_decl(node.data.lhs, name);
        if (node.data.rhs != NULL_NODE) {
            try self.write(" = ");
            try self.emit_expr(node.data.rhs);
        }
        try self.write(";\n");
    }

    fn emit_fn_decl(self: *Emitter, node: Node) EmitError!void {
        const extra = self.tree.extra_data.items;
        const extra_start = node.data.lhs;
        const name = self.token_str(extra[extra_start + 0]);
        const params_start = extra[extra_start + 1];
        const params_len = extra[extra_start + 2];
        const return_type = extra[extra_start + 3];
        const attrs_start = extra[extra_start + 4];
        const attrs_len = extra[extra_start + 5];
        const stage = self.detect_stage(attrs_start, attrs_len);

        try self.write("\n");

        if (stage == .compute) {
            self.saw_compute_entry = true;
            const workgroup_attr = self.find_attr(attrs_start, attrs_len, "workgroup_size") orelse return error.InvalidAst;
            const span = decode_packed_span(workgroup_attr.data.rhs);
            if (span.len == 0) return error.InvalidAst;
            try self.write("[numthreads(");
            try self.emit_expr(self.tree.extra_data.items[span.start + 0]);
            try self.write(", ");
            if (span.len > 1) {
                try self.emit_expr(self.tree.extra_data.items[span.start + 1]);
            } else {
                try self.write("1");
            }
            try self.write(", ");
            if (span.len > 2) {
                try self.emit_expr(self.tree.extra_data.items[span.start + 2]);
            } else {
                try self.write("1");
            }
            try self.write(")]\n");
            try self.write("void ");
            try self.write(name);
            try self.write("(");
            var p: u32 = 0;
            while (p < params_len) : (p += 1) {
                if (p > 0) try self.write(", ");
                const param_extra_start = self.tree.extra_data.items[params_start + p];
                try self.emit_entry_param(param_extra_start);
            }
            try self.write(")\n");
            try self.emit_block_node(node.data.rhs, 0);
            return;
        }

        if (return_type != NULL_NODE) {
            try self.emit_type_expr(return_type);
        } else {
            try self.write("void");
        }
        try self.write(" ");
        try self.write(name);
        try self.write("(");
        var p: u32 = 0;
        while (p < params_len) : (p += 1) {
            if (p > 0) try self.write(", ");
            const param_extra_start = self.tree.extra_data.items[params_start + p];
            try self.emit_helper_param(param_extra_start);
        }
        try self.write(")\n");
        try self.emit_block_node(node.data.rhs, 0);
    }

    fn emit_helper_param(self: *Emitter, extra_start: u32) EmitError!void {
        const extra = self.tree.extra_data.items;
        const name = self.token_str(extra[extra_start + 0]);
        const type_node = extra[extra_start + 1];
        const attrs_len = extra[extra_start + 3];
        if (attrs_len != 0) return error.InvalidAst;
        try self.emit_decl(type_node, name);
    }

    fn emit_entry_param(self: *Emitter, extra_start: u32) EmitError!void {
        const extra = self.tree.extra_data.items;
        const name = self.token_str(extra[extra_start + 0]);
        const attrs_start = extra[extra_start + 2];
        const attrs_len = extra[extra_start + 3];
        const builtin = self.find_builtin(attrs_start, attrs_len);
        switch (builtin) {
            .global_invocation_id => try self.write_fmt("uint3 {s} : SV_DispatchThreadID", .{name}),
            .local_invocation_id => try self.write_fmt("uint3 {s} : SV_GroupThreadID", .{name}),
            .local_invocation_index => try self.write_fmt("uint {s} : SV_GroupIndex", .{name}),
            .workgroup_id => try self.write_fmt("uint3 {s} : SV_GroupID", .{name}),
            .num_workgroups, .none => return error.InvalidAst,
        }
    }

    fn emit_block_node(self: *Emitter, node_idx: u32, indent: u32) EmitError!void {
        const node = self.tree.nodes.items[node_idx];
        if (node.tag != .block) return error.InvalidAst;
        try self.emit_indent(indent);
        try self.write("{\n");
        var i: u32 = 0;
        while (i < node.data.rhs) : (i += 1) {
            const stmt_idx = self.tree.extra_data.items[node.data.lhs + i];
            try self.emit_statement(stmt_idx, indent + 1);
        }
        try self.emit_indent(indent);
        try self.write("}\n");
    }

    fn emit_statement(self: *Emitter, node_idx: u32, indent: u32) EmitError!void {
        const node = self.tree.nodes.items[node_idx];
        switch (node.tag) {
            .block => try self.emit_block_node(node_idx, indent),
            .var_stmt => try self.emit_local_binding(node, indent, false),
            .let_stmt, .const_stmt => try self.emit_local_binding(node, indent, true),
            .return_stmt => try self.emit_return_stmt(node, indent),
            .if_stmt => try self.emit_if_stmt(node, indent),
            .for_stmt => try self.emit_for_stmt(node, indent),
            .while_stmt => try self.emit_while_stmt(node, indent),
            .loop_stmt => try self.emit_loop_stmt(node, indent),
            .break_stmt => try self.emit_break_stmt(node, indent),
            .continue_stmt => try self.emit_continue_stmt(indent),
            .continuing_stmt => return error.InvalidAst,
            .switch_stmt, .switch_case => return error.InvalidAst,
            .discard_stmt => return error.InvalidAst,
            .expr_stmt => try self.emit_expr_stmt(node, indent),
            .assign_stmt => try self.emit_assign_stmt(node, indent),
            else => return error.InvalidAst,
        }
    }

    fn emit_local_binding(self: *Emitter, node: Node, indent: u32, is_const: bool) EmitError!void {
        if (node.data.lhs == NULL_NODE) return error.InvalidAst;
        try self.emit_indent(indent);
        if (is_const) try self.write("const ");
        try self.emit_decl(node.data.lhs, self.token_str(node.main_token + 1));
        if (node.data.rhs != NULL_NODE) {
            try self.write(" = ");
            try self.emit_expr(node.data.rhs);
        }
        try self.write(";\n");
    }

    fn emit_return_stmt(self: *Emitter, node: Node, indent: u32) EmitError!void {
        try self.emit_indent(indent);
        try self.write("return");
        if (node.data.lhs != NULL_NODE) {
            try self.write(" ");
            try self.emit_expr(node.data.lhs);
        }
        try self.write(";\n");
    }

    fn emit_if_stmt(self: *Emitter, node: Node, indent: u32) EmitError!void {
        try self.emit_indent(indent);
        try self.write("if (");
        try self.emit_expr(node.data.lhs);
        try self.write(")\n");
        try self.emit_block_node(node.data.rhs, indent);
    }

    fn emit_for_stmt(self: *Emitter, node: Node, indent: u32) EmitError!void {
        const extra_start = node.data.lhs;
        const init_idx = self.tree.extra_data.items[extra_start + 0];
        const cond_idx = self.tree.extra_data.items[extra_start + 1];
        const update_idx = self.tree.extra_data.items[extra_start + 2];

        try self.emit_indent(indent);
        try self.write("for (");
        if (init_idx != NULL_NODE) try self.emit_for_clause(init_idx);
        try self.write("; ");
        if (cond_idx != NULL_NODE) try self.emit_expr(cond_idx);
        try self.write("; ");
        if (update_idx != NULL_NODE) try self.emit_for_clause(update_idx);
        try self.write(")\n");
        try self.emit_block_node(node.data.rhs, indent);
    }

    fn emit_while_stmt(self: *Emitter, node: Node, indent: u32) EmitError!void {
        try self.emit_indent(indent);
        try self.write("while (");
        try self.emit_expr(node.data.lhs);
        try self.write(")\n");
        try self.emit_block_node(node.data.rhs, indent);
    }

    fn emit_loop_stmt(self: *Emitter, node: Node, indent: u32) EmitError!void {
        try self.emit_indent(indent);
        try self.write("for (;;)\n");
        try self.emit_block_node(node.data.lhs, indent);
    }

    fn emit_break_stmt(self: *Emitter, node: Node, indent: u32) EmitError!void {
        if (node.data.lhs != NULL_NODE) return error.InvalidAst;
        try self.emit_indent(indent);
        try self.write("break;\n");
    }

    fn emit_continue_stmt(self: *Emitter, indent: u32) EmitError!void {
        try self.emit_indent(indent);
        try self.write("continue;\n");
    }

    fn emit_expr_stmt(self: *Emitter, node: Node, indent: u32) EmitError!void {
        try self.emit_indent(indent);
        try self.emit_expr(node.data.lhs);
        try self.write(";\n");
    }

    fn emit_assign_stmt(self: *Emitter, node: Node, indent: u32) EmitError!void {
        try self.emit_indent(indent);
        try self.emit_assignment(node);
        try self.write(";\n");
    }

    fn emit_for_clause(self: *Emitter, node_idx: u32) EmitError!void {
        const node = self.tree.nodes.items[node_idx];
        switch (node.tag) {
            .var_stmt => {
                if (node.data.lhs == NULL_NODE) return error.InvalidAst;
                try self.emit_decl(node.data.lhs, self.token_str(node.main_token + 1));
                if (node.data.rhs != NULL_NODE) {
                    try self.write(" = ");
                    try self.emit_expr(node.data.rhs);
                }
            },
            .let_stmt, .const_stmt => {
                if (node.data.lhs == NULL_NODE) return error.InvalidAst;
                try self.write("const ");
                try self.emit_decl(node.data.lhs, self.token_str(node.main_token + 1));
                if (node.data.rhs != NULL_NODE) {
                    try self.write(" = ");
                    try self.emit_expr(node.data.rhs);
                }
            },
            .assign_stmt => try self.emit_assignment(node),
            .expr_stmt => try self.emit_expr(node.data.lhs),
            else => return error.InvalidAst,
        }
    }

    fn emit_assignment(self: *Emitter, node: Node) EmitError!void {
        try self.emit_expr(node.data.lhs);
        try self.write(" ");
        try self.write(self.token_str(node.main_token));
        try self.write(" ");
        try self.emit_expr(node.data.rhs);
    }

    fn emit_expr(self: *Emitter, node_idx: u32) EmitError!void {
        const node = self.tree.nodes.items[node_idx];
        switch (node.tag) {
            .ident_expr, .int_literal, .float_literal, .bool_literal => try self.write(self.token_str(node.main_token)),
            .binary_expr => {
                try self.write("(");
                try self.emit_expr(node.data.lhs);
                try self.write(" ");
                try self.write(self.token_str(node.main_token));
                try self.write(" ");
                try self.emit_expr(node.data.rhs);
                try self.write(")");
            },
            .unary_expr => {
                const op = self.token_str(node.main_token);
                if (std.mem.eql(u8, op, "&") or std.mem.eql(u8, op, "*")) return error.InvalidAst;
                try self.write("(");
                try self.write(op);
                try self.emit_expr(node.data.lhs);
                try self.write(")");
            },
            .call_expr => try self.emit_call_expr(node),
            .member_expr => {
                try self.emit_expr(node.data.lhs);
                try self.write(".");
                try self.write(self.token_str(node.data.rhs));
            },
            .index_expr => {
                try self.emit_expr(node.data.lhs);
                try self.write("[");
                try self.emit_expr(node.data.rhs);
                try self.write("]");
            },
            else => return error.InvalidAst,
        }
    }

    fn emit_call_expr(self: *Emitter, node: Node) EmitError!void {
        const name = self.token_str(node.main_token);
        if (std.mem.eql(u8, name, "workgroupBarrier")) {
            try self.write("GroupMemoryBarrierWithGroupSync()");
            return;
        }
        if (std.mem.eql(u8, name, "atomicLoad")) {
            if (node.data.rhs != 1) return error.InvalidAst;
            try self.write("doe_atomicLoad(");
            try self.emit_atomic_target(self.tree.extra_data.items[node.data.lhs]);
            try self.write(")");
            return;
        }
        if (std.mem.eql(u8, name, "atomicStore")) {
            if (node.data.rhs != 2) return error.InvalidAst;
            try self.write("doe_atomicStore(");
            try self.emit_atomic_target(self.tree.extra_data.items[node.data.lhs + 0]);
            try self.write(", ");
            try self.emit_expr(self.tree.extra_data.items[node.data.lhs + 1]);
            try self.write(")");
            return;
        }

        try self.emit_call_name(name);
        try self.write("(");
        var i: u32 = 0;
        while (i < node.data.rhs) : (i += 1) {
            if (i > 0) try self.write(", ");
            try self.emit_expr(self.tree.extra_data.items[node.data.lhs + i]);
        }
        try self.write(")");
    }

    fn emit_call_name(self: *Emitter, name: []const u8) EmitError!void {
        if (map_scalar_or_vector_or_matrix(name)) |mapped| {
            try self.write(mapped);
            return;
        }
        try self.write(name);
    }

    fn emit_atomic_target(self: *Emitter, node_idx: u32) EmitError!void {
        const node = self.tree.nodes.items[node_idx];
        if (node.tag == .unary_expr and std.mem.eql(u8, self.token_str(node.main_token), "&")) {
            try self.emit_expr(node.data.lhs);
            return;
        }
        try self.emit_expr(node_idx);
    }

    fn emit_decl(self: *Emitter, type_node_idx: u32, name: []const u8) EmitError!void {
        const node = self.tree.nodes.items[type_node_idx];
        if (node.tag == .type_parameterized and std.mem.eql(u8, self.token_str(node.main_token), "array")) {
            const elem_type = self.param_node(node, 0) orelse return error.InvalidAst;
            const count_expr = self.param_node(node, 1) orelse return error.InvalidAst;
            try self.emit_type_expr(elem_type);
            try self.write(" ");
            try self.write(name);
            try self.write("[");
            try self.emit_expr(count_expr);
            try self.write("]");
            return;
        }

        try self.emit_type_expr(type_node_idx);
        try self.write(" ");
        try self.write(name);
    }

    fn emit_type_expr(self: *Emitter, type_node_idx: u32) EmitError!void {
        const node = self.tree.nodes.items[type_node_idx];
        switch (node.tag) {
            .type_name, .type_vec_shorthand, .type_mat_shorthand => {
                if (map_scalar_or_vector_or_matrix(self.token_str(node.main_token))) |mapped| {
                    try self.write(mapped);
                    return;
                }
                try self.write(self.token_str(node.main_token));
            },
            .type_parameterized => {
                const base = self.token_str(node.main_token);
                if (std.mem.eql(u8, base, "atomic")) {
                    const inner = self.param_node(node, 0) orelse return error.InvalidAst;
                    try self.emit_type_expr(inner);
                    return;
                }
                if (std.mem.eql(u8, base, "texture_2d")) {
                    try self.write("Texture2D<float4>");
                    return;
                }
                if (std.mem.eql(u8, base, "array")) return error.InvalidAst;
                if (std.mem.eql(u8, base, "sampler")) {
                    try self.write("SamplerState");
                    return;
                }
                if (std.mem.eql(u8, base, "vec2") or std.mem.eql(u8, base, "vec3") or std.mem.eql(u8, base, "vec4")) {
                    const scalar = self.scalar_type_for_generic(self.param_node(node, 0) orelse return error.InvalidAst) orelse return error.InvalidAst;
                    try self.write_fmt("{s}{s}", .{ scalar, base[3..] });
                    return;
                }
                if (std.mem.eql(u8, base, "mat2x2") or std.mem.eql(u8, base, "mat2x3") or std.mem.eql(u8, base, "mat2x4") or std.mem.eql(u8, base, "mat3x2") or std.mem.eql(u8, base, "mat3x3") or std.mem.eql(u8, base, "mat3x4") or std.mem.eql(u8, base, "mat4x2") or std.mem.eql(u8, base, "mat4x3") or std.mem.eql(u8, base, "mat4x4")) {
                    const scalar = self.scalar_type_for_generic(self.param_node(node, 0) orelse return error.InvalidAst) orelse return error.InvalidAst;
                    try self.write_fmt("{s}{s}", .{ scalar, base[3..] });
                    return;
                }
                return error.InvalidAst;
            },
            else => return error.InvalidAst,
        }
    }

    fn scalar_type_for_generic(self: *Emitter, node_idx: u32) ?[]const u8 {
        const node = self.tree.nodes.items[node_idx];
        if (node.tag != .type_name and node.tag != .type_vec_shorthand and node.tag != .type_mat_shorthand) return null;
        const text = self.tree.tokenSlice(node.main_token);
        if (std.mem.eql(u8, text, "f16")) return "half";
        if (std.mem.eql(u8, text, "f32")) return "float";
        if (std.mem.eql(u8, text, "i32")) return "int";
        if (std.mem.eql(u8, text, "u32")) return "uint";
        if (std.mem.eql(u8, text, "bool")) return "bool";
        return null;
    }

    fn array_element_type(self: *Emitter, type_node_idx: u32) ?u32 {
        const node = self.tree.nodes.items[type_node_idx];
        if (node.tag != .type_parameterized) return null;
        if (!std.mem.eql(u8, self.token_str(node.main_token), "array")) return null;
        return self.param_node(node, 0);
    }

    fn is_texture_type(self: *Emitter, type_node_idx: u32) bool {
        const node = self.tree.nodes.items[type_node_idx];
        return node.tag == .type_parameterized and std.mem.eql(u8, self.token_str(node.main_token), "texture_2d");
    }

    fn is_sampler_type(self: *Emitter, type_node_idx: u32) bool {
        const node = self.tree.nodes.items[type_node_idx];
        return node.tag == .type_name and std.mem.eql(u8, self.token_str(node.main_token), "sampler");
    }

    fn param_node(self: *Emitter, node: Node, index: u32) ?u32 {
        if (index >= node.data.rhs) return null;
        return self.tree.extra_data.items[node.data.lhs + index];
    }

    fn detect_stage(self: *Emitter, attrs_start: u32, attrs_len: u32) Stage {
        if (self.find_attr(attrs_start, attrs_len, "compute") != null) return .compute;
        return .none;
    }

    fn find_builtin(self: *Emitter, attrs_start: u32, attrs_len: u32) Builtin {
        const attr = self.find_attr(attrs_start, attrs_len, "builtin") orelse return .none;
        const span = decode_packed_span(attr.data.rhs);
        if (span.len != 1) return .none;
        const arg_idx = self.tree.extra_data.items[span.start];
        const arg = self.tree.nodes.items[arg_idx];
        if (arg.tag != .ident_expr) return .none;
        const name = self.token_str(arg.main_token);
        if (std.mem.eql(u8, name, "global_invocation_id")) return .global_invocation_id;
        if (std.mem.eql(u8, name, "local_invocation_id")) return .local_invocation_id;
        if (std.mem.eql(u8, name, "local_invocation_index")) return .local_invocation_index;
        if (std.mem.eql(u8, name, "workgroup_id")) return .workgroup_id;
        if (std.mem.eql(u8, name, "num_workgroups")) return .num_workgroups;
        return .none;
    }

    fn find_group_binding(self: *Emitter, attrs_start: u32, attrs_len: u32) EmitError!?struct { group: u32, binding: u32 } {
        const group_attr = self.find_attr(attrs_start, attrs_len, "group") orelse return null;
        const binding_attr = self.find_attr(attrs_start, attrs_len, "binding") orelse return null;
        const group = self.parse_attr_uint(group_attr) orelse return error.InvalidAst;
        const binding = self.parse_attr_uint(binding_attr) orelse return error.InvalidAst;
        return .{ .group = group, .binding = binding };
    }

    fn find_attr(self: *Emitter, attrs_start: u32, attrs_len: u32, name: []const u8) ?Node {
        var i: u32 = 0;
        while (i < attrs_len) : (i += 1) {
            const attr_idx = self.tree.extra_data.items[attrs_start + i];
            const attr = self.tree.nodes.items[attr_idx];
            if (attr.tag != .attribute) continue;
            if (std.mem.eql(u8, self.token_str(attr.data.lhs), name)) return attr;
        }
        return null;
    }

    fn parse_attr_uint(self: *Emitter, attr: Node) ?u32 {
        const span = decode_packed_span(attr.data.rhs);
        if (span.len != 1) return null;
        const arg_idx = self.tree.extra_data.items[span.start];
        const arg = self.tree.nodes.items[arg_idx];
        if (arg.tag != .int_literal) return null;
        return parse_uint_suffix(self.token_str(arg.main_token));
    }

    fn emit_register(self: *Emitter, reg_class: []const u8, binding: u32, group: u32) EmitError!void {
        try self.write_fmt(" : register({s}{}, space{})", .{ reg_class, binding, group });
    }

    fn emit_indent(self: *Emitter, depth: u32) EmitError!void {
        var i: u32 = 0;
        while (i < depth) : (i += 1) try self.write("    ");
    }

    fn token_str(self: *Emitter, token_idx: u32) []const u8 {
        return self.tree.tokenSlice(token_idx);
    }

    fn write(self: *Emitter, bytes: []const u8) EmitError!void {
        if (self.pos + bytes.len > self.buf.len) return error.OutputTooLarge;
        @memcpy(self.buf[self.pos .. self.pos + bytes.len], bytes);
        self.pos += bytes.len;
    }

    fn write_fmt(self: *Emitter, comptime fmt: []const u8, args: anytype) EmitError!void {
        var tmp: [256]u8 = undefined;
        const rendered = std.fmt.bufPrint(&tmp, fmt, args) catch return error.InvalidAst;
        try self.write(rendered);
    }
};

fn decode_packed_span(raw: u32) PackedSpan {
    return .{
        .start = raw & 0xFFFF,
        .len = raw >> 16,
    };
}

fn parse_uint_suffix(text: []const u8) ?u32 {
    var end = text.len;
    while (end > 0 and (text[end - 1] == 'u' or text[end - 1] == 'i')) : (end -= 1) {}
    return std.fmt.parseInt(u32, text[0..end], 10) catch null;
}

fn map_scalar_or_vector_or_matrix(name: []const u8) ?[]const u8 {
    if (std.mem.eql(u8, name, "bool")) return "bool";
    if (std.mem.eql(u8, name, "f16")) return "half";
    if (std.mem.eql(u8, name, "f32")) return "float";
    if (std.mem.eql(u8, name, "i32")) return "int";
    if (std.mem.eql(u8, name, "u32")) return "uint";

    if (std.mem.eql(u8, name, "vec2f")) return "float2";
    if (std.mem.eql(u8, name, "vec3f")) return "float3";
    if (std.mem.eql(u8, name, "vec4f")) return "float4";
    if (std.mem.eql(u8, name, "vec2h")) return "half2";
    if (std.mem.eql(u8, name, "vec3h")) return "half3";
    if (std.mem.eql(u8, name, "vec4h")) return "half4";
    if (std.mem.eql(u8, name, "vec2i")) return "int2";
    if (std.mem.eql(u8, name, "vec3i")) return "int3";
    if (std.mem.eql(u8, name, "vec4i")) return "int4";
    if (std.mem.eql(u8, name, "vec2u")) return "uint2";
    if (std.mem.eql(u8, name, "vec3u")) return "uint3";
    if (std.mem.eql(u8, name, "vec4u")) return "uint4";

    if (std.mem.eql(u8, name, "mat2x2f")) return "float2x2";
    if (std.mem.eql(u8, name, "mat2x3")) return "float2x3";
    if (std.mem.eql(u8, name, "mat2x4")) return "float2x4";
    if (std.mem.eql(u8, name, "mat3x2")) return "float3x2";
    if (std.mem.eql(u8, name, "mat3x3f")) return "float3x3";
    if (std.mem.eql(u8, name, "mat3x4")) return "float3x4";
    if (std.mem.eql(u8, name, "mat4x2")) return "float4x2";
    if (std.mem.eql(u8, name, "mat4x3")) return "float4x3";
    if (std.mem.eql(u8, name, "mat4x4f")) return "float4x4";
    if (std.mem.eql(u8, name, "mat2x2h")) return "half2x2";
    if (std.mem.eql(u8, name, "mat3x3h")) return "half3x3";
    if (std.mem.eql(u8, name, "mat4x4h")) return "half4x4";

    return null;
}
