// hlsl_subsystem_test.zig -- HLSL/DXIL subsystem tests for Doe WebGPU.
//
// Tests the HLSL code generation pipeline: translateToHlsl output correctness,
// register mapping, type mapping, compute shader specifics, texture operations,
// num_workgroups dispatch contract, DXIL toolchain config, and error handling.

const std = @import("std");
const mod = @import("../../src/doe_wgsl/mod.zig");
const dispatch_contract = @import("../../src/doe_wgsl/hlsl_dispatch_contract.zig");
const maps = @import("../../src/doe_wgsl/emit_hlsl_maps.zig");
const emit_dxil = @import("../../src/doe_wgsl/emit_dxil.zig");

const testing = std.testing;
const allocator = testing.allocator;

const MAX_HLSL = mod.MAX_HLSL_OUTPUT;
const translateToHlsl = mod.translateToHlsl;
const analyzeToIr = mod.analyzeToIr;

fn contains(haystack: []const u8, needle: []const u8) bool {
    return std.mem.indexOf(u8, haystack, needle) != null;
}

// ============================================================
// 1. HLSL output correctness -- structural verification
// ============================================================

test "hlsl output: preamble contains generated comment and helpers" {
    const source =
        \\@group(0) @binding(0) var<storage, read_write> buf: array<u32>;
        \\@compute @workgroup_size(1)
        \\fn main(@builtin(global_invocation_id) gid: vec3u) {
        \\    buf[gid.x] = gid.x;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "// Generated by doe_wgsl/emit_hlsl.zig"));
    // Atomic helpers always present
    try testing.expect(contains(hlsl, "uint doe_atomicLoad(inout uint value)"));
    try testing.expect(contains(hlsl, "void doe_atomicStore(inout uint value, uint next)"));
    try testing.expect(contains(hlsl, "uint doe_atomicAdd(inout uint v, uint a)"));
    try testing.expect(contains(hlsl, "uint doe_atomicSub(inout uint v, uint a)"));
    try testing.expect(contains(hlsl, "uint doe_atomicExchange(inout uint v, uint a)"));
    // Signed int variants
    try testing.expect(contains(hlsl, "int doe_atomicLoad(inout int value)"));
    try testing.expect(contains(hlsl, "void doe_atomicStore(inout int value, int next)"));
    // Pack/unpack helpers
    try testing.expect(contains(hlsl, "doe_unpack2x16float"));
    try testing.expect(contains(hlsl, "doe_pack2x16float"));
    try testing.expect(contains(hlsl, "doe_unpack4x8unorm"));
    try testing.expect(contains(hlsl, "doe_pack4x8snorm"));
}

// ============================================================
// 2. Register mapping -- cbuffer/UAV/SRV/sampler registers
// ============================================================

test "hlsl register: uniform maps to cbuffer b-register" {
    const source =
        \\struct Params { x: f32, y: f32 }
        \\@group(0) @binding(3) var<uniform> params: Params;
        \\@compute @workgroup_size(1)
        \\fn main(@builtin(global_invocation_id) gid: vec3u) {
        \\    let v = params.x;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "register(b3, space0)"));
    try testing.expect(contains(hlsl, "cbuffer doe_uniform_params"));
}

test "hlsl register: storage read_write maps to u-register, read maps to t-register" {
    const source =
        \\@group(0) @binding(0) var<storage, read_write> rw_data: array<f32>;
        \\@group(0) @binding(1) var<storage, read> ro_data: array<f32>;
        \\@compute @workgroup_size(1)
        \\fn main(@builtin(global_invocation_id) gid: vec3u) {
        \\    rw_data[0] = ro_data[0];
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "RWStructuredBuffer"));
    try testing.expect(contains(hlsl, "register(u0, space0)"));
    try testing.expect(contains(hlsl, "StructuredBuffer<"));
    try testing.expect(contains(hlsl, "register(t1, space0)"));
}

test "hlsl register: sampler maps to s-register, texture to t-register" {
    const source =
        \\@group(0) @binding(0) var tex: texture_2d<f32>;
        \\@group(0) @binding(1) var samp: sampler;
        \\@fragment
        \\fn main(@location(0) uv: vec2f) -> @location(0) vec4f {
        \\    return textureSample(tex, samp, uv);
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "SamplerState samp : register(s1, space0)"));
    try testing.expect(contains(hlsl, "Texture2D<float4> tex : register(t0, space0)"));
}

test "hlsl register: group maps to HLSL space" {
    const source =
        \\@group(2) @binding(5) var<uniform> params: vec4f;
        \\@compute @workgroup_size(1)
        \\fn main(@builtin(global_invocation_id) gid: vec3u) {
        \\    let v = params.x;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "register(b5, space2)"));
}

// ============================================================
// 3. Type mapping -- WGSL types to HLSL types
// ============================================================

test "hlsl type: scalar and vector types map correctly" {
    const source =
        \\struct Types {
        \\    a: f32, b: u32, c: i32, d: bool,
        \\    e: vec2f, f: vec3u, g: vec4i, h: vec2<bool>,
        \\}
        \\@group(0) @binding(0) var<uniform> t: Types;
        \\@compute @workgroup_size(1)
        \\fn main(@builtin(global_invocation_id) gid: vec3u) {
        \\    let v = t.a;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    // Scalars
    try testing.expect(contains(hlsl, "float a;"));
    try testing.expect(contains(hlsl, "uint b;"));
    try testing.expect(contains(hlsl, "int c;"));
    try testing.expect(contains(hlsl, "bool d;"));
    // Vectors
    try testing.expect(contains(hlsl, "float2 e;"));
    try testing.expect(contains(hlsl, "uint3 f;"));
    try testing.expect(contains(hlsl, "int4 g;"));
    try testing.expect(contains(hlsl, "bool2 h;"));
}

test "hlsl type: matrix and array types map correctly" {
    const source =
        \\struct TypesMA {
        \\    a: mat4x4f,
        \\    b: mat2x2<f32>,
        \\    c: mat3x3<f32>,
        \\    d: array<f32, 8>,
        \\}
        \\@group(0) @binding(0) var<uniform> t: TypesMA;
        \\@compute @workgroup_size(1)
        \\fn main(@builtin(global_invocation_id) gid: vec3u) {
        \\    let v = t.a;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "float4x4 a;"));
    try testing.expect(contains(hlsl, "float2x2 b;"));
    try testing.expect(contains(hlsl, "float3x3 c;"));
    try testing.expect(contains(hlsl, "float d[8]"));
}

// ============================================================
// 4. Compute shader specifics
// ============================================================

test "hlsl compute: numthreads 3D and builtin semantics" {
    const source =
        \\@group(0) @binding(0) var<storage, read_write> buf: array<u32>;
        \\@compute @workgroup_size(16, 8, 4)
        \\fn main(@builtin(global_invocation_id) gid: vec3u) {
        \\    buf[gid.x] = gid.x;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "[numthreads(16, 8, 4)]"));
    try testing.expect(contains(hlsl, "SV_DispatchThreadID"));
    try testing.expect(contains(hlsl, "uint3 gid"));
}

test "hlsl compute: all compute builtins map to correct HLSL semantics" {
    const source =
        \\@group(0) @binding(0) var<storage, read_write> buf: array<u32>;
        \\@compute @workgroup_size(64)
        \\fn main(
        \\    @builtin(local_invocation_id) lid: vec3u,
        \\    @builtin(local_invocation_index) idx: u32,
        \\    @builtin(workgroup_id) wgid: vec3u,
        \\) {
        \\    buf[idx] = lid.x + wgid.x;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "SV_GroupThreadID"));
    try testing.expect(contains(hlsl, "SV_GroupIndex"));
    try testing.expect(contains(hlsl, "SV_GroupID"));
}

test "hlsl compute: groupshared for workgroup variable" {
    const source =
        \\var<workgroup> shared: array<f32, 256>;
        \\@compute @workgroup_size(256)
        \\fn main(@builtin(local_invocation_index) idx: u32) {
        \\    shared[idx] = f32(idx);
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "groupshared"));
    try testing.expect(contains(hlsl, "float shared[256]"));
}

// ============================================================
// 5. Texture operations
// ============================================================

test "hlsl texture: Load, Sample, SampleLevel, SampleCmp, SampleCmpLevelZero" {
    // textureLoad -> .Load
    {
        const source =
            \\@group(0) @binding(0) var tex: texture_2d<f32>;
            \\@group(0) @binding(1) var<storage, read_write> out_buf: array<f32>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    let c = textureLoad(tex, vec2u(gid.x, 0u), 0);
            \\    out_buf[gid.x] = c.x;
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        const hlsl = out[0..len];
        try testing.expect(contains(hlsl, ".Load("));
        try testing.expect(contains(hlsl, "Texture2D<float4>"));
    }
    // textureSample -> .Sample
    {
        const source =
            \\@group(0) @binding(0) var tex: texture_2d<f32>;
            \\@group(0) @binding(1) var samp: sampler;
            \\@fragment
            \\fn main(@location(0) uv: vec2f) -> @location(0) vec4f {
            \\    return textureSample(tex, samp, uv);
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        try testing.expect(contains(out[0..len], ".Sample("));
    }
    // textureSampleLevel -> .SampleLevel
    {
        const source =
            \\@group(0) @binding(0) var tex: texture_2d<f32>;
            \\@group(0) @binding(1) var samp: sampler;
            \\@group(0) @binding(2) var<storage, read_write> out_buf: array<f32>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    let c = textureSampleLevel(tex, samp, vec2f(0.5, 0.5), 0.0);
            \\    out_buf[0] = c.x;
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        try testing.expect(contains(out[0..len], ".SampleLevel("));
    }
    // textureSampleCompare -> .SampleCmp
    {
        const source =
            \\@group(0) @binding(0) var tex: texture_depth_2d;
            \\@group(0) @binding(1) var samp: sampler_comparison;
            \\@fragment
            \\fn main(@location(0) uv: vec2f) -> @location(0) vec4f {
            \\    let d = textureSampleCompare(tex, samp, uv, 0.5);
            \\    return vec4f(d, d, d, 1.0);
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        try testing.expect(contains(out[0..len], ".SampleCmp("));
    }
    // textureSampleCompareLevel -> .SampleCmpLevelZero
    {
        const source =
            \\@group(0) @binding(0) var tex: texture_depth_2d;
            \\@group(0) @binding(1) var samp: sampler_comparison;
            \\@group(0) @binding(2) var<storage, read_write> out_buf: array<f32>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    let d = textureSampleCompareLevel(tex, samp, vec2f(0.5, 0.5), 0.5);
            \\    out_buf[0] = d;
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        try testing.expect(contains(out[0..len], ".SampleCmpLevelZero("));
    }
}

test "hlsl texture: dimensions helpers and store" {
    // textureDimensions -> helper with GetDimensions
    {
        const source =
            \\@group(0) @binding(0) var tex: texture_2d<f32>;
            \\@group(0) @binding(1) var<storage, read_write> out_buf: array<u32>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    let dims = textureDimensions(tex, 0);
            \\    out_buf[0] = dims.x;
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        const hlsl = out[0..len];
        try testing.expect(contains(hlsl, "doe_textureDimensions_tex"));
        try testing.expect(contains(hlsl, "GetDimensions("));
    }
    // textureStore -> RWTexture2D with u-register
    {
        const source =
            \\@group(0) @binding(0) var tex: texture_storage_2d<rgba8unorm, write>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    textureStore(tex, vec2u(gid.x, 0u), vec4f(1.0, 0.0, 0.0, 1.0));
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        const hlsl = out[0..len];
        try testing.expect(contains(hlsl, "RWTexture2D<float4>"));
        try testing.expect(contains(hlsl, "register(u0, space0)"));
    }
}

test "hlsl texture: Texture2DArray, Texture3D, TextureCube type mapping" {
    // Texture2DArray
    {
        const source =
            \\@group(0) @binding(0) var tex: texture_2d_array<f32>;
            \\@group(0) @binding(1) var<storage, read_write> out_buf: array<u32>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    out_buf[0] = textureNumLayers(tex);
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        const hlsl = out[0..len];
        try testing.expect(contains(hlsl, "Texture2DArray<float4>"));
        try testing.expect(contains(hlsl, "doe_textureNumLayers_tex()"));
    }
    // Texture3D
    {
        const source =
            \\@group(0) @binding(0) var tex: texture_3d<f32>;
            \\@group(0) @binding(1) var samp: sampler;
            \\@group(0) @binding(2) var<storage, read_write> out_buf: array<f32>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    let c = textureSampleLevel(tex, samp, vec3f(0.5, 0.5, 0.5), 0.0);
            \\    out_buf[0] = c.x;
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        try testing.expect(contains(out[0..len], "Texture3D<float4>"));
    }
    // TextureCube
    {
        const source =
            \\@group(0) @binding(0) var tex: texture_cube<f32>;
            \\@group(0) @binding(1) var samp: sampler;
            \\@group(0) @binding(2) var<storage, read_write> out_buf: array<f32>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    let c = textureSampleLevel(tex, samp, vec3f(1.0, 0.0, 0.0), 0.0);
            \\    out_buf[0] = c.x;
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        try testing.expect(contains(out[0..len], "TextureCube<float4>"));
    }
}

// ============================================================
// 6. num_workgroups dispatch contract
// ============================================================

test "hlsl dispatch contract: cbuffer emitted when num_workgroups used" {
    const source =
        \\@group(0) @binding(0) var<storage, read_write> buf: array<u32>;
        \\@compute @workgroup_size(1)
        \\fn main(@builtin(num_workgroups) nwg: vec3u) {
        \\    buf[0] = nwg.x;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "cbuffer DoeDispatchInfo"));
    try testing.expect(contains(hlsl, "register(b0, space7)"));
    try testing.expect(contains(hlsl, "uint3 doe_num_workgroups;"));
    try testing.expect(contains(hlsl, "uint _doe_num_workgroups_pad;"));
    try testing.expect(contains(hlsl, "const uint3 nwg = doe_num_workgroups;"));
}

test "hlsl dispatch contract: cbuffer NOT emitted without num_workgroups" {
    const source =
        \\@group(0) @binding(0) var<storage, read_write> buf: array<u32>;
        \\@compute @workgroup_size(64)
        \\fn main(@builtin(global_invocation_id) gid: vec3u) {
        \\    buf[gid.x] = gid.x;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(!contains(hlsl, "DoeDispatchInfo"));
    try testing.expect(!contains(hlsl, "doe_num_workgroups"));
}

test "hlsl dispatch contract: constants match expected values" {
    try testing.expectEqual(@as(u32, 0), dispatch_contract.DISPATCH_INFO_REGISTER_SLOT);
    try testing.expectEqual(@as(u32, 7), dispatch_contract.DISPATCH_INFO_REGISTER_SPACE);
    try testing.expectEqual(@as(u32, 0), dispatch_contract.DISPATCH_INFO_ROOT_PARAMETER_INDEX);
    try testing.expectEqual(@as(u64, 256), dispatch_contract.DISPATCH_INFO_BUFFER_BYTES);
    try testing.expectEqualStrings("DoeDispatchInfo", dispatch_contract.DISPATCH_INFO_CBUFFER_NAME);
    try testing.expectEqualStrings("doe_num_workgroups", dispatch_contract.DISPATCH_INFO_FIELD_NAME);
    try testing.expectEqualStrings("_doe_num_workgroups_pad", dispatch_contract.DISPATCH_INFO_PAD_FIELD_NAME);
}

// ============================================================
// 7. HLSL map correctness
// ============================================================

test "hlsl maps: builtin name mapping covers all expected builtins" {
    try testing.expectEqualStrings("SV_Position", maps.hlsl_builtin_name(.position));
    try testing.expectEqualStrings("SV_Depth", maps.hlsl_builtin_name(.frag_depth));
    try testing.expectEqualStrings("SV_IsFrontFace", maps.hlsl_builtin_name(.front_facing));
    try testing.expectEqualStrings("SV_DispatchThreadID", maps.hlsl_builtin_name(.global_invocation_id));
    try testing.expectEqualStrings("SV_GroupThreadID", maps.hlsl_builtin_name(.local_invocation_id));
    try testing.expectEqualStrings("SV_GroupIndex", maps.hlsl_builtin_name(.local_invocation_index));
    try testing.expectEqualStrings("SV_GroupID", maps.hlsl_builtin_name(.workgroup_id));
    try testing.expectEqualStrings("SV_SampleIndex", maps.hlsl_builtin_name(.sample_index));
    try testing.expectEqualStrings("SV_Coverage", maps.hlsl_builtin_name(.sample_mask));
    try testing.expectEqualStrings("SV_VertexID", maps.hlsl_builtin_name(.vertex_index));
    try testing.expectEqualStrings("SV_InstanceID", maps.hlsl_builtin_name(.instance_index));
    try testing.expectEqualStrings("SV_ClipDistance", maps.hlsl_builtin_name(.clip_distances));
    try testing.expectEqualStrings("SV_PrimitiveID", maps.hlsl_builtin_name(.primitive_index));
    // num_workgroups has no semantic
    try testing.expect(!maps.hlsl_builtin_has_semantic(.num_workgroups));
}

test "hlsl maps: subgroup intrinsics and renamed builtins" {
    // Subgroup builtins are intrinsic calls, not parameter semantics
    try testing.expectEqualStrings("WaveGetLaneCount()", maps.hlsl_intrinsic_builtin(.subgroup_size).?);
    try testing.expectEqualStrings("WaveGetLaneIndex()", maps.hlsl_intrinsic_builtin(.subgroup_invocation_id).?);
    try testing.expect(maps.hlsl_intrinsic_builtin(.position) == null);
    // Renamed builtins
    try testing.expectEqualStrings("frac", maps.hlsl_renamed_builtin("fract").?);
    try testing.expectEqualStrings("rsqrt", maps.hlsl_renamed_builtin("inverseSqrt").?);
    try testing.expectEqualStrings("lerp", maps.hlsl_renamed_builtin("mix").?);
    try testing.expectEqualStrings("countbits", maps.hlsl_renamed_builtin("countOneBits").?);
    try testing.expectEqualStrings("reversebits", maps.hlsl_renamed_builtin("reverseBits").?);
    try testing.expectEqualStrings("firstbithigh", maps.hlsl_renamed_builtin("firstLeadingBit").?);
    try testing.expectEqualStrings("firstbitlow", maps.hlsl_renamed_builtin("firstTrailingBit").?);
    try testing.expect(maps.hlsl_renamed_builtin("unknownFunc") == null);
    // Passthrough builtins
    try testing.expect(maps.hlsl_builtin_passthrough("abs"));
    try testing.expect(maps.hlsl_builtin_passthrough("sin"));
    try testing.expect(maps.hlsl_builtin_passthrough("dot"));
    try testing.expect(maps.hlsl_builtin_passthrough("normalize"));
    try testing.expect(!maps.hlsl_builtin_passthrough("fract"));
    try testing.expect(!maps.hlsl_builtin_passthrough("mix"));
}

// ============================================================
// 8. Stage-specific emission (vertex/fragment)
// ============================================================

test "hlsl stage: vertex shader emits impl wrapper and semantics" {
    const source =
        \\struct VertInput {
        \\    @location(0) pos: vec3f,
        \\    @location(1) color: vec4f,
        \\}
        \\struct VertOutput {
        \\    @builtin(position) clip_pos: vec4f,
        \\    @location(0) color: vec4f,
        \\}
        \\@vertex
        \\fn vs_main(input: VertInput) -> VertOutput {
        \\    var out: VertOutput;
        \\    out.clip_pos = vec4f(input.pos, 1.0);
        \\    out.color = input.color;
        \\    return out;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "vs_main_impl("));
    try testing.expect(contains(hlsl, "vs_main_stage_out"));
    try testing.expect(contains(hlsl, "TEXCOORD0"));
    try testing.expect(contains(hlsl, "TEXCOORD1"));
    try testing.expect(contains(hlsl, "SV_Position"));
    try testing.expect(contains(hlsl, "VertInput input;"));
}

test "hlsl stage: fragment shader outputs SV_Target" {
    const source =
        \\@fragment
        \\fn fs_main(@location(0) uv: vec2f) -> @location(0) vec4f {
        \\    return vec4f(uv, 0.0, 1.0);
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "SV_Target0"));
    try testing.expect(contains(hlsl, "TEXCOORD0"));
    try testing.expect(contains(hlsl, "fs_main_stage_out"));
    try testing.expect(contains(hlsl, "fs_main_impl("));
}

// ============================================================
// 9. DXIL module -- testable without DXC
// ============================================================

test "dxil: lower extracts entry point from IR" {
    const source =
        \\@group(0) @binding(0) var<storage, read_write> buf: array<u32>;
        \\@compute @workgroup_size(32, 2, 1)
        \\fn my_kernel(@builtin(global_invocation_id) gid: vec3u) {
        \\    buf[gid.x] = gid.x;
        \\}
    ;
    var module_ir = try analyzeToIr(allocator, source);
    defer module_ir.deinit();
    const lowered = try emit_dxil.lower(&module_ir);
    try testing.expectEqual(emit_dxil.Stage.compute, lowered.entry_point.stage);
    try testing.expectEqualStrings("my_kernel", lowered.entry_point.name);
    try testing.expectEqual(@as(u32, 32), lowered.entry_point.workgroup_size[0]);
    try testing.expectEqual(@as(u32, 2), lowered.entry_point.workgroup_size[1]);
    try testing.expectEqual(@as(u32, 1), lowered.entry_point.workgroup_size[2]);
    try testing.expectEqual(@as(u8, 6), lowered.shader_model.major);
    try testing.expectEqual(@as(u8, 0), lowered.shader_model.minor);
}

test "dxil: lower vertex and fragment stages" {
    {
        const source =
            \\@vertex
            \\fn vs_main(@builtin(vertex_index) vid: u32) -> @builtin(position) vec4f {
            \\    return vec4f(f32(vid), 0.0, 0.0, 1.0);
            \\}
        ;
        var module_ir = try analyzeToIr(allocator, source);
        defer module_ir.deinit();
        const lowered = try emit_dxil.lower(&module_ir);
        try testing.expectEqual(emit_dxil.Stage.vertex, lowered.entry_point.stage);
    }
    {
        const source =
            \\@fragment
            \\fn fs_main(@location(0) uv: vec2f) -> @location(0) vec4f {
            \\    return vec4f(uv, 0.0, 1.0);
            \\}
        ;
        var module_ir = try analyzeToIr(allocator, source);
        defer module_ir.deinit();
        const lowered = try emit_dxil.lower(&module_ir);
        try testing.expectEqual(emit_dxil.Stage.fragment, lowered.entry_point.stage);
    }
}

test "dxil: toolchain config rejects empty executable" {
    var out_buf: [256]u8 = undefined;
    const source =
        \\@group(0) @binding(0) var<storage, read_write> buf: array<u32>;
        \\@compute @workgroup_size(1)
        \\fn main(@builtin(global_invocation_id) gid: vec3u) {
        \\    buf[0] = 0u;
        \\}
    ;
    var module_ir = try analyzeToIr(allocator, source);
    defer module_ir.deinit();
    const config = emit_dxil.ToolchainConfig{
        .executable = "",
        .discovery = .explicit_config,
    };
    const result = emit_dxil.emitWithToolchainConfig(&module_ir, &out_buf, config);
    try testing.expectError(error.ShaderToolchainUnavailable, result);
    const msg = emit_dxil.lastErrorMessage();
    try testing.expect(msg.len > 0);
    try testing.expect(contains(msg, emit_dxil.DXC_ENV_VAR));
}

test "dxil: MAX_OUTPUT constant is defined" {
    try testing.expectEqual(@as(usize, 256 * 1024), emit_dxil.MAX_OUTPUT);
}

// ============================================================
// 10. Error handling
// ============================================================

test "hlsl error: invalid syntax and undeclared identifier" {
    var out: [MAX_HLSL]u8 = undefined;
    // Invalid syntax
    {
        const result = translateToHlsl(allocator, "fn main( { bad }", &out);
        try testing.expect(result == error.UnexpectedToken or
            result == error.InvalidWgsl or
            result == error.InvalidType);
    }
    // Undeclared identifier
    {
        const source =
            \\@compute @workgroup_size(1)
            \\fn main() {
            \\    let x = undefined_var;
            \\}
        ;
        try testing.expectError(error.UnknownIdentifier, translateToHlsl(allocator, source, &out));
    }
}

test "hlsl error: output buffer too small returns OutputTooLarge" {
    const source =
        \\@group(0) @binding(0) var<storage, read_write> buf: array<u32>;
        \\@compute @workgroup_size(1)
        \\fn main(@builtin(global_invocation_id) gid: vec3u) {
        \\    buf[gid.x] = gid.x;
        \\}
    ;
    var tiny_out: [16]u8 = undefined;
    try testing.expectError(error.OutputTooLarge, translateToHlsl(allocator, source, &tiny_out));
}

// ============================================================
// 11. Builtin function mapping
// ============================================================

test "hlsl builtin: select ternary and barrier mapping" {
    // select -> ternary
    {
        const source =
            \\@group(0) @binding(0) var<storage, read_write> buf: array<f32>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    buf[0] = select(1.0, 2.0, true);
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        try testing.expect(contains(out[0..len], "?"));
    }
    // workgroupBarrier
    {
        const source =
            \\var<workgroup> shared: array<f32, 64>;
            \\@group(0) @binding(0) var<storage, read_write> buf: array<f32>;
            \\@compute @workgroup_size(64)
            \\fn main(@builtin(local_invocation_index) idx: u32) {
            \\    shared[idx] = buf[idx];
            \\    workgroupBarrier();
            \\    buf[idx] = shared[63u - idx];
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        try testing.expect(contains(out[0..len], "GroupMemoryBarrierWithGroupSync()"));
    }
}

test "hlsl builtin: fract->frac and mix->lerp" {
    {
        const source =
            \\@group(0) @binding(0) var<storage, read_write> buf: array<f32>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    buf[gid.x] = fract(buf[gid.x]);
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        try testing.expect(contains(out[0..len], "frac("));
        try testing.expect(!contains(out[0..len], "fract("));
    }
    {
        const source =
            \\@group(0) @binding(0) var<storage, read_write> buf: array<f32>;
            \\@compute @workgroup_size(1)
            \\fn main(@builtin(global_invocation_id) gid: vec3u) {
            \\    buf[0] = mix(0.0, 1.0, 0.5);
            \\}
        ;
        var out: [MAX_HLSL]u8 = undefined;
        const len = try translateToHlsl(allocator, source, &out);
        try testing.expect(contains(out[0..len], "lerp("));
    }
}

// ============================================================
// 12. Interpolation modifiers
// ============================================================

test "hlsl interpolation: flat and linear modifiers" {
    const source =
        \\struct VsOut {
        \\    @builtin(position) pos: vec4f,
        \\    @location(0) @interpolate(flat) id: u32,
        \\    @location(1) @interpolate(linear) uv: vec2f,
        \\}
        \\@vertex
        \\fn vs_main(@builtin(vertex_index) vid: u32) -> VsOut {
        \\    var out: VsOut;
        \\    out.id = vid;
        \\    return out;
        \\}
    ;
    var out: [MAX_HLSL]u8 = undefined;
    const len = try translateToHlsl(allocator, source, &out);
    const hlsl = out[0..len];
    try testing.expect(contains(hlsl, "nointerpolation"));
    try testing.expect(contains(hlsl, "noperspective"));
}
