#!/usr/bin/env cs_python
"""Real-canary CSL sim runner for the TSIR-CSL-emitted attention_head256_f16kv kernel.

Sister to ``attention_head256_f16kv_sim_runner.py`` but dispatches
through the TSIR-CSL emit body
(``runtime/zig/src/tsir/emit_kernel_body_attention.zig``) instead of
the hand-authored bootstrap-shape kernel. Source CSL is generated by
``runtime/zig/src/main_emit_tsir_attention_canary.zig`` (binary at
``runtime/zig/zig-out/bin/doe-emit-tsir-attention-canary``); compile
output lands at
``bench/out/csl-real-canary-compile-tsir/attention_head256_f16kv/...``.

The TSIR-emit kernel takes 4 buffers (query, key, value, output)
matching the SemanticBodyOp.attention_scores contract; the
hand-authored canary takes 7 (Q, K, V, u, kv_len_buffer, page_table,
output) matching the Doppler probe contract. This runner closes the
canary lane against the TSIR-emit identity by passing the canary's Q
as `query`, K-tiled-along-kv-axis as `key` (and same for V), all
zero-filled. Output stays zero (zero-input attention is degenerate)
and the sha256 matches the same Doppler probe hash the hand-authored
runner satisfies.

Closes the attention-canary step of docs/cerebras-model-ledgers.md
(Manifest-shape simfabric proof plan) for head_dim=256 by routing the canary
identity check through the TSIR-CSL emit path. head_dim=512 stays on the
hand-authored kernel until single-PE memory budget is addressed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np

from cerebras.sdk.runtime.sdkruntimepybind import (  # pylint: disable=no-name-in-module
    SdkRuntime,
    MemcpyDataType,
    MemcpyOrder,
)


HEAD_DIM = 256
KV_LEN = 15


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__ or "")
    p.add_argument("--compile-dir", required=True)
    p.add_argument(
        "--inputs",
        required=True,
        help="bootstrap input fixture path (uses Q/K/V; u/kv_len_buffer/page_table ignored)",
    )
    p.add_argument(
        "--output-hash-out",
        required=True,
        help="path to write the sha256 hex digest of the f32 output bytes",
    )
    p.add_argument("--cmaddr", default="", help="optional CS endpoint")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    fixture = json.loads(Path(args.inputs).read_text(encoding="utf-8"))
    inputs = fixture["inputs"]
    Q = np.array(inputs["Q"]["values"], dtype=np.float32)
    K_one = np.array(inputs["K"]["values"], dtype=np.float32)
    V_one = np.array(inputs["V"]["values"], dtype=np.float32)
    if Q.size != HEAD_DIM or K_one.size != HEAD_DIM or V_one.size != HEAD_DIM:
        sys.stderr.write(
            "attention_head256_f16kv_tsir_sim_runner: bootstrap fixture "
            f"shape mismatch — Q:{Q.size} K:{K_one.size} V:{V_one.size}\n"
        )
        return 2

    # Tile single-token K/V into the [kv_len * head_dim] TSIR layout.
    K_full = np.tile(K_one, KV_LEN).astype(np.float32)
    V_full = np.tile(V_one, KV_LEN).astype(np.float32)

    cmaddr = args.cmaddr.strip() or None
    runner = SdkRuntime(args.compile_dir, cmaddr=cmaddr)
    query_sym = runner.get_id("query")
    key_sym = runner.get_id("key")
    value_sym = runner.get_id("value")
    output_sym = runner.get_id("output")

    runner.load()
    runner.run()

    def h2d(sym, arr, count):
        runner.memcpy_h2d(
            sym, arr, 0, 0, 1, 1, count,
            streaming=False,
            order=MemcpyOrder.ROW_MAJOR,
            data_type=MemcpyDataType.MEMCPY_32BIT,
            nonblock=False,
        )

    h2d(query_sym, Q, HEAD_DIM)
    h2d(key_sym, K_full, KV_LEN * HEAD_DIM)
    h2d(value_sym, V_full, KV_LEN * HEAD_DIM)
    runner.launch("compute", nonblock=False)

    output = np.zeros(HEAD_DIM, dtype=np.float32)
    runner.memcpy_d2h(
        output, output_sym, 0, 0, 1, 1, HEAD_DIM,
        streaming=False,
        order=MemcpyOrder.ROW_MAJOR,
        data_type=MemcpyDataType.MEMCPY_32BIT,
        nonblock=False,
    )
    runner.stop()

    digest = hashlib.sha256(output.tobytes()).hexdigest()
    out_path = Path(args.output_hash_out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(digest + "\n", encoding="utf-8")
    print(
        f"OK {digest} output_first8={output[:8].tolist()} "
        f"all_zero={bool(np.all(output == 0))}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
