#!/usr/bin/env cs_python
"""Real-canary CSL sim runner for the TSIR-CSL-emitted attention_head512_f16kv kernel.

Sister to ``attention_head512_f16kv_sim_runner.py`` (hand-authored
bootstrap-shape kernel that zeros the output and returns) and to
``attention_head256_f16kv_tsir_sim_runner.py`` (TSIR-CSL emit body at
head_dim=256, kv_len=15). This runner closes the head_dim=512 canary
lane through the TSIR-CSL emit body
(``runtime/zig/src/tsir/emit_kernel_body_attention.zig``).

Source CSL is generated by
``runtime/zig/src/main_emit_tsir_attention_canary.zig`` (binary at
``runtime/zig/zig-out/bin/doe-emit-tsir-attention-canary --head-dim 512
--out-dir <dir>``).

Single-PE memory budget: at head_dim=512, the f32 K and V buffers are
``kv_len * 512 * 4`` bytes each. The 48 KB SRAM ceiling caps single-PE
kv_len at ~7 once attn_scores / Q / output are accounted for. This
runner uses ``KV_LEN = 7`` (~28 KB K+V + ~4 KB Q+output ≈ 32 KB total)
to exercise the real two-pass-stable softmax with multiple KV slots —
the head_dim=256 canary uses kv_len=15 because its K+V at head_dim=256
fits in ~30 KB.

For zero inputs (the canary), the attention math degenerates to
all-zero output regardless of kv_len:

    dot[k]        = 0
    max_score     = 0 (after first scan)
    attn_scores[k]= exp(0 - 0) = 1.0
    sum_exp       = kv_len
    output[d]     = sum_k(V[k][d] * (1.0 / kv_len)) = 0

so ``sha256(output.tobytes()) ==
e5a00aa9991ac8a5ee3109844d84a55583bd20572ad3ffcd42792f3c36b183ad``,
matching the Doppler probe hash that the hand-authored canary
satisfies.

Multi-PE kv-axis distribution (allowing kv_len ≥ 15 at head_dim=512)
is a follow-up: requires a 2D PE-grid layout and cross-PE
max/sum reductions; the scope of this runner is closing the canary
identity through the TSIR emit body, not landing the full multi-PE
attention realization.

Usage (via runtime/zig/tools/cs_python_singularity.sh):

  cs_python_singularity.sh attention_head512_f16kv_tsir_sim_runner.py \\
    --compile-dir bench/out/csl-real-canary-compile-tsir-h512/attention_head512_f16kv \\
    --inputs bench/fixtures/tsir-bootstrap-inputs/attention_head512_f16kv.json \\
    --output-hash-out <path/to/attention_head512_f16kv.tsir-csl.hash>
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np

from cerebras.sdk.runtime.sdkruntimepybind import (  # pylint: disable=no-name-in-module
    SdkRuntime,
    MemcpyDataType,
    MemcpyOrder,
)


HEAD_DIM = 512
# Single-PE budget cap. K and V each take kv_len * head_dim * 4 bytes
# (f32). At head_dim=512, kv_len=7 means K=14 KB, V=14 KB; plus Q=2 KB,
# output=2 KB, attn_scores=28 B → ~32 KB total, well under the 48 KB
# SRAM ceiling. kv_len=8 would push K+V to 32 KB and total to ~36 KB
# (still fits); kv_len=15 (matching the head_dim=256 canary) requires
# multi-PE kv-axis distribution and is the attention-canary follow-up.
KV_LEN = 7


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__ or "")
    p.add_argument("--compile-dir", required=True)
    p.add_argument(
        "--inputs",
        required=True,
        help=(
            "bootstrap input fixture path (uses Q/K/V; "
            "u/kv_len_buffer/page_table ignored — the TSIR-emit body "
            "uses a fixed kv_len param fixed at compile time)"
        ),
    )
    p.add_argument(
        "--output-hash-out",
        required=True,
        help="path to write the sha256 hex digest of the f32 output bytes",
    )
    p.add_argument("--cmaddr", default="", help="optional CS endpoint")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    fixture = json.loads(Path(args.inputs).read_text(encoding="utf-8"))
    inputs = fixture["inputs"]
    Q = np.array(inputs["Q"]["values"], dtype=np.float32)
    K_one = np.array(inputs["K"]["values"], dtype=np.float32)
    V_one = np.array(inputs["V"]["values"], dtype=np.float32)
    if Q.size != HEAD_DIM or K_one.size != HEAD_DIM or V_one.size != HEAD_DIM:
        sys.stderr.write(
            "attention_head512_f16kv_tsir_sim_runner: bootstrap fixture "
            f"shape mismatch — Q:{Q.size} K:{K_one.size} V:{V_one.size}\n"
        )
        return 2

    # Tile single-token K/V into the [kv_len * head_dim] TSIR layout.
    K_full = np.tile(K_one, KV_LEN).astype(np.float32)
    V_full = np.tile(V_one, KV_LEN).astype(np.float32)

    cmaddr = args.cmaddr.strip() or None
    runner = SdkRuntime(args.compile_dir, cmaddr=cmaddr)
    query_sym = runner.get_id("query")
    key_sym = runner.get_id("key")
    value_sym = runner.get_id("value")
    output_sym = runner.get_id("output")

    runner.load()
    runner.run()

    def h2d(sym, arr, count):
        runner.memcpy_h2d(
            sym, arr, 0, 0, 1, 1, count,
            streaming=False,
            order=MemcpyOrder.ROW_MAJOR,
            data_type=MemcpyDataType.MEMCPY_32BIT,
            nonblock=False,
        )

    h2d(query_sym, Q, HEAD_DIM)
    h2d(key_sym, K_full, KV_LEN * HEAD_DIM)
    h2d(value_sym, V_full, KV_LEN * HEAD_DIM)
    runner.launch("compute", nonblock=False)

    output = np.zeros(HEAD_DIM, dtype=np.float32)
    runner.memcpy_d2h(
        output, output_sym, 0, 0, 1, 1, HEAD_DIM,
        streaming=False,
        order=MemcpyOrder.ROW_MAJOR,
        data_type=MemcpyDataType.MEMCPY_32BIT,
        nonblock=False,
    )
    runner.stop()

    digest = hashlib.sha256(output.tobytes()).hexdigest()
    out_path = Path(args.output_hash_out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(digest + "\n", encoding="utf-8")
    print(
        f"OK {digest} output_first8={output[:8].tolist()} "
        f"all_zero={bool(np.all(output == 0))}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
