"""Load implementation-family identities and render their documentation view."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import jsonschema

REPO_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_PATH = Path("config/implementation-peers.json")
SCHEMA_PATH = REGISTRY_PATH.with_suffix(".schema.json")
DOC_PATH = Path("docs/implementation-peers.md")


def load_peers(root: Path = REPO_ROOT) -> list[dict[str, Any]]:
    """Load strict peer records, rejecting ambiguous identities and bad links."""
    payload = json.loads((root / REGISTRY_PATH).read_text(encoding="utf-8"))
    schema = json.loads((root / SCHEMA_PATH).read_text(encoding="utf-8"))
    try:
        jsonschema.Draft202012Validator(schema).validate(payload)
    except jsonschema.ValidationError as exc:
        raise ValueError(f"{REGISTRY_PATH}: {exc.message}") from exc
    peers = payload["peers"]
    for key in ("id", "nativeProviderId"):
        values = [peer[key] for peer in peers]
        if len(set(values)) != len(values) or "doe" in values:
            raise ValueError(f"{REGISTRY_PATH}: duplicate or reserved {key}")
    for peer in peers:
        for path in peer["trackingPaths"] + peer["evidencePaths"]:
            target = (root / path).resolve()
            if not target.is_relative_to(root.resolve()) or not target.is_file():
                raise ValueError(f"{REGISTRY_PATH}: invalid local reference {path}")
    return peers


def native_providers(root: Path = REPO_ROOT) -> tuple[str, ...]:
    """Return declared identities; membership does not enable execution."""
    return ("doe", *(peer["nativeProviderId"] for peer in load_peers(root)))


def resolve_provider_sets(
    entries: list[dict[str, Any]], root: Path = REPO_ROOT,
) -> dict[str, tuple[str, ...]]:
    """Resolve cube provider references without changing comparison profiles."""
    result: dict[str, tuple[str, ...]] = {}
    for entry in entries:
        if entry["id"] in result:
            raise ValueError(f"duplicate provider set: {entry['id']}")
        if "sourceRegistryPath" in entry:
            if entry["sourceRegistryPath"] != REGISTRY_PATH.as_posix():
                raise ValueError("provider set must reference implementation peers")
            if "providers" in entry:
                raise ValueError("provider set cannot embed and reference providers")
            providers = native_providers(root)
        else:
            providers = tuple(entry["providers"])
        result[entry["id"]] = providers
    return result


def render_peers(peers: list[dict[str, Any]]) -> str:
    """Render the complete documentation projection from canonical records."""
    lines = [
        "# WebGPU implementation peers", "",
        "<!-- Generated by bench.tools.render_implementation_peers; do not edit. -->",
        "",
        "The canonical inventory is [implementation-peers.json]"
        "(../config/implementation-peers.json), validated by its",
        "[schema](../config/implementation-peers.schema.json).",
        "Implementation families, compiler identities, native provider IDs and",
        "tracking links are edited there. Registry order preserves provider order.",
        "",
        "Provider membership describes identity, not runnable support, conformance,",
        "or a performance ranking. [Compare profiles](benchmark-taxonomy.md) govern",
        "available execution; retained artifacts own exact revisions, library",
        "hashes, measurements and claim scope. Empty evidence links mean no evidence",
        "is indexed here, not proof that no historical experiment exists.",
        "[Ecosystem actor scores](ecosystem.md) remain a separate authority for",
        "adoption and relationships; package bindings are not new engine families.",
        "",
        "Regenerate with `python3 -m bench.tools.render_implementation_peers`.",
        "Use `--check` to detect drift; the blocking schema gate also checks this view.",
        "",
        "| Peer | Maintainers | WGSL compiler | Native provider ID |",
        "| --- | --- | --- | --- |",
    ]
    for peer in peers:
        compiler = peer["compiler"]
        lines.append(
            f"| [{peer['name']}]({peer['repositoryUrl']}) | {peer['maintainers']} "
            f"| [{compiler['name']}]({compiler['sourceUrl']}) "
            f"| `{peer['nativeProviderId']}` |"
        )
    for peer in peers:
        lines.extend(["", f"## {peer['name']}", "", peer["integrationNote"],
                      "", peer["trackingNote"], "", "Tracking:", ""])
        for path in peer["trackingPaths"]:
            lines.append(f"- [{path}](../{path})")
        lines.extend(["", "Evidence pointers:", ""])
        if not peer["evidencePaths"]:
            lines.append("No evidence indexed in this registry.")
        for path in peer["evidencePaths"]:
            lines.append(f"- [{path}](../{path})")
        lines.extend(["", "Upstream sources:", ""])
        for url in peer["upstreamSources"]:
            lines.append(f"- [{url}]({url})")
    return "\n".join(lines) + "\n"


def validate_peer_document(root: Path = REPO_ROOT) -> list[str]:
    """Return actionable registry or generated-document failures for the gate."""
    try:
        expected = render_peers(load_peers(root))
        if (root / DOC_PATH).read_text(encoding="utf-8") != expected:
            return [f"{DOC_PATH}: stale; run python3 -m "
                    "bench.tools.render_implementation_peers"]
    except (OSError, UnicodeError, ValueError) as exc:
        return [f"implementation peers: {exc}"]
    return []
