const vk = @import("vulkan_types.zig");

pub const VK_MAX_PHYSICAL_DEVICE_NAME_SIZE: usize = 256;
pub const VK_UUID_SIZE: usize = 16;
pub const VK_LUID_SIZE: usize = 8;

pub const VkFormatProperties = extern struct {
    linearTilingFeatures: vk.VkFlags,
    optimalTilingFeatures: vk.VkFlags,
    bufferFeatures: vk.VkFlags,
};

pub const VkPhysicalDeviceFeatures = extern struct {
    robustBufferAccess: vk.VkBool32,
    fullDrawIndexUint32: vk.VkBool32,
    imageCubeArray: vk.VkBool32,
    independentBlend: vk.VkBool32,
    geometryShader: vk.VkBool32,
    tessellationShader: vk.VkBool32,
    sampleRateShading: vk.VkBool32,
    dualSrcBlend: vk.VkBool32,
    logicOp: vk.VkBool32,
    multiDrawIndirect: vk.VkBool32,
    drawIndirectFirstInstance: vk.VkBool32,
    depthClamp: vk.VkBool32,
    depthBiasClamp: vk.VkBool32,
    fillModeNonSolid: vk.VkBool32,
    depthBounds: vk.VkBool32,
    wideLines: vk.VkBool32,
    largePoints: vk.VkBool32,
    alphaToOne: vk.VkBool32,
    multiViewport: vk.VkBool32,
    samplerAnisotropy: vk.VkBool32,
    textureCompressionETC2: vk.VkBool32,
    textureCompressionASTC_LDR: vk.VkBool32,
    textureCompressionBC: vk.VkBool32,
    occlusionQueryPrecise: vk.VkBool32,
    pipelineStatisticsQuery: vk.VkBool32,
    vertexPipelineStoresAndAtomics: vk.VkBool32,
    fragmentStoresAndAtomics: vk.VkBool32,
    shaderTessellationAndGeometryPointSize: vk.VkBool32,
    shaderImageGatherExtended: vk.VkBool32,
    shaderStorageImageExtendedFormats: vk.VkBool32,
    shaderStorageImageMultisample: vk.VkBool32,
    shaderStorageImageReadWithoutFormat: vk.VkBool32,
    shaderStorageImageWriteWithoutFormat: vk.VkBool32,
    shaderUniformBufferArrayDynamicIndexing: vk.VkBool32,
    shaderSampledImageArrayDynamicIndexing: vk.VkBool32,
    shaderStorageBufferArrayDynamicIndexing: vk.VkBool32,
    shaderStorageImageArrayDynamicIndexing: vk.VkBool32,
    shaderClipDistance: vk.VkBool32,
    shaderCullDistance: vk.VkBool32,
    shaderFloat64: vk.VkBool32,
    shaderInt64: vk.VkBool32,
    shaderInt16: vk.VkBool32,
    shaderResourceResidency: vk.VkBool32,
    shaderResourceMinLod: vk.VkBool32,
    sparseBinding: vk.VkBool32,
    sparseResidencyBuffer: vk.VkBool32,
    sparseResidencyImage2D: vk.VkBool32,
    sparseResidencyImage3D: vk.VkBool32,
    sparseResidency2Samples: vk.VkBool32,
    sparseResidency4Samples: vk.VkBool32,
    sparseResidency8Samples: vk.VkBool32,
    sparseResidency16Samples: vk.VkBool32,
    sparseResidencyAliased: vk.VkBool32,
    variableMultisampleRate: vk.VkBool32,
    inheritedQueries: vk.VkBool32,
};

pub const VkPhysicalDeviceFeatures2 = extern struct {
    sType: vk.VkStructureType,
    pNext: ?*anyopaque,
    features: VkPhysicalDeviceFeatures,
};

pub const VkPhysicalDevice16BitStorageFeatures = extern struct {
    sType: vk.VkStructureType,
    pNext: ?*anyopaque,
    storageBuffer16BitAccess: vk.VkBool32,
    uniformAndStorageBuffer16BitAccess: vk.VkBool32,
    storagePushConstant16: vk.VkBool32,
    storageInputOutput16: vk.VkBool32,
};

pub const VkPhysicalDeviceLimits = extern struct {
    maxImageDimension1D: u32,
    maxImageDimension2D: u32,
    maxImageDimension3D: u32,
    maxImageDimensionCube: u32,
    maxImageArrayLayers: u32,
    maxTexelBufferElements: u32,
    maxUniformBufferRange: u32,
    maxStorageBufferRange: u32,
    maxPushConstantsSize: u32,
    maxMemoryAllocationCount: u32,
    maxSamplerAllocationCount: u32,
    bufferImageGranularity: vk.VkDeviceSize,
    sparseAddressSpaceSize: vk.VkDeviceSize,
    maxBoundDescriptorSets: u32,
    maxPerStageDescriptorSamplers: u32,
    maxPerStageDescriptorUniformBuffers: u32,
    maxPerStageDescriptorStorageBuffers: u32,
    maxPerStageDescriptorSampledImages: u32,
    maxPerStageDescriptorStorageImages: u32,
    maxPerStageDescriptorInputAttachments: u32,
    maxPerStageResources: u32,
    maxDescriptorSetSamplers: u32,
    maxDescriptorSetUniformBuffers: u32,
    maxDescriptorSetUniformBuffersDynamic: u32,
    maxDescriptorSetStorageBuffers: u32,
    maxDescriptorSetStorageBuffersDynamic: u32,
    maxDescriptorSetSampledImages: u32,
    maxDescriptorSetStorageImages: u32,
    maxDescriptorSetInputAttachments: u32,
    maxVertexInputAttributes: u32,
    maxVertexInputBindings: u32,
    maxVertexInputAttributeOffset: u32,
    maxVertexInputBindingStride: u32,
    maxVertexOutputComponents: u32,
    maxTessellationGenerationLevel: u32,
    maxTessellationPatchSize: u32,
    maxTessellationControlPerVertexInputComponents: u32,
    maxTessellationControlPerVertexOutputComponents: u32,
    maxTessellationControlPerPatchOutputComponents: u32,
    maxTessellationControlTotalOutputComponents: u32,
    maxTessellationEvaluationInputComponents: u32,
    maxTessellationEvaluationOutputComponents: u32,
    maxGeometryShaderInvocations: u32,
    maxGeometryInputComponents: u32,
    maxGeometryOutputComponents: u32,
    maxGeometryOutputVertices: u32,
    maxGeometryTotalOutputComponents: u32,
    maxFragmentInputComponents: u32,
    maxFragmentOutputAttachments: u32,
    maxFragmentDualSrcAttachments: u32,
    maxFragmentCombinedOutputResources: u32,
    maxComputeSharedMemorySize: u32,
    maxComputeWorkGroupCount: [3]u32,
    maxComputeWorkGroupInvocations: u32,
    maxComputeWorkGroupSize: [3]u32,
    subPixelPrecisionBits: u32,
    subTexelPrecisionBits: u32,
    mipmapPrecisionBits: u32,
    maxDrawIndexedIndexValue: u32,
    maxDrawIndirectCount: u32,
    maxSamplerLodBias: f32,
    maxSamplerAnisotropy: f32,
    maxViewports: u32,
    maxViewportDimensions: [2]u32,
    viewportBoundsRange: [2]f32,
    viewportSubPixelBits: u32,
    minMemoryMapAlignment: usize,
    minTexelBufferOffsetAlignment: vk.VkDeviceSize,
    minUniformBufferOffsetAlignment: vk.VkDeviceSize,
    minStorageBufferOffsetAlignment: vk.VkDeviceSize,
    minTexelOffset: i32,
    maxTexelOffset: u32,
    minTexelGatherOffset: i32,
    maxTexelGatherOffset: u32,
    minInterpolationOffset: f32,
    maxInterpolationOffset: f32,
    subPixelInterpolationOffsetBits: u32,
    maxFramebufferWidth: u32,
    maxFramebufferHeight: u32,
    maxFramebufferLayers: u32,
    framebufferColorSampleCounts: vk.VkFlags,
    framebufferDepthSampleCounts: vk.VkFlags,
    framebufferStencilSampleCounts: vk.VkFlags,
    framebufferNoAttachmentsSampleCounts: vk.VkFlags,
    maxColorAttachments: u32,
    sampledImageColorSampleCounts: vk.VkFlags,
    sampledImageIntegerSampleCounts: vk.VkFlags,
    sampledImageDepthSampleCounts: vk.VkFlags,
    sampledImageStencilSampleCounts: vk.VkFlags,
    storageImageSampleCounts: vk.VkFlags,
    maxSampleMaskWords: u32,
    timestampComputeAndGraphics: vk.VkBool32,
    timestampPeriod: f32,
    maxClipDistances: u32,
    maxCullDistances: u32,
    maxCombinedClipAndCullDistances: u32,
    discreteQueuePriorities: u32,
    pointSizeRange: [2]f32,
    lineWidthRange: [2]f32,
    pointSizeGranularity: f32,
    lineWidthGranularity: f32,
    strictLines: vk.VkBool32,
    standardSampleLocations: vk.VkBool32,
    optimalBufferCopyOffsetAlignment: vk.VkDeviceSize,
    optimalBufferCopyRowPitchAlignment: vk.VkDeviceSize,
    nonCoherentAtomSize: vk.VkDeviceSize,
};

pub const VkPhysicalDeviceSparseProperties = extern struct {
    residencyStandard2DBlockShape: vk.VkBool32,
    residencyStandard2DMultisampleBlockShape: vk.VkBool32,
    residencyStandard3DBlockShape: vk.VkBool32,
    residencyAlignedMipSize: vk.VkBool32,
    residencyNonResidentStrict: vk.VkBool32,
};

pub const VkPhysicalDeviceProperties = extern struct {
    apiVersion: u32,
    driverVersion: u32,
    vendorID: u32,
    deviceID: u32,
    deviceType: u32,
    deviceName: [VK_MAX_PHYSICAL_DEVICE_NAME_SIZE]u8,
    pipelineCacheUUID: [VK_UUID_SIZE]u8,
    limits: VkPhysicalDeviceLimits,
    sparseProperties: VkPhysicalDeviceSparseProperties,
};

pub const VkPhysicalDeviceProperties2 = extern struct {
    sType: vk.VkStructureType,
    pNext: ?*anyopaque,
    properties: VkPhysicalDeviceProperties,
};

pub const VkPhysicalDeviceSubgroupProperties = extern struct {
    sType: vk.VkStructureType,
    pNext: ?*anyopaque,
    subgroupSize: u32,
    supportedStages: vk.VkFlags,
    supportedOperations: vk.VkFlags,
    quadOperationsInAllStages: vk.VkBool32,
};

pub const VkPhysicalDeviceVulkan12Features = extern struct {
    sType: vk.VkStructureType,
    pNext: ?*anyopaque,
    samplerMirrorClampToEdge: vk.VkBool32,
    drawIndirectCount: vk.VkBool32,
    storageBuffer8BitAccess: vk.VkBool32,
    uniformAndStorageBuffer8BitAccess: vk.VkBool32,
    storagePushConstant8: vk.VkBool32,
    shaderBufferInt64Atomics: vk.VkBool32,
    shaderSharedInt64Atomics: vk.VkBool32,
    shaderFloat16: vk.VkBool32,
    shaderInt8: vk.VkBool32,
    descriptorIndexing: vk.VkBool32,
    shaderInputAttachmentArrayDynamicIndexing: vk.VkBool32,
    shaderUniformTexelBufferArrayDynamicIndexing: vk.VkBool32,
    shaderStorageTexelBufferArrayDynamicIndexing: vk.VkBool32,
    shaderUniformBufferArrayNonUniformIndexing: vk.VkBool32,
    shaderSampledImageArrayNonUniformIndexing: vk.VkBool32,
    shaderStorageBufferArrayNonUniformIndexing: vk.VkBool32,
    shaderStorageImageArrayNonUniformIndexing: vk.VkBool32,
    shaderInputAttachmentArrayNonUniformIndexing: vk.VkBool32,
    shaderUniformTexelBufferArrayNonUniformIndexing: vk.VkBool32,
    shaderStorageTexelBufferArrayNonUniformIndexing: vk.VkBool32,
    descriptorBindingUniformBufferUpdateAfterBind: vk.VkBool32,
    descriptorBindingSampledImageUpdateAfterBind: vk.VkBool32,
    descriptorBindingStorageImageUpdateAfterBind: vk.VkBool32,
    descriptorBindingStorageBufferUpdateAfterBind: vk.VkBool32,
    descriptorBindingUniformTexelBufferUpdateAfterBind: vk.VkBool32,
    descriptorBindingStorageTexelBufferUpdateAfterBind: vk.VkBool32,
    descriptorBindingUpdateUnusedWhilePending: vk.VkBool32,
    descriptorBindingPartiallyBound: vk.VkBool32,
    descriptorBindingVariableDescriptorCount: vk.VkBool32,
    runtimeDescriptorArray: vk.VkBool32,
    samplerFilterMinmax: vk.VkBool32,
    scalarBlockLayout: vk.VkBool32,
    imagelessFramebuffer: vk.VkBool32,
    uniformBufferStandardLayout: vk.VkBool32,
    shaderSubgroupExtendedTypes: vk.VkBool32,
    separateDepthStencilLayouts: vk.VkBool32,
    hostQueryReset: vk.VkBool32,
    timelineSemaphore: vk.VkBool32,
    bufferDeviceAddress: vk.VkBool32,
    bufferDeviceAddressCaptureReplay: vk.VkBool32,
    bufferDeviceAddressMultiDevice: vk.VkBool32,
    vulkanMemoryModel: vk.VkBool32,
    vulkanMemoryModelDeviceScope: vk.VkBool32,
    vulkanMemoryModelAvailabilityVisibilityChains: vk.VkBool32,
    shaderOutputViewportIndex: vk.VkBool32,
    shaderOutputLayer: vk.VkBool32,
    subgroupBroadcastDynamicId: vk.VkBool32,
};
