import Doe.Core.Bridge
import Doe.Core.BindGroupSlot
import Doe.Core.BufferLifecycle
import Doe.Core.Dispatch
import Doe.Core.DeterminismPolicy
import Doe.Core.IrBuilderSoundness
import Doe.Core.IrSemanticContract
import Doe.Core.IrValidatorRedundancy
import Doe.Core.RenderPassStateMachine
import Doe.Core.MslAddressSpace
import Doe.Core.BufferDispatchPrecondition
import Doe.Core.IrTypePreserved
import Doe.Full.ComparabilityFixtures
import Doe.Full.WorkloadGeometry
import Doe.Shader.ComputeBounds

set_option maxRecDepth 4096

private def jsonBool (b : Bool) : String := if b then "true" else "false"

private def requireEnv (name : String) : IO String := do
  match (← IO.getEnv name) with
  | some value => pure value
  | none => throw (IO.userError s!"missing required extraction env var: {name}")

/-- Emit proof artifact as JSON to stdout.
    Compilation of this module verifies all imported theorems.
    Decidable propositions are additionally evaluated at runtime. -/
def main : IO Unit := do
  let leanToolchainRef ← requireEnv "DOE_LEAN_TOOLCHAIN_REF"
  let extractProgramSha256 ← requireEnv "DOE_LEAN_EXTRACT_PROGRAM_SHA256"
  let leanSourceTreeSha256 ← requireEnv "DOE_LEAN_SOURCE_TREE_SHA256"
  let generatedComparabilityContractSha256 ← requireEnv "DOE_LEAN_GENERATED_COMPARABILITY_CONTRACT_SHA256"
  let proofPatternSpecSha256 ← requireEnv "DOE_LEAN_PROOF_PATTERN_SPEC_SHA256"
  let happyPath := comparableFromFacts strictHappyPathFacts
  let missingLeft := comparableFromFacts strictMissingLeftSamplesFacts
  let densityFailure := comparableFromFacts allowLeftNoExecutionDensityFailureFacts
  let happyPathBlocking := (failedBlockingObligations (obligationsFromFacts strictHappyPathFacts)).length
  let missingLeftBlocking := (failedBlockingObligations (obligationsFromFacts strictMissingLeftSamplesFacts)).length
  let densityFailureBlocking := (failedBlockingObligations (obligationsFromFacts allowLeftNoExecutionDensityFailureFacts)).length

  IO.println "{"
  IO.println "  \"schemaVersion\": 1,"
  IO.println "  \"status\": \"verified\","
  IO.println "  \"provenance\": {"
  IO.println ("    \"leanToolchainRef\": \"" ++ leanToolchainRef ++ "\",")
  IO.println ("    \"extractProgramSha256\": \"" ++ extractProgramSha256 ++ "\",")
  IO.println ("    \"leanSourceTreeSha256\": \"" ++ leanSourceTreeSha256 ++ "\",")
  IO.println ("    \"generatedComparabilityContractSha256\": \"" ++ generatedComparabilityContractSha256 ++ "\",")
  IO.println ("    \"proofPatternSpecSha256\": \"" ++ proofPatternSpecSha256 ++ "\"")
  IO.println "  },"
  IO.println "  \"contractHashes\": {"
  IO.println ("    \"comparabilityObligationsSha256\": \"" ++ comparabilityContractSha256 ++ "\"")
  IO.println "  },"
  IO.println "  \"theorems\": ["
  IO.println "    { \"name\": \"critical_is_max_rank\", \"module\": \"Doe.Core.Model\", \"category\": \"comptime_verified\" },"
  IO.println "    { \"name\": \"requiredProof_forbidden_reject_from_rank\", \"module\": \"Doe.Core.Model\", \"category\": \"comptime_verified\" },"
  IO.println "    { \"name\": \"toggleAlwaysSupported\", \"module\": \"Doe.Core.Dispatch\", \"category\": \"tautological\" },"
  IO.println "    { \"name\": \"strongerSafetyRaisesProofDemand\", \"module\": \"Doe.Core.Dispatch\", \"category\": \"comptime_verified\" },"
  IO.println "    { \"name\": \"betterMatch_prefers_higher_score\", \"module\": \"Doe.Core.Runtime\", \"category\": \"tautological\" },"
  IO.println "    { \"name\": \"stableTokenChoose_mem_tiedMaxIndices\", \"module\": \"Doe.Core.DeterminismPolicy\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"stableTokenChoose_le_all_tiedMaxIndices\", \"module\": \"Doe.Core.DeterminismPolicy\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"exactMaxTieTriggered_iff_two_or_more_candidates\", \"module\": \"Doe.Core.DeterminismPolicy\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"candidateMarginBandTriggered_iff_gap_within_epsilon\", \"module\": \"Doe.Core.DeterminismPolicy\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"fixedPriorityBetter_true_implies_lexicographic_preference\", \"module\": \"Doe.Core.DeterminismPolicy\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"reviewedChoiceSelect_uses_review_token_when_present\", \"module\": \"Doe.Core.DeterminismPolicy\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"comparableFromObligations_eq_noFailed\", \"module\": \"Doe.Full.Comparability\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"comparableFromFacts_eq_noFailed\", \"module\": \"Doe.Full.Comparability\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"comparableFromObligations_true_iff_failedBlockingNil\", \"module\": \"Doe.Full.Comparability\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"comparableFromObligations_false_iff_failedBlockingNonEmpty\", \"module\": \"Doe.Full.Comparability\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"comparableFromFacts_true_iff_failedBlockingNil\", \"module\": \"Doe.Full.Comparability\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"comparableFromFacts_false_iff_failedBlockingNonEmpty\", \"module\": \"Doe.Full.Comparability\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"structurallyEquivalentGeometry_refl\", \"module\": \"Doe.Full.WorkloadGeometry\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"structurallyEquivalentGeometry_forall_components\", \"module\": \"Doe.Full.WorkloadGeometry\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"equalGeometrySetsExecutionShapeFacts\", \"module\": \"Doe.Full.WorkloadGeometry\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"strictHappyPathExpectedBlocking_exact\", \"module\": \"Doe.Full.ComparabilityFixtures\", \"category\": \"lean_fixture\" },"
  IO.println "    { \"name\": \"strictHappyPathComparable\", \"module\": \"Doe.Full.ComparabilityFixtures\", \"category\": \"lean_fixture\" },"
  IO.println "    { \"name\": \"strictMissingLeftSamplesExpectedBlocking_exact\", \"module\": \"Doe.Full.ComparabilityFixtures\", \"category\": \"lean_fixture\" },"
  IO.println "    { \"name\": \"strictMissingLeftSamplesComparable\", \"module\": \"Doe.Full.ComparabilityFixtures\", \"category\": \"lean_fixture\" },"
  IO.println "    { \"name\": \"allowLeftNoExecutionDensityFailureExpectedBlocking_exact\", \"module\": \"Doe.Full.ComparabilityFixtures\", \"category\": \"lean_fixture\" },"
  IO.println "    { \"name\": \"allowLeftNoExecutionDensityFailureComparable\", \"module\": \"Doe.Full.ComparabilityFixtures\", \"category\": \"lean_fixture\" },"
  IO.println "    { \"name\": \"noOpActionIdentity\", \"module\": \"Doe.Core.Dispatch\", \"category\": \"tautological\" },"
  IO.println "    { \"name\": \"informationalToggleIdentity\", \"module\": \"Doe.Core.Dispatch\", \"category\": \"tautological\" },"
  IO.println "    { \"name\": \"unhandledToggleIdentity\", \"module\": \"Doe.Core.Dispatch\", \"category\": \"tautological\" },"
  IO.println "    { \"name\": \"behavioralToggleNotIdentity\", \"module\": \"Doe.Core.Dispatch\", \"category\": \"tautological\" },"
  IO.println "    { \"name\": \"identityActionComplete\", \"module\": \"Doe.Core.Dispatch\", \"category\": \"comptime_verified\" },"
  IO.println "    { \"name\": \"scopeCommandTableComplete\", \"module\": \"Doe.Core.Dispatch\", \"category\": \"tautological\" },"
  IO.println "    { \"name\": \"identityActionPreservesCommand\", \"module\": \"Doe.Core.Dispatch\", \"category\": \"tautological\" },"
  IO.println "    { \"name\": \"mslBindingSlot_injective_within_group\", \"module\": \"Doe.Core.BindGroupSlot\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"mslBindingSlot_injective_across_groups\", \"module\": \"Doe.Core.BindGroupSlot\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"mslBindingSlot_in_bounds\", \"module\": \"Doe.Core.BindGroupSlot\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"mslBindingSlot_distinct_groups\", \"module\": \"Doe.Core.BindGroupSlot\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"doeRelease_terminal\", \"module\": \"Doe.Core.BufferLifecycle\", \"category\": \"tautological\" },"
  IO.println "    { \"name\": \"released_absorbs_all\", \"module\": \"Doe.Core.BufferLifecycle\", \"category\": \"tautological\" },"
  IO.println "    { \"name\": \"doeMapAsync_idempotent\", \"module\": \"Doe.Core.BufferLifecycle\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"doeUnmap_idempotent\", \"module\": \"Doe.Core.BufferLifecycle\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"doeMapUnmap_roundtrip\", \"module\": \"Doe.Core.BufferLifecycle\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"doe_getMappedRange_gap\", \"module\": \"Doe.Core.BufferLifecycle\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"doe_dispatch_gap\", \"module\": \"Doe.Core.BufferLifecycle\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"doe_getMappedRange_superset\", \"module\": \"Doe.Core.BufferLifecycle\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"doe_dispatch_superset\", \"module\": \"Doe.Core.BufferLifecycle\", \"category\": \"lean_verified\" },"
  IO.println "    { \"name\": \"ExprIdValid_mono\", \"module\": \"Doe.Core.IrBuilderSoundness\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"ExprArgRangeValid_mono\", \"module\": \"Doe.Core.IrBuilderSoundness\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"StmtIdValid_mono\", \"module\": \"Doe.Core.IrBuilderSoundness\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"StmtChildRangeValid_mono\", \"module\": \"Doe.Core.IrBuilderSoundness\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"SwitchCaseRangeValid_mono\", \"module\": \"Doe.Core.IrBuilderSoundness\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"builder_soundness\", \"module\": \"Doe.Core.IrBuilderSoundness\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"TypesCompatible_refl\", \"module\": \"Doe.Core.IrSemanticContract\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"IsBoolType_not_integer\", \"module\": \"Doe.Core.IrSemanticContract\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"builder_load_inner_is_ref\", \"module\": \"Doe.Core.IrSemanticContract\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"builder_assign_lhs_is_ref\", \"module\": \"Doe.Core.IrSemanticContract\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"bounds_checks_pre_satisfied\", \"module\": \"Doe.Core.IrValidatorRedundancy\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"semantic_checks_pre_satisfied\", \"module\": \"Doe.Core.IrValidatorRedundancy\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"ValidatorRedundant\", \"module\": \"Doe.Core.IrValidatorRedundancy\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"ended_absorbs_all_ops\", \"module\": \"Doe.Core.RenderPassStateMachine\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"finished_absorbs_all_ops\", \"module\": \"Doe.Core.RenderPassStateMachine\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"chain_preserves_addr_space\", \"module\": \"Doe.Core.MslAddressSpace\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"chain_msl_qualifier_invariant\", \"module\": \"Doe.Core.MslAddressSpace\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"storage_ref_chain_emits_device\", \"module\": \"Doe.Core.MslAddressSpace\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"uniform_ref_chain_emits_constant\", \"module\": \"Doe.Core.MslAddressSpace\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"liveOps_preserve_live\", \"module\": \"Doe.Core.BufferDispatchPrecondition\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"liveOps_dispatch_always_ready\", \"module\": \"Doe.Core.BufferDispatchPrecondition\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"nPasses_preserve_original_types\", \"module\": \"Doe.Core.IrTypePreserved\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"gid_component_lt_total\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"gid_inbounds_when_dispatch_fits\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"gid_plus_offset_inbounds_when_dispatch_fits\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"gid_times_stride_plus_offset_inbounds_when_dispatch_fits\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"gid_plus_bounded_loop_index_inbounds_when_dispatch_fits\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"gid_affine_plus_scaled_loop_index_inbounds_when_dispatch_fits\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"gid_tiled_index_plus_offset_inbounds_when_dispatch_fits\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"clamp_noop_when_inbounds\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"gid_2d_inbounds\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"flat_index_2d_inbounds\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"flat_index_2d_plus_offset_inbounds\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"gid_texture_coords_2d_inbounds_when_dispatch_fits\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"guarded_gid_texture_coords_2d_inbounds\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"gid_texture_coords_3d_inbounds_when_dispatch_fits\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" },"
  IO.println "    { \"name\": \"guarded_gid_texture_coords_3d_inbounds\", \"module\": \"Doe.Shader.ComputeBounds\", \"category\": \"lean_required\" }"
  IO.println "  ],"
  IO.println "  \"evaluatedConditions\": {"
  IO.println ("    \"comparability.strictHappyPath.comparable\": " ++ jsonBool happyPath ++ ",")
  IO.println ("    \"comparability.strictHappyPath.failedBlockingCount\": " ++ toString happyPathBlocking ++ ",")
  IO.println ("    \"comparability.strictMissingLeftSamples.comparable\": " ++ jsonBool missingLeft ++ ",")
  IO.println ("    \"comparability.strictMissingLeftSamples.failedBlockingCount\": " ++ toString missingLeftBlocking ++ ",")
  IO.println ("    \"comparability.allowLeftNoExecutionDensityFailure.comparable\": " ++ jsonBool densityFailure ++ ",")
  IO.println ("    \"comparability.allowLeftNoExecutionDensityFailure.failedBlockingCount\": " ++ toString densityFailureBlocking ++ ",")
  IO.println ("    \"dispatch.criticalSafetyRank\": " ++ toString SafetyClass.critical.rank ++ ",")
  IO.println ("    \"dispatch.provenProofRank\": " ++ toString ProofLevel.proven.rank ++ ",")
  IO.println ("    \"dispatch.noOpIsIdentity\": " ++ jsonBool ActionKind.no_op.isIdentity ++ ",")
  IO.println ("    \"dispatch.informationalToggleIsIdentity\": " ++ jsonBool (ActionKind.toggle .informational).isIdentity ++ ",")
  IO.println ("    \"dispatch.behavioralToggleIsIdentity\": " ++ jsonBool (ActionKind.toggle .behavioral).isIdentity ++ ",")
  IO.println ("    \"dispatch.driverToggleSupportsUpload\": " ++ jsonBool (supportsScope .driver_toggle .upload) ++ ",")
  IO.println ("    \"dispatch.driverToggleSupportsMapAsync\": " ++ jsonBool (supportsScope .driver_toggle .mapAsync) ++ ",")
  IO.println ("    \"dispatch.alignmentSupportsBarrier\": " ++ jsonBool (supportsScope .alignment .barrier) ++ ",")
  IO.println ("    \"dispatch.layoutSupportsRenderDraw\": " ++ jsonBool (supportsScope .layout .renderDraw) ++ ",")
  IO.println ("    \"bindGroupSlot.slot_0_0\": " ++ toString (mslBindingSlot 0 0) ++ ",")
  IO.println ("    \"bindGroupSlot.slot_1_0\": " ++ toString (mslBindingSlot 1 0) ++ ",")
  IO.println ("    \"bindGroupSlot.slot_3_15\": " ++ toString (mslBindingSlot 3 15) ++ ",")
  IO.println ("    \"bufferLifecycle.doeAllowsGetMappedRange_unmapped\": " ++ jsonBool (doeAllowsGetMappedRange .unmapped) ++ ",")
  IO.println ("    \"bufferLifecycle.specAllowsGetMappedRange_unmapped\": " ++ jsonBool (specAllowsGetMappedRange .unmapped) ++ ",")
  IO.println ("    \"bufferLifecycle.doeAllowsDispatch_mapped\": " ++ jsonBool (doeAllowsDispatch .mapped) ++ ",")
  IO.println ("    \"bufferLifecycle.specAllowsDispatch_mapped\": " ++ jsonBool (specAllowsDispatch .mapped))
  IO.println "  },"
  IO.println "  \"boundsEliminations\": ["
  IO.println "    {"
  IO.println "      \"theorem\": \"gid_inbounds_when_dispatch_fits\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"global_invocation_id.{component} indexes storage buffer\","
  IO.println "      \"precondition\": \"workgroup_size.{component} * num_workgroups.{component} <= buffer_element_count\","
  IO.println "      \"eliminates\": \"min(gid.{component}, arrayLength(&buf) - 1) -> gid.{component}\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_runtime_sized\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"gid_plus_offset_inbounds_when_dispatch_fits\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"global_invocation_id.{component} + constant indexes storage buffer\","
  IO.println "      \"precondition\": \"workgroup_size.{component} * num_workgroups.{component} + constant <= buffer_element_count\","
  IO.println "      \"eliminates\": \"min(gid.{component} + constant, arrayLength(&buf) - 1) -> gid.{component} + constant\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_runtime_sized\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"gid_times_stride_plus_offset_inbounds_when_dispatch_fits\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"global_invocation_id.{component} * constant + constant indexes storage buffer\","
  IO.println "      \"precondition\": \"workgroup_size.{component} * num_workgroups.{component} * stride + offset <= buffer_element_count\","
  IO.println "      \"eliminates\": \"min(gid.{component} * stride + offset, arrayLength(&buf) - 1) -> gid.{component} * stride + offset\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_runtime_sized\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"gid_plus_bounded_loop_index_inbounds_when_dispatch_fits\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"canonical counted-loop local i with global_invocation_id.{component} + i + constant indexing a storage buffer\","
  IO.println "      \"precondition\": \"either for (var i = 0; i < limit; i = i + 1) or var i = 0; loop { if (i >= limit) { break; } ... continuing { i = i + 1; } } AND workgroup_size.{component} * num_workgroups.{component} + limit + offset <= buffer_element_count\","
  IO.println "      \"eliminates\": \"min(gid.{component} + i + offset, arrayLength(&buf) - 1) -> gid.{component} + i + offset\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_runtime_sized\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"gid_affine_plus_scaled_loop_index_inbounds_when_dispatch_fits\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"canonical counted-loop local i with global_invocation_id.{component} * gid_stride + i * loop_stride + constant indexing a storage buffer\","
  IO.println "      \"precondition\": \"supported counted-loop form with i < limit, gid_stride > 0, loop_stride > 0, and workgroup_size.{component} * num_workgroups.{component} * gid_stride + limit * loop_stride + offset <= buffer_element_count\","
  IO.println "      \"eliminates\": \"min(gid.{component} * gid_stride + i * loop_stride + offset, arrayLength(&buf) - 1) -> gid.{component} * gid_stride + i * loop_stride + offset\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_runtime_sized\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"gid_tiled_index_plus_offset_inbounds_when_dispatch_fits\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"(global_invocation_id.{component} / tile_width) * tile_stride + (global_invocation_id.{component} % tile_width) + constant indexes storage buffer\","
  IO.println "      \"precondition\": \"tile_width > 0 AND tile_width <= tile_stride AND (((workgroup_size.{component} * num_workgroups.{component} - 1) / tile_width) + 1) * tile_stride + offset <= buffer_element_count\","
  IO.println "      \"eliminates\": \"min(tiled_index + offset, arrayLength(&buf) - 1) -> tiled_index + offset\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_runtime_sized\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"flat_index_2d_inbounds\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"gid.y * width + gid.x indexes storage buffer\","
  IO.println "      \"precondition\": \"ws.x * nwg.x <= width AND ws.y * nwg.y <= height AND width * height <= buffer_element_count\","
  IO.println "      \"eliminates\": \"min(flat_index, arrayLength(&buf) - 1) -> flat_index\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_runtime_sized\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"flat_index_2d_plus_offset_inbounds\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"gid.y * width + gid.x + constant indexes storage buffer\","
  IO.println "      \"precondition\": \"ws.x * nwg.x <= width AND ws.y * nwg.y <= height AND width * height + offset <= buffer_element_count\","
  IO.println "      \"eliminates\": \"min(flat_index + offset, arrayLength(&buf) - 1) -> flat_index + offset\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_runtime_sized\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"guarded_gid_texture_coords_2d_inbounds\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"global_invocation_id.xy texture coords guarded by root early-return against textureDimensions(tex[,level]).xy\","
  IO.println "      \"precondition\": \"if gid.x >= textureDimensions(...).x || gid.y >= textureDimensions(...).y { return; }\","
  IO.println "      \"eliminates\": \"clamp(coords, vec(0), textureDimensions(tex[,level]) - 1) -> coords\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_texture_coords\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"gid_texture_coords_2d_inbounds_when_dispatch_fits\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"global_invocation_id.xy texture coords on a bound 2D texture\","
  IO.println "      \"precondition\": \"workgroup_size.x * num_workgroups.x <= textureDimensions(tex,0).x AND workgroup_size.y * num_workgroups.y <= textureDimensions(tex,0).y\","
  IO.println "      \"eliminates\": \"clamp(coords, vec(0), textureDimensions(tex[,level]) - 1) -> coords\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_texture_coords\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"guarded_gid_texture_coords_3d_inbounds\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"global_invocation_id.xyz texture coords guarded by root early-return against textureDimensions(tex[,level]).xyz\","
  IO.println "      \"precondition\": \"if gid.x >= textureDimensions(...).x || gid.y >= textureDimensions(...).y || gid.z >= textureDimensions(...).z { return; }\","
  IO.println "      \"eliminates\": \"clamp(coords, vec(0), textureDimensions(tex[,level]) - 1) -> coords\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_texture_coords\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"gid_texture_coords_3d_inbounds_when_dispatch_fits\","
  IO.println "      \"module\": \"Doe.Shader.ComputeBounds\","
  IO.println "      \"category\": \"lean_required\","
  IO.println "      \"pattern\": \"global_invocation_id.xyz texture coords on a bound 3D texture\","
  IO.println "      \"precondition\": \"workgroup_size.x * num_workgroups.x <= textureDimensions(tex,0).x AND workgroup_size.y * num_workgroups.y <= textureDimensions(tex,0).y AND workgroup_size.z * num_workgroups.z <= textureDimensions(tex,0).z\","
  IO.println "      \"eliminates\": \"clamp(coords, vec(0), textureDimensions(tex[,level]) - 1) -> coords\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/ir_transform_robustness.zig:clamp_texture_coords\""
  IO.println "    }"
  IO.println "  ],"
  IO.println "  \"eliminationTargets\": ["
  IO.println "    {"
  IO.println "      \"theorem\": \"toggleAlwaysSupported\","
  IO.println "      \"condition\": \"scope == driver_toggle implies supports all commands\","
  IO.println "      \"runtimePath\": \"quirk/runtime.zig:supportsScope\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"requiredProof_forbidden_reject_from_rank\","
  IO.println "      \"condition\": \"no safety class maps to ProofLevel.rejected\","
  IO.println "      \"runtimePath\": \"quirk/runtime.zig:finalizeBucket\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"strongerSafetyRaisesProofDemand\","
  IO.println "      \"condition\": \"critical safety class requires proven proof level\","
  IO.println "      \"runtimePath\": \"quirk/runtime.zig:finalizeBucket\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"identityActionComplete\","
  IO.println "      \"condition\": \"no_op, informational toggle, and unhandled toggle actions are identity; behavioral toggle is not\","
  IO.println "      \"runtimePath\": \"quirk/runtime.zig:dispatch\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"scopeCommandTableComplete\","
  IO.println "      \"condition\": \"comptime scope×command table matches supportsScope for all pairs; subsumes toggleAlwaysSupported\","
  IO.println "      \"runtimePath\": \"quirk/runtime.zig:buildDispatchContext,buildProfileDispatchContext\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"identityActionPreservesCommand\","
  IO.println "      \"condition\": \"identity actions preserve the command unchanged; dispatch can skip applyAction\","
  IO.println "      \"runtimePath\": \"quirk/runtime.zig:dispatch\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"equalGeometrySetsExecutionShapeFacts\","
  IO.println "      \"condition\": \"matching buffer size and dispatch geometry force execution-shape comparability facts true for arbitrary Nat-valued workloads\","
  IO.println "      \"runtimePath\": \"bench/native_compare_modules/comparability.py:evaluate_comparability_from_facts\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"mslBindingSlot_injective_across_groups\","
  IO.println "      \"condition\": \"group*16+binding is injective for binding<16; flat buffer array has no collisions\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/emit_msl_ir.zig:msl_binding_slot,runtime/zig/src/doe_compute_ext_native.zig:flattenBindGroups\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"mslBindingSlot_in_bounds\","
  IO.println "      \"condition\": \"valid group and binding produce slot < 64; bounds check can be elided at comptime\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_compute_ext_native.zig:flattenBindGroups\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"doe_getMappedRange_superset\","
  IO.println "      \"condition\": \"Doe permits all spec-valid getMappedRange calls; no false rejections\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgpu_native.zig:doeBufferGetMappedRange\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"doe_dispatch_superset\","
  IO.println "      \"condition\": \"Doe permits all spec-valid dispatch calls; no false rejections\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgpu_native.zig:doeBufferRelease\""
  IO.println "    },"
  IO.println "    {"
  IO.println "      \"theorem\": \"ValidatorRedundant\","
  IO.println "      \"condition\": \"sema-Ok + build-Ok IR satisfies all ir_validate.validate() checks; validate() call is eliminable\","
  IO.println "      \"runtimePath\": \"runtime/zig/src/doe_wgsl/mod.zig:analyzeToIr\""
  IO.println "    }"
  IO.println "  ]"
  IO.println "}"
