// Generated by tools/generate_test_suites.py from config/zig-test-inventory.json.
// Do not edit this file directly.
const test_tests_backend_backend_identity_test_zig_327f4508 = @import("tests/backend/backend_identity_test.zig");
const test_tests_backend_backend_runtime_config_policy_test_zig_a6480ea9 = @import("tests/backend/backend_runtime_config_policy_test.zig");
const test_tests_backend_backend_runtime_policy_test_zig_f04cc8a6 = @import("tests/backend/backend_runtime_policy_test.zig");
const test_tests_backend_backend_selection_policy_test_zig_153fd435 = @import("tests/backend/backend_selection_policy_test.zig");
const test_tests_backend_backend_vulkan_doe_app_lane_policy_test_zig_6d3b28d3 = @import("tests/backend/backend_vulkan_doe_app_lane_policy_test.zig");
const test_tests_backend_common_artifact_meta_test_zig_80b3c4bd = @import("tests/backend/common_artifact_meta_test.zig");
const test_tests_backend_common_capabilities_test_zig_a8b72200 = @import("tests/backend/common_capabilities_test.zig");
const test_tests_backend_common_command_info_test_zig_f3c88d8e = @import("tests/backend/common_command_info_test.zig");
const test_tests_backend_common_errors_test_zig_d930e12d = @import("tests/backend/common_errors_test.zig");
const test_tests_backend_common_timing_test_zig_c0d7814b = @import("tests/backend/common_timing_test.zig");
const test_tests_d3d12_d3d12_mod_integration_test_zig_1dfc7364 = @import("tests/d3d12/d3d12_mod_integration_test.zig");
const test_tests_d3d12_d3d12_timing_semantics_test_zig_d70c327c = @import("tests/d3d12/d3d12_timing_semantics_test.zig");
const test_tests_backend_d3d12_descriptors_formats_test_zig_30b22068 = @import("tests/backend/d3d12_descriptors_formats_test.zig");
const test_tests_d3d12_d3d12_native_unit_test_zig_8a0c5009 = @import("tests/d3d12/d3d12_native_unit_test.zig");
const test_src_backend_d3d12_commands_d3d12_dispatch_zig_793febe7 = @import("src/backend/d3d12/commands/d3d12_dispatch.zig");
const test_src_backend_d3d12_d3d12_native_runtime_zig_55270130 = @import("src/backend/d3d12/d3d12_native_runtime.zig");
const test_src_backend_d3d12_d3d12_runtime_upload_zig_19153cf8 = @import("src/backend/d3d12/d3d12_runtime_upload.zig");
const test_src_backend_d3d12_commands_d3d12_streaming_copy_zig_061dc0c0 = @import("src/backend/d3d12/commands/d3d12_streaming_copy.zig");

comptime {
    _ = test_tests_backend_backend_identity_test_zig_327f4508;
    _ = test_tests_backend_backend_runtime_config_policy_test_zig_a6480ea9;
    _ = test_tests_backend_backend_runtime_policy_test_zig_f04cc8a6;
    _ = test_tests_backend_backend_selection_policy_test_zig_153fd435;
    _ = test_tests_backend_backend_vulkan_doe_app_lane_policy_test_zig_6d3b28d3;
    _ = test_tests_backend_common_artifact_meta_test_zig_80b3c4bd;
    _ = test_tests_backend_common_capabilities_test_zig_a8b72200;
    _ = test_tests_backend_common_command_info_test_zig_f3c88d8e;
    _ = test_tests_backend_common_errors_test_zig_d930e12d;
    _ = test_tests_backend_common_timing_test_zig_c0d7814b;
    _ = test_tests_d3d12_d3d12_mod_integration_test_zig_1dfc7364;
    _ = test_tests_d3d12_d3d12_timing_semantics_test_zig_d70c327c;
    _ = test_tests_backend_d3d12_descriptors_formats_test_zig_30b22068;
    _ = test_tests_d3d12_d3d12_native_unit_test_zig_8a0c5009;
    _ = test_src_backend_d3d12_commands_d3d12_dispatch_zig_793febe7;
    _ = test_src_backend_d3d12_d3d12_native_runtime_zig_55270130;
    _ = test_src_backend_d3d12_d3d12_runtime_upload_zig_19153cf8;
    _ = test_src_backend_d3d12_commands_d3d12_streaming_copy_zig_061dc0c0;
}
