// Generated by tools/generate_test_suites.py from config/zig-test-inventory.json.
// Do not edit this file directly.
const suite_aggregate_ee3c65b5 = @import("test_suite.zig");
const test_tests_core_command_scope_test_zig_a677642c = @import("tests/core/command_scope_test.zig");
const test_tests_full_command_scope_test_zig_125739d8 = @import("tests/full/command_scope_test.zig");
const test_tests_core_surface_test_zig_20da8529 = @import("tests/core/surface_test.zig");
const test_tests_full_surface_api_test_zig_995dbed5 = @import("tests/full/surface_api_test.zig");
const test_src_native_support_doe_callback_delivery_zig_24ee01a5 = @import("src/native/support/doe_callback_delivery.zig");
const test_src_native_support_doe_future_ids_zig_46c77022 = @import("src/native/support/doe_future_ids.zig");
const test_src_native_support_doe_device_loss_zig_09817a3f = @import("src/native/support/doe_device_loss.zig");

comptime {
    _ = suite_aggregate_ee3c65b5;
    _ = test_tests_core_command_scope_test_zig_a677642c;
    _ = test_tests_full_command_scope_test_zig_125739d8;
    _ = test_tests_core_surface_test_zig_20da8529;
    _ = test_tests_full_surface_api_test_zig_995dbed5;
    _ = test_src_native_support_doe_callback_delivery_zig_24ee01a5;
    _ = test_src_native_support_doe_future_ids_zig_46c77022;
    _ = test_src_native_support_doe_device_loss_zig_09817a3f;
}
