// Generated by tools/generate_test_suites.py from config/zig-test-inventory.json.
// Do not edit this file directly.
const test_tests_wgsl_browser_wgsl_test_zig_1f1e4c0b = @import("tests/wgsl/browser_wgsl_test.zig");

comptime {
    _ = test_tests_wgsl_browser_wgsl_test_zig_1f1e4c0b;
}
