#!/usr/bin/env python3
"""Fail the pack if receipt hashes have drifted since the pinned baseline.

Mitigates "Bundle staleness from runtime/zig changes" / "TSIR or
doe_wgsl edits invalidate emitted hashes" from
docs/cerebras-north-star.md (Local risk mitigations). Wraps
`bench/tools/prepare_cerebras_validation_bundle.sh` with a pre-step
that computes sha256 of every receipt path the packer's INCLUDE_FILES
declares, compares against a pinned baseline, and exits non-zero when
any pinned receipt has drifted unexpectedly.

Two operating modes:

  * --update-baseline (or first run when no baseline exists):
      Compute current hashes and write them to
      `bench/fingerprints/prepack-fingerprints.json`. Exits 0.

  * Default (baseline present):
      Recompute current hashes for the stable pinned subset, compare
      to baseline. Exit 0 if that include set matches the baseline and
      every pinned receipt hash matches. Exit 1 with a report if any
      receipt's sha256 differs, a new include path appears, or a
      baseline path disappears.

The guard is intentionally narrow: it only checks files the packer
declares in INCLUDE_FILES (it does not walk bench/out/). Files that
appear in INCLUDE_FILES but are absent on disk are listed as
`missing` in the drift report; that is the packer's existing failure
mode, surfaced earlier.

Usage:
  python3 bench/tools/prepack_hash_drift_guard.py
  python3 bench/tools/prepack_hash_drift_guard.py --update-baseline
  python3 bench/tools/prepack_hash_drift_guard.py --baseline PATH
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BASELINE = REPO_ROOT / "bench" / "fingerprints" / "prepack-fingerprints.json"
PACKER_PATH = REPO_ROOT / "bench" / "tools" / "pack_cerebras_validation_archive.py"
PINNED_INCLUDE_PREFIXES: tuple[str, ...] = (
    "config/",
    "docs/",
    "bench/out/26b-moe-lane/",
    "bench/out/31b-full-graph/",
    "bench/out/r3-1-",
    "bench/out/doppler-reference/gemma-4-e2b-int4ple-production-final-logits/",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--baseline",
        type=Path,
        default=DEFAULT_BASELINE,
        help="Path to the pinned-fingerprints JSON.",
    )
    parser.add_argument(
        "--update-baseline",
        action="store_true",
        help=(
            "Recompute fingerprints and overwrite the baseline. Use this "
            "when receipt drift is intentional (e.g. after a runtime/zig "
            "change that legitimately changes emitted hashes)."
        ),
    )
    parser.add_argument(
        "--show-all",
        action="store_true",
        help="Print every drift entry. Default shows first 20 then count.",
    )
    return parser.parse_args()


def load_packer_include_files() -> list[str]:
    """Import the packer module and return its INCLUDE_FILES tuple as
    a flat list of stable pinned source paths.

    Some bundle entries are regenerated by the gate runner and contain
    volatile timing or capture metadata. Those gates are still verified
    by `run_cerebras_evidence_bundle.py`; this guard pins the stable
    promoted/config/doc evidence surface so intentional receipt changes
    must be accepted explicitly.
    """
    spec = importlib.util.spec_from_file_location(
        "pack_cerebras_validation_archive", PACKER_PATH
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load packer module at {PACKER_PATH}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    paths: list[str] = []
    for entry in mod.INCLUDE_FILES:
        if isinstance(entry, tuple):
            # Tuple form: (source_relpath, archive_relpath). Pin the
            # SOURCE because that is the on-disk file whose hash drifts.
            source = entry[0]
            # Strip the `path.md#ARCHIVE_NAME.md` extraction syntax —
            # those archive entries are extracted from a section of a
            # markdown source rather than a free-standing file.
            if "#" in source:
                source = source.split("#", 1)[0]
            if source.startswith(PINNED_INCLUDE_PREFIXES):
                paths.append(source)
        else:
            if entry.startswith(PINNED_INCLUDE_PREFIXES):
                paths.append(entry)
    return paths


def sha256_of_file(path: Path) -> str | None:
    if not path.is_file():
        return None
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def compute_fingerprints(include_paths: list[str]) -> dict:
    rows = []
    missing = []
    for rel in sorted(set(include_paths)):
        abs_path = REPO_ROOT / rel
        digest = sha256_of_file(abs_path)
        if digest is None:
            missing.append(rel)
            continue
        rows.append({"path": rel, "sha256": digest})
    return {"fingerprints": rows, "missing": missing}


def diff_fingerprints(baseline: dict, current: dict) -> dict:
    base_map = {r["path"]: r["sha256"] for r in baseline.get("fingerprints", [])}
    cur_map = {r["path"]: r["sha256"] for r in current["fingerprints"]}
    drifted = []
    for path, cur_hash in cur_map.items():
        base_hash = base_map.get(path)
        if base_hash is None:
            continue  # new path; not drift
        if base_hash != cur_hash:
            drifted.append({
                "path": path,
                "baseline": base_hash,
                "current": cur_hash,
            })
    new_paths = sorted(set(cur_map.keys()) - set(base_map.keys()))
    removed_paths = sorted(set(base_map.keys()) - set(cur_map.keys()))
    return {
        "drifted": drifted,
        "newPaths": new_paths,
        "removedPaths": removed_paths,
    }


def main() -> int:
    args = parse_args()
    include_paths = load_packer_include_files()
    current = compute_fingerprints(include_paths)
    current_doc = {
        "schemaVersion": 1,
        "artifactKind": "doe_prepack_fingerprints",
        "fingerprints": current["fingerprints"],
        "missing": current["missing"],
    }

    if args.update_baseline or not args.baseline.is_file():
        args.baseline.parent.mkdir(parents=True, exist_ok=True)
        args.baseline.write_text(
            json.dumps(current_doc, indent=2) + "\n", encoding="utf-8"
        )
        action = "wrote" if args.update_baseline else "wrote (first run)"
        print(
            f"PASS: {action} baseline at {args.baseline.relative_to(REPO_ROOT)} "
            f"({len(current['fingerprints'])} pinned, {len(current['missing'])} missing)"
        )
        return 0

    baseline = json.loads(args.baseline.read_text(encoding="utf-8"))
    diff = diff_fingerprints(baseline, current_doc)
    has_set_drift = bool(diff["newPaths"] or diff["removedPaths"])
    if not diff["drifted"] and not has_set_drift:
        print(
            f"PASS: {len(current['fingerprints'])} pinned receipt hashes match "
            f"baseline at {args.baseline.relative_to(REPO_ROOT)}"
        )
        if current["missing"]:
            print(f"  note: {len(current['missing'])} packer include paths absent on disk", file=sys.stderr)
        return 0

    print(
        "FAIL: pinned receipt fingerprints differ from baseline at "
        f"{args.baseline.relative_to(REPO_ROOT)}",
        file=sys.stderr,
    )
    if diff["newPaths"]:
        shown_new = diff["newPaths"] if args.show_all else diff["newPaths"][:20]
        print(f"  new include paths: {len(diff['newPaths'])}", file=sys.stderr)
        for path in shown_new:
            print(f"    + {path}", file=sys.stderr)
        if not args.show_all and len(diff["newPaths"]) > 20:
            print(f"    ... and {len(diff['newPaths']) - 20} more", file=sys.stderr)
    if diff["removedPaths"]:
        shown_removed = (
            diff["removedPaths"] if args.show_all else diff["removedPaths"][:20]
        )
        print(
            f"  removed baseline paths: {len(diff['removedPaths'])}",
            file=sys.stderr,
        )
        for path in shown_removed:
            print(f"    - {path}", file=sys.stderr)
        if not args.show_all and len(diff["removedPaths"]) > 20:
            print(
                f"    ... and {len(diff['removedPaths']) - 20} more",
                file=sys.stderr,
            )
    shown = diff["drifted"] if args.show_all else diff["drifted"][:20]
    if diff["drifted"]:
        print(f"  drifted hashes: {len(diff['drifted'])}", file=sys.stderr)
    for entry in shown:
        print(
            f"    {entry['path']}: baseline={entry['baseline'][:12]}... current={entry['current'][:12]}...",
            file=sys.stderr,
        )
    if not args.show_all and len(diff["drifted"]) > 20:
        print(f"  ... and {len(diff['drifted']) - 20} more", file=sys.stderr)
    print(
        "  Update the baseline with --update-baseline if drift is intentional.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
