#!/usr/bin/env python3
"""Regenerate the Dawn component build that exposes C++ symbols for the cache shim.

The default vendored ``bench/vendor/dawn/out/Release/`` build ships with
``args.gn = "is_debug = false"`` and produces ``libwebgpu_dawn.so`` with the
``wgpu*`` C ABI only -- every ``dawn::platform::*`` and ``dawn::native::*``
symbol is hidden. That default is correct for the existing benchmark lanes,
but the Dawn delegate persistent-cache shim needs the C++ surface exposed.

This script writes a canonical ``args.gn`` into a separate build directory
(default ``bench/vendor/dawn/out/ComponentTest/``) and runs ``gn gen`` so the
operator does not have to remember the flag set. ``--build`` also runs
``ninja`` for ``libdawn_platform.so`` and ``libdawn_native.so``; ``--verify``
runs a symbol check against the built ``.so`` files.

The ``bench/vendor/`` tree is gitignored in full, so the generated build
directory is always an ephemeral local artifact. The tracked contract is this
script: running it with no args reproduces the same build every time.

Usage:
    python3 bench/tools/regenerate_dawn_component_build.py               # gn gen only
    python3 bench/tools/regenerate_dawn_component_build.py --build       # also ninja
    python3 bench/tools/regenerate_dawn_component_build.py --build --verify
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DAWN_ROOT = REPO_ROOT / "bench" / "vendor" / "dawn"
DEFAULT_OUT_DIR_NAME = "ComponentTest"

CANONICAL_ARGS_GN = """\
# Generated by bench/tools/regenerate_dawn_component_build.py.
# Do not edit by hand; re-run the script to refresh this file.
#
# These args expose Dawn's C++ surface (dawn::platform::Platform,
# dawn::platform::CachingInterface, dawn::native::DawnInstanceDescriptor)
# which the Dawn delegate persistent-cache shim subclasses.
# See bench/docs/dawn-delegate-cache-integration.md for the integration plan.

is_debug = false
is_component_build = true
dawn_complete_static_libs = false
use_custom_libcxx = true
dawn_use_swiftshader = false
angle_enable_swiftshader = false
"""

BUILD_TARGETS = (
    "src/dawn/platform:shared",
    "src/dawn/native:shared",
)

REQUIRED_PLATFORM_SYMBOLS = (
    "dawn::platform::Platform::Platform()",
    "dawn::platform::Platform::~Platform()",
    "dawn::platform::Platform::GetCachingInterface()",
    "dawn::platform::CachingInterface::CachingInterface()",
    "dawn::platform::CachingInterface::~CachingInterface()",
)

REQUIRED_NATIVE_SYMBOLS = (
    "dawn::native::DawnInstanceDescriptor::DawnInstanceDescriptor()",
    "dawn::native::Instance::SetPlatformForTesting(dawn::platform::Platform*)",
)


@dataclass(frozen=True)
class RegenResult:
    args_gn_path: Path
    build_dir: Path
    gn_gen_ok: bool
    built_targets: tuple[str, ...]
    missing_symbols: tuple[str, ...]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dawn-root",
        type=Path,
        default=DEFAULT_DAWN_ROOT,
        help=(
            "Path to the vendored Dawn tree "
            f"(default {DEFAULT_DAWN_ROOT.relative_to(REPO_ROOT)})"
        ),
    )
    parser.add_argument(
        "--out-name",
        default=DEFAULT_OUT_DIR_NAME,
        help=(
            "Name of the build directory under <dawn-root>/out/ "
            f"(default {DEFAULT_OUT_DIR_NAME})"
        ),
    )
    parser.add_argument(
        "--build",
        action="store_true",
        help="Run ninja for libdawn_platform.so and libdawn_native.so after gn gen.",
    )
    parser.add_argument(
        "--verify",
        action="store_true",
        help="After --build, verify the required C++ symbols export from each .so.",
    )
    parser.add_argument(
        "--summary-out",
        type=Path,
        default=None,
        help="Optional JSON summary path for audit.",
    )
    return parser.parse_args()


def run(cmd: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=str(cwd),
        text=True,
        capture_output=True,
        check=False,
    )


def locate_gn(dawn_root: Path) -> Path:
    candidates = [
        dawn_root / "buildtools" / "linux64" / "gn",
        dawn_root / "buildtools" / "mac" / "gn",
        dawn_root / "buildtools" / "win" / "gn.exe",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        f"could not locate Dawn's vendored gn binary under {dawn_root}/buildtools/"
    )


def write_args_gn(build_dir: Path) -> Path:
    build_dir.mkdir(parents=True, exist_ok=True)
    args_gn_path = build_dir / "args.gn"
    args_gn_path.write_text(CANONICAL_ARGS_GN, encoding="utf-8")
    return args_gn_path


def gn_gen(dawn_root: Path, build_dir: Path) -> bool:
    gn = locate_gn(dawn_root)
    result = run(
        [str(gn), "gen", str(build_dir.relative_to(dawn_root))],
        cwd=dawn_root,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        sys.stderr.write(result.stdout)
        return False
    sys.stdout.write(result.stdout.splitlines()[-1] + "\n" if result.stdout else "")
    return True


def ninja_build(dawn_root: Path, build_dir: Path, targets: tuple[str, ...]) -> tuple[str, ...]:
    built: list[str] = []
    build_rel = build_dir.relative_to(dawn_root)
    for target in targets:
        sys.stdout.write(f"ninja {target} ...\n")
        sys.stdout.flush()
        result = run(["ninja", "-C", str(build_rel), target], cwd=dawn_root)
        if result.returncode != 0:
            sys.stderr.write(result.stdout)
            sys.stderr.write(result.stderr)
            raise RuntimeError(f"ninja build failed for {target}")
        built.append(target)
    return tuple(built)


def list_exported_symbols(so_path: Path) -> set[str]:
    nm_result = subprocess.run(
        ["nm", "-D", "--defined-only", str(so_path)],
        text=True,
        capture_output=True,
        check=False,
    )
    if nm_result.returncode != 0:
        raise RuntimeError(f"nm failed on {so_path}: {nm_result.stderr.strip()}")
    cxxfilt_result = subprocess.run(
        ["c++filt"],
        input=nm_result.stdout,
        text=True,
        capture_output=True,
        check=False,
    )
    if cxxfilt_result.returncode != 0:
        raise RuntimeError(f"c++filt failed: {cxxfilt_result.stderr.strip()}")
    exported: set[str] = set()
    for line in cxxfilt_result.stdout.splitlines():
        parts = line.split(" ", 2)
        if len(parts) < 3:
            continue
        kind = parts[1]
        demangled = parts[2].strip()
        if kind == "T" and demangled:
            exported.add(demangled)
    return exported


def verify_symbols(
    build_dir: Path,
) -> tuple[str, ...]:
    missing: list[str] = []
    platform_so = build_dir / "libdawn_platform.so"
    native_so = build_dir / "libdawn_native.so"

    if platform_so.exists():
        exports = list_exported_symbols(platform_so)
        for required in REQUIRED_PLATFORM_SYMBOLS:
            if required not in exports:
                missing.append(f"libdawn_platform.so missing: {required}")
    else:
        missing.append(f"libdawn_platform.so not found at {platform_so}")

    if native_so.exists():
        exports = list_exported_symbols(native_so)
        for required in REQUIRED_NATIVE_SYMBOLS:
            if required not in exports:
                missing.append(f"libdawn_native.so missing: {required}")
    else:
        missing.append(f"libdawn_native.so not found at {native_so}")

    return tuple(missing)


def run_regen(
    dawn_root: Path,
    out_name: str,
    build: bool,
    verify: bool,
) -> RegenResult:
    if not dawn_root.exists():
        raise FileNotFoundError(f"Dawn root not found: {dawn_root}")
    build_dir = dawn_root / "out" / out_name
    args_gn_path = write_args_gn(build_dir)
    gn_ok = gn_gen(dawn_root, build_dir)
    built: tuple[str, ...] = ()
    missing: tuple[str, ...] = ()
    if build and gn_ok:
        built = ninja_build(dawn_root, build_dir, BUILD_TARGETS)
    if verify:
        missing = verify_symbols(build_dir)
    return RegenResult(
        args_gn_path=args_gn_path,
        build_dir=build_dir,
        gn_gen_ok=gn_ok,
        built_targets=built,
        missing_symbols=missing,
    )


def write_summary(result: RegenResult, out_path: Path) -> None:
    payload = {
        "argsGnPath": str(result.args_gn_path),
        "buildDir": str(result.build_dir),
        "gnGenOk": result.gn_gen_ok,
        "builtTargets": list(result.built_targets),
        "missingSymbols": list(result.missing_symbols),
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    result = run_regen(
        dawn_root=args.dawn_root.resolve(),
        out_name=args.out_name,
        build=args.build,
        verify=args.verify,
    )
    sys.stdout.write(f"args.gn: {result.args_gn_path}\n")
    sys.stdout.write(f"build dir: {result.build_dir}\n")
    sys.stdout.write(f"gn gen: {'ok' if result.gn_gen_ok else 'FAILED'}\n")
    if result.built_targets:
        sys.stdout.write(f"built targets: {', '.join(result.built_targets)}\n")
    if args.verify:
        if result.missing_symbols:
            sys.stdout.write("symbol verify FAILED:\n")
            for entry in result.missing_symbols:
                sys.stdout.write(f"  - {entry}\n")
        else:
            sys.stdout.write("symbol verify: all required symbols exported\n")
    if args.summary_out is not None:
        write_summary(result, args.summary_out)
        sys.stdout.write(f"summary: {args.summary_out}\n")
    if not result.gn_gen_ok:
        return 1
    if args.verify and result.missing_symbols:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
